//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16 [unused]
//   float4 globalScalars2;             // Offset:  192 Size:    16 [unused]
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16 [unused]
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16 [unused]
//   float4 gCSMResolution;             // Offset:  224 Size:    16 [unused]
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
// cbuffer cascadeshadows_rendering_locals
// {
//
//   row_major float4x4 viewToWorldProjectionParam;// Offset:    0 Size:    64
//   float4 perspectiveShearParam;      // Offset:   64 Size:    16
//   float4 shadowParams;               // Offset:   80 Size:    16
//   float4 shadowParams2;              // Offset:   96 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CloudSampler                      sampler      NA          NA             s5      1 
// SmoothStepSampler                 sampler      NA          NA             s6      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// depthBuffer                       texture   float        2dMS             t3      1 
// CloudSampler                      texture  float4          2d             t5      1 
// SmoothStepSampler                 texture  float4          2d             t6      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// cascadeshadows_rendering_locals    cbuffer      NA          NA           cb11      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1   xyz         2     NONE   float       
// TEXCOORD                 2   xyz         3     NONE   float       
// SV_SampleIndex           0   x           4   SAMPLE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
// Pixel Shader runs at sample frequency
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[15], immediateIndexed
dcl_constantbuffer CB6[12], immediateIndexed
dcl_constantbuffer CB11[6], immediateIndexed
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2dms(0) (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v1.xy
dcl_input_ps_sgv constant v4.x, sampleIndex
dcl_output o0.xyzw
dcl_temps 3
mad r0.xy, v1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mad r0.xy, r0.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), cb11[4].xyxx
mul r0.y, r0.y, cb11[1].w
mul r0.x, r0.x, cb11[0].w
mul r0.yzw, r0.yyyy, cb11[1].xxyz
mad r0.xyz, r0.xxxx, cb11[0].xyzx, r0.yzwy
add r0.xyz, r0.xyzx, -cb11[2].xyzx
mul r1.xy, v1.xyxx, cb2[14].xyxx
ftoi r1.xy, r1.xyxx
mov r1.zw, l(0,0,0,0)
ldms r0.w, r1.xyzw, t3.yzwx, v4.x
add r1.x, cb11[3].w, l(1.000000)
add r0.w, -r0.w, r1.x
div r0.w, cb11[2].w, r0.w
mad r0.xyz, r0.xyzx, r0.wwww, cb11[3].xyzx
mad_sat r0.w, r0.w, cb6[0].w, cb6[1].w
mul r1.xyz, r0.yyyy, cb6[1].xyzx
mad r1.xyz, r0.xxxx, cb6[0].xyzx, r1.xyzx
mad r1.xyz, r0.zzzz, cb6[2].xyzx, r1.xyzx
mad r1.xyz, r1.xyzx, cb6[7].xyzx, cb6[11].xyzx
mad r1.w, r1.y, l(0.250000), l(0.875000)
add r2.xyz, r1.xwzx, l(0.500000, 0.000000, 0.000000, 0.000000)
max r1.x, |r1.y|, |r1.x|
add r1.x, r1.x, l(-0.450000)
mul_sat r1.x, r1.x, l(15.000000)
sample_c_lz r1.y, r2.xyxx, t15.xxxx, s15, r2.z
mul r1.y, r1.y, l(4.000000)
dp4 r1.y, r1.yyyy, l(1.000000, 1.000000, 1.000000, 1.000000)
mad r0.w, r1.y, l(0.062500), r0.w
add r0.w, r1.x, r0.w
mov r1.x, -cb11[5].w
mov r1.yw, l(0,-0.000000,0,0.500000)
mad r0.xy, r0.xyxx, l(0.000286, 0.000286, 0.000000, 0.000000), r1.xyxx
mad_sat r0.z, r0.z, cb6[3].x, cb6[3].y
sqrt r0.z, r0.z
mad r0.z, -r0.z, cb6[3].z, l(1.000000)
sample r1.z, r0.xyxx, t5.xzyw, s5
sample r0.x, r1.zwzz, t6.xyzw, s6
mul r0.x, r0.z, r0.x
mul o0.xyzw, r0.xxxx, r0.wwww
ret 
// Approximately 41 instruction slots used
