//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16 [unused]
//   float4 globalScalars2;             // Offset:  192 Size:    16 [unused]
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// depthBuffer2                      texture   float        2dMS             t7      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   x           0   TARGET   float   x   
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[16], immediateIndexed
dcl_resource_texture2dms(0) (float,float,float,float) t7
dcl_input_ps linear v1.xy
dcl_output o0.x
dcl_temps 4
ftoi r0.xy, v1.xyxx
ult r1.xyz, l(2, 4, 6, 0), cb2[15].xxxx
if_nz cb2[15].x
  mov r0.z, l(0)
  ldms r1.w, r0.xyzz, t7.yzwx, l(0)
  ldms r2.x, r0.xyzz, t7.xyzw, l(1)
  max r2.y, r1.w, r2.x
  min r3.x, r2.y, l(1.000000)
  min r1.w, r1.w, r2.x
  max r3.y, r1.w, l(0.000000)
else 
  mov r3.xy, l(1.000000,0,0,0)
endif 
if_nz r1.x
  mov r0.w, l(0)
  ldms r1.x, r0.xyww, t7.xyzw, l(2)
  ldms r1.w, r0.xyww, t7.yzwx, l(3)
  max r2.x, r1.w, r1.x
  min r3.x, r2.x, r3.x
  min r1.x, r1.w, r1.x
  max r3.y, r1.x, r3.y
endif 
if_nz r1.y
  mov r2.xy, r0.xyxx
  mov r2.zw, l(0,0,0,0)
  ldms r1.x, r2.xyww, t7.xyzw, l(4)
  ldms r1.y, r2.xyzw, t7.yxzw, l(5)
  max r1.w, r1.y, r1.x
  min r3.x, r1.w, r3.x
  min r1.x, r1.y, r1.x
  max r3.y, r1.x, r3.y
endif 
if_nz r1.z
  mov r1.xy, r0.xyxx
  mov r1.zw, l(0,0,0,0)
  ldms r2.x, r1.xyww, t7.xyzw, l(6)
  ldms r1.x, r1.xyzw, t7.xyzw, l(7)
  max r1.y, r1.x, r2.x
  min r3.x, r1.y, r3.x
  min r1.x, r1.x, r2.x
  max r3.y, r1.x, r3.y
endif 
ult r1.xyzw, l(8, 10, 12, 14), cb2[15].xxxx
if_nz r1.x
  mov r2.xy, r0.xyxx
  mov r2.zw, l(0,0,0,0)
  ldms r1.x, r2.xyww, t7.xyzw, l(8)
  ldms r2.x, r2.xyzw, t7.xyzw, l(9)
  max r2.y, r1.x, r2.x
  min r3.x, r2.y, r3.x
  min r1.x, r1.x, r2.x
  max r3.y, r1.x, r3.y
endif 
if_nz r1.y
  mov r2.xy, r0.xyxx
  mov r2.zw, l(0,0,0,0)
  ldms r1.x, r2.xyww, t7.xyzw, l(10)
  ldms r1.y, r2.xyzw, t7.yxzw, l(11)
  max r2.x, r1.y, r1.x
  min r3.x, r2.x, r3.x
  min r1.x, r1.y, r1.x
  max r3.y, r1.x, r3.y
endif 
if_nz r1.z
  mov r2.xy, r0.xyxx
  mov r2.zw, l(0,0,0,0)
  ldms r1.x, r2.xyww, t7.xyzw, l(12)
  ldms r1.y, r2.xyzw, t7.yxzw, l(13)
  max r1.z, r1.y, r1.x
  min r3.x, r1.z, r3.x
  min r1.x, r1.y, r1.x
  max r3.y, r1.x, r3.y
endif 
if_nz r1.w
  mov r0.zw, l(0,0,0,0)
  ldms r1.x, r0.xyww, t7.xyzw, l(14)
  ldms r0.x, r0.xyzw, t7.xyzw, l(15)
  max r0.y, r0.x, r1.x
  min r3.x, r0.y, r3.x
  min r0.x, r0.x, r1.x
  max r3.y, r0.x, r3.y
endif 
add r0.x, r3.y, r3.x
mul o0.x, r0.x, l(0.500000)
ret 
// Approximately 85 instruction slots used
