//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16 [unused]
//   float4 globalScalars2;             // Offset:  192 Size:    16 [unused]
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16
//   float4 gCSMResolution;             // Offset:  224 Size:    16
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
// cbuffer cascadeshadows_recieving_locals
// {
//
//   float4 gCSMShaderVars_deferred;    // Offset:    0 Size:    16
//   float4 particleShadowsParams;      // Offset:   16 Size:    16
//
// }
//
// cbuffer cascadeshadows_rendering_locals
// {
//
//   row_major float4x4 viewToWorldProjectionParam;// Offset:    0 Size:    64
//   float4 perspectiveShearParam;      // Offset:   64 Size:    16
//   float4 shadowParams;               // Offset:   80 Size:    16
//   float4 shadowParams2;              // Offset:   96 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gCSMParticleShadowSamp            sampler      NA          NA             s2      1 
// CloudSampler                      sampler      NA          NA             s5      1 
// SmoothStepSampler                 sampler      NA          NA             s6      1 
// gCSMDitherTextureSamp             sampler      NA          NA            s14      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// gCSMParticleShadowTexture         texture  float4          2d             t2      1 
// depthBuffer                       texture   float        2dMS             t3      1 
// CloudSampler                      texture  float4          2d             t5      1 
// SmoothStepSampler                 texture  float4          2d             t6      1 
// gCSMDitherTextureSamp             texture  float4          2d            t14      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// cascadeshadows_rendering_locals    cbuffer      NA          NA           cb11      1 
// cascadeshadows_recieving_locals    cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1   xyz         2     NONE   float       
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// SV_SampleIndex           0   x           4   SAMPLE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
// Pixel Shader runs at sample frequency
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[15], immediateIndexed
dcl_constantbuffer CB6[15], dynamicIndexed
dcl_constantbuffer CB12[2], immediateIndexed
dcl_constantbuffer CB11[6], immediateIndexed
dcl_sampler s2, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s14, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2dms(0) (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v1.xy
dcl_input_ps linear sample v3.xyz
dcl_input_ps_sgv constant v4.x, sampleIndex
dcl_output o0.xyzw
dcl_temps 21
dcl_indexableTemp x0[4], 4
mad r0.xy, v1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mad r0.xy, r0.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), cb11[4].xyxx
mul r0.x, r0.x, cb11[0].w
mul r0.y, r0.y, cb11[1].w
mul r0.yzw, r0.yyyy, cb11[1].xxyz
mad r0.xyz, r0.xxxx, cb11[0].xyzx, r0.yzwy
add r0.xyz, r0.xyzx, -cb11[2].xyzx
mul r1.xy, v1.xyxx, cb2[14].xyxx
ftoi r2.xy, r1.xyxx
mov r2.zw, l(0,0,0,0)
ldms r0.w, r2.xyzw, t3.yzwx, v4.x
add r1.z, cb11[3].w, l(1.000000)
add r0.w, -r0.w, r1.z
div r0.w, cb11[2].w, r0.w
mad r0.xyz, r0.xyzx, r0.wwww, cb11[3].xyzx
mul r2.xyzw, r0.wwww, v3.yxyz
mul r1.xy, r1.xyxx, l(0.015625, 0.015625, 0.000000, 0.000000)
sample r1.x, r1.xyxx, t14.zxyw, s14
mul r1.x, r1.x, cb12[0].w
mad r1.yzw, r2.yyzw, cb6[4].xxyz, cb6[8].xxyz
mov x0[0].xyz, r1.yzwy
mad r3.xyz, r2.yzwy, cb6[5].xyzx, cb6[9].xyzx
mov x0[1].xyz, r3.xyzx
mad r4.xyz, r2.yzwy, cb6[6].xyzx, cb6[10].xyzx
mov x0[2].xyz, r4.xyzx
mad r5.xyz, r2.yzwy, cb6[7].xyzx, cb6[11].xyzx
mov x0[3].xyz, r5.xyzx
mul r3.zw, cb6[14].zzzw, l(0.000000, 0.000000, -0.346097, 0.328490)
mad r1.w, -cb6[14].z, l(1.500000), l(1.000000)
mad r1.x, r1.w, l(0.500000), -r1.x
max r1.w, |r4.y|, |r4.x|
lt r1.w, r1.w, r1.x
movc r1.w, r1.w, l(2), l(3)
max r3.x, |r3.y|, |r3.x|
lt r3.x, r3.x, r1.x
movc r1.w, r3.x, l(1), r1.w
max r1.y, |r1.z|, |r1.y|
lt r1.x, r1.y, r1.x
movc r1.x, r1.x, l(0), r1.w
mov r1.yzw, x0[r1.x + 0].xxyz
itof r3.x, r1.x
add r3.y, r3.x, l(0.500000)
mul r3.y, r3.y, l(0.250000)
eq r4.xyzw, l(0.000000, 1.000000, 2.000000, 3.000000), r3.xxxx
and r4.xyzw, r4.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
dp4 r3.x, r4.xyzw, cb6[12].xyzw
dp4 r4.x, r4.xyzw, cb6[13].xyzw
add r6.x, r1.y, l(0.500000)
mad r6.y, r1.z, l(0.250000), r3.y
ne r1.y, r3.x, l(0.000000)
add r1.z, r1.w, -r3.x
deriv_rtx r7.xyw, r6.xyxy
deriv_rtx r7.z, r1.z
deriv_rty r8.xyz, r6.yxyy
deriv_rty r8.w, r1.z
mul r3.xy, r7.ywyy, r8.ywyy
mad r9.xy, r7.xzxx, r8.xzxx, -r3.xyxx
div r3.x, l(1.000000, 1.000000, 1.000000, 1.000000), r9.x
mul r3.y, r7.z, r8.y
mad r9.z, r7.x, r8.w, -r3.y
mul r3.xy, r3.xxxx, r9.yzyy
max r3.xy, r3.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mad r1.z, -r4.x, r3.x, r1.z
mad r1.z, -r4.x, r3.y, r1.z
movc r4.z, r1.y, r1.z, r1.w
iadd r1.x, l(4), r1.x
mul r1.xyzw, l(0.250000, 1.000000, 0.250000, 1.000000), cb6[r1.x + 0].yxyz
deriv_rtx r7.xyzw, r2.yzwz
mul r7.xyzw, r1.yzwz, r7.xyzw
deriv_rty r2.xyzw, r2.xyzw
mul r1.xyzw, r1.xyzw, r2.xyzw
mul r2.xy, r1.ywyy, r7.ywyy
mad r2.xy, r7.xzxx, r1.xzxx, -r2.xyxx
div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r2.x
mul r1.y, r1.y, r7.z
mad r2.z, r7.x, r1.w, -r1.y
mul r1.xy, r1.xxxx, r2.yzyy
max r1.xy, r1.xyxx, l(-1.000000, -1.000000, 0.000000, 0.000000)
min r1.xy, r1.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
dp2 r6.z, r1.xyxx, r3.zwzz
mul r4.xy, cb6[14].zwzz, l(-0.346097, 0.328490, 0.000000, 0.000000)
add r2.xyz, r4.xyzx, r6.xyzx
mul r3.xyzw, cb6[14].zwzw, l(-0.799291, 0.201741, -0.031176, 0.179338)
dp2 r6.w, r1.xyxx, r3.xyxx
mul r4.xy, cb6[14].zwzz, l(-0.799291, 0.201741, 0.000000, 0.000000)
add r7.xyz, r6.xywx, r4.xyzx
dp2 r3.x, r1.xyxx, r3.zwzz
mul r4.xy, cb6[14].zwzz, l(-0.031176, 0.179338, 0.000000, 0.000000)
mov r3.yz, r6.xxyx
add r8.xyz, r3.yzxy, r4.xyzx
mul r9.xyzw, cb6[14].zwzw, l(0.514749, 0.253502, -0.072870, 0.008097)
dp2 r3.w, r1.xyxx, r9.xyxx
mul r4.xy, cb6[14].zwzz, l(0.514749, 0.253502, 0.000000, 0.000000)
add r10.xyz, r3.yzwy, r4.xyzx
dp2 r3.x, r1.xyxx, r9.zwzz
mul r4.xy, cb6[14].zwzz, l(-0.072870, 0.008097, 0.000000, 0.000000)
add r9.xyz, r3.yzxy, r4.xyzx
mul r11.xyzw, cb6[14].zwzw, l(-0.969781, 0.034522, 0.545547, 0.024129)
dp2 r3.w, r1.xyxx, r11.xyxx
mul r4.xy, cb6[14].zwzz, l(-0.969781, 0.034522, 0.000000, 0.000000)
add r12.xyz, r3.yzwy, r4.xyzx
dp2 r3.x, r1.xyxx, r11.zwzz
mul r4.xy, cb6[14].zwzz, l(0.545547, 0.024129, 0.000000, 0.000000)
add r11.xyz, r3.yzxy, r4.xyzx
mul r13.xyzw, cb6[14].zwzw, l(-0.028906, -0.136785, -0.479511, -0.244833)
dp2 r3.w, r1.xyxx, r13.xyxx
mul r4.xy, cb6[14].zwzz, l(-0.028906, -0.136785, 0.000000, 0.000000)
add r14.xyz, r3.yzwy, r4.xyzx
dp2 r3.x, r1.xyxx, r13.zwzz
mul r4.xy, cb6[14].zwzz, l(-0.479511, -0.244833, 0.000000, 0.000000)
add r13.xyz, r3.yzxy, r4.xyzx
mul r15.xyzw, cb6[14].zwzw, l(0.758788, -0.112109, 0.339353, -0.249328)
dp2 r3.w, r1.xyxx, r15.xyxx
mul r4.xy, cb6[14].zwzz, l(0.758788, -0.112109, 0.000000, 0.000000)
add r16.xyz, r3.yzwy, r4.xyzx
dp2 r3.x, r1.xyxx, r15.zwzz
mul r4.xy, cb6[14].zwzz, l(0.339353, -0.249328, 0.000000, 0.000000)
add r15.xyz, r3.yzxy, r4.xyzx
mul r17.xyzw, cb6[14].zwzw, l(1.070598, 0.208123, 1.294038, -0.018078)
dp2 r3.w, r1.xyxx, r17.xyxx
mul r4.xy, cb6[14].zwzz, l(1.070598, 0.208123, 0.000000, 0.000000)
add r18.xyz, r3.yzwy, r4.xyzx
dp2 r3.x, r1.xyxx, r17.zwzz
mul r4.xy, cb6[14].zwzz, l(1.294038, -0.018078, 0.000000, 0.000000)
add r17.xyz, r3.yzxy, r4.xyzx
mul r19.xyzw, cb6[14].zwzw, l(-0.747563, -0.113974, 0.947722, -0.248764)
dp2 r3.w, r1.xyxx, r19.xyxx
mul r4.xy, cb6[14].zwzz, l(-0.747563, -0.113974, 0.000000, 0.000000)
add r20.xyz, r3.yzwy, r4.xyzx
dp2 r3.x, r1.xyxx, r19.zwzz
mul r4.xy, cb6[14].zwzz, l(0.947722, -0.248764, 0.000000, 0.000000)
add r19.xyz, r3.yzxy, r4.xyzx
mul r1.zw, cb6[14].zzzw, l(0.000000, 0.000000, -1.343153, -0.088584)
dp2 r3.w, r1.xyxx, r1.zwzz
mul r4.xy, cb6[14].zwzz, l(-1.343153, -0.088584, 0.000000, 0.000000)
add r1.xyz, r3.yzwy, r4.xyzx
sample_c_lz r2.x, r2.xyxx, t15.xxxx, s15, r2.z
sample_c_lz r2.y, r7.xyxx, t15.xxxx, s15, r7.z
sample_c_lz r2.z, r8.xyxx, t15.xxxx, s15, r8.z
sample_c_lz r2.w, r10.xyxx, t15.xxxx, s15, r10.z
sample_c_lz r3.x, r9.xyxx, t15.xxxx, s15, r9.z
sample_c_lz r3.y, r12.xyxx, t15.xxxx, s15, r12.z
sample_c_lz r3.z, r11.xyxx, t15.xxxx, s15, r11.z
sample_c_lz r3.w, r14.xyxx, t15.xxxx, s15, r14.z
sample_c_lz r4.x, r13.xyxx, t15.xxxx, s15, r13.z
sample_c_lz r4.y, r16.xyxx, t15.xxxx, s15, r16.z
sample_c_lz r4.z, r15.xyxx, t15.xxxx, s15, r15.z
sample_c_lz r4.w, r18.xyxx, t15.xxxx, s15, r18.z
sample_c_lz r7.x, r17.xyxx, t15.xxxx, s15, r17.z
sample_c_lz r7.y, r20.xyxx, t15.xxxx, s15, r20.z
sample_c_lz r7.z, r19.xyxx, t15.xxxx, s15, r19.z
sample_c_lz r7.w, r1.xyxx, t15.xxxx, s15, r1.z
add r1.xyzw, r2.xyzw, r3.xyzw
add r1.xyzw, r4.xyzw, r1.xyzw
add r1.xyzw, r7.xyzw, r1.xyzw
dp4 r1.x, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mul r1.x, r1.x, l(0.062500)
ne r1.z, cb12[1].x, l(0.000000)
if_nz r1.z
  sample r1.z, r6.xyxx, t2.xywz, s2
  add r1.y, -r1.z, l(1.000000)
else 
  mov r1.y, l(1.000000)
endif 
mad_sat r0.w, r0.w, cb6[0].w, cb6[1].w
max r1.z, |r5.y|, |r5.x|
mad_sat r1.z, r1.z, l(15.000000), l(-6.300000)
add r0.w, -r0.w, l(1.000000)
mad r1.xy, r0.wwww, r1.zzzz, r1.xyxx
mul r1.xy, r1.xyxx, r1.xyxx
min r1.yz, r1.xxyx, l(0.000000, 1.000000, 1.000000, 0.000000)
ne r0.w, l(0.000000, 0.000000, 0.000000, 0.000000), cb12[1].y
mul r1.w, r1.z, r1.y
movc r1.x, r0.w, r1.w, r1.y
mov r2.x, -cb11[5].w
mov r2.yw, l(0,-0.000000,0,0.500000)
mad r0.xy, r0.xyxx, l(0.000286, 0.000286, 0.000000, 0.000000), r2.xyxx
sample r2.z, r0.xyxx, t5.xzyw, s5
sample r0.x, r2.zwzz, t6.xyzw, s6
mad_sat r0.y, r0.z, cb6[3].x, cb6[3].y
sqrt r0.y, r0.y
mad r0.y, -r0.y, cb6[3].z, l(1.000000)
mul r0.x, r0.y, r0.x
mul o0.xyzw, r0.xxxx, r1.xzzz
ret 
// Approximately 186 instruction slots used
