//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// earlyOut                          texture   float          2d             t6      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// SV_SampleIndex           0   x           1   SAMPLE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_resource_texture2d (float,float,float,float) t6
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_output o0.xyzw
dcl_temps 3
mov r0.zw, l(0,0,0,0)
ftoi r1.xy, v0.xyxx
iadd r0.xy, r1.xyxx, l(-1, 1, 0, 0)
ld r0.x, r0.xyzw, t6.xyzw
mov r2.zw, l(0,0,0,0)
iadd r2.xy, r1.xyxx, l(0, 1, 0, 0)
ld r0.y, r2.xyzw, t6.yxzw
add r0.x, r0.y, r0.x
mov r2.zw, l(0,0,0,0)
iadd r2.xy, r1.xyxx, l(1, 1, 0, 0)
ld r0.y, r2.xyzw, t6.yxzw
add r0.x, r0.y, r0.x
mov r2.zw, l(0,0,0,0)
iadd r2.xy, r1.xyxx, l(-1, 0, 0, 0)
ld r0.y, r2.xyzw, t6.yxzw
add r0.x, r0.y, r0.x
mov r1.zw, l(0,0,0,0)
ld r0.y, r1.xyww, t6.yxzw
add r0.x, r0.y, r0.x
iadd r2.xyzw, r1.xyww, l(1, 0, 0, 0)
ld r0.y, r2.xyzw, t6.yxzw
add r0.x, r0.y, r0.x
iadd r2.xyzw, r1.xyww, l(-1, -1, 0, 0)
ld r0.y, r2.xyzw, t6.yxzw
add r0.x, r0.y, r0.x
iadd r2.xyzw, r1.xyww, l(0, -1, 0, 0)
iadd r1.xyzw, r1.xyzw, l(1, -1, 0, 0)
ld r0.y, r1.xyzw, t6.yxzw
ld r0.z, r2.xyzw, t6.yzxw
add r0.x, r0.z, r0.x
add r0.x, r0.y, r0.x
mul o0.xyzw, r0.xxxx, l(0.111111, 0.111111, 0.111111, 0.111111)
ret 
// Approximately 33 instruction slots used
