//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer more_stuff
// {
//
//   float4 gEntitySelectColor[2];      // Offset:    0 Size:    32 [unused]
//   float4 gAmbientOcclusionEffect;    // Offset:   32 Size:    16 [unused]
//   float4 gDynamicBakesAndWetness;    // Offset:   48 Size:    16
//   float4 gAlphaRefVec0;              // Offset:   64 Size:    16
//   float4 gAlphaRefVec1;              // Offset:   80 Size:    16 [unused]
//   float gAlphaTestRef;               // Offset:   96 Size:     4 [unused]
//   bool gTreesUseDiscard;             // Offset:  100 Size:     4 [unused]
//   float gReflectionMipCount;         // Offset:  104 Size:     4 [unused]
//   bool gUseTransparencyAA;           // Offset:  108 Size:     4 [unused]
//   bool gUseFogRay;                   // Offset:  112 Size:     4 [unused]
//
// }
//
// cbuffer megashader_locals
// {
//
//   float specularFresnel;             // Offset:    0 Size:     4 [unused]
//   float specularFalloffMult;         // Offset:    4 Size:     4 [unused]
//   float specularIntensityMult;       // Offset:    8 Size:     4
//   float bumpiness;                   // Offset:   12 Size:     4
//   float useTessellation;             // Offset:   16 Size:     4 [unused]
//   float HardAlphaBlend;              // Offset:   20 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// BumpSampler                       sampler      NA          NA             s2      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// BumpSampler                       texture  float4          2d             t2      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// more_stuff                        cbuffer      NA          NA            cb5      1 
// megashader_locals                 cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// COLOR                    0   xyzw        1     NONE   float   x  w
// TEXCOORD                 0   xy          2     NONE   float   xy  
// TEXCOORD                 1   xyz         3     NONE   float   xyz 
// TEXCOORD                 4   xyz         4     NONE   float   xyz 
// TEXCOORD                 5   xyz         5     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
//
ps_4_0
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000} }
dcl_constantbuffer CB2[13], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB12[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xw
dcl_input_ps linear v2.xy
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_temps 2
ftou r0.xy, v0.xyxx
and r0.xy, r0.xyxx, l(1, 1, 0, 0)
ishl r0.y, r0.y, l(1)
iadd r0.x, r0.x, r0.y
dp4 r0.x, cb2[0].xyzw, icb[r0.x + 0].xyzw
lt r0.x, r0.x, l(1.000000)
discard_nz r0.x
sample r0.xyzw, v2.xyxx, t0.xyzw, s0
mul r0.x, r0.w, cb2[11].x
ge r0.x, cb5[4].x, r0.x
discard_nz r0.x
sample r0.xyzw, v2.xyxx, t2.xyzw, s2
mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.z, r0.xyxx, r0.xyxx
add r0.z, -r0.z, l(1.000000)
sqrt r0.z, |r0.z|
max r1.x, cb12[0].w, l(0.001000)
mul r0.xy, r0.xyxx, r1.xxxx
mul r1.xyz, r0.yyyy, v5.xyzx
mad r1.xyz, r0.xxxx, v4.xyzx, r1.xyzx
mad r0.xyz, r0.zzzz, v3.xyzx, r1.xyzx
dp3 r1.x, r0.xyzx, r0.xyzx
rsq r1.x, r1.x
mul r1.yzw, r0.xxyz, r1.xxxx
mul r0.x, v1.x, cb2[11].z
mad o1.xyz, r1.yzwy, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
mul r0.y, r0.w, v1.w
mul o1.w, r0.y, cb2[11].x
mad r0.y, r0.z, r1.x, l(-0.350000)
mul_sat r0.y, r0.y, l(1.538462)
mul r0.y, r0.y, cb5[3].z
add r0.z, -cb2[12].z, l(1.000000)
mul r0.y, r0.z, r0.y
mul r0.z, r0.x, r0.y
add_sat r0.w, cb12[0].z, l(0.700000)
mul r0.xy, r0.wwww, r0.zzzz
mul r0.xyz, r0.xyzx, l(0.500000, 0.488281, 0.970000, 0.000000)
sqrt o2.xy, r0.xyxx
mov o2.z, r0.z
mov o2.w, l(0)
mov o0.xyzw, l(0,0,0,0)
mov o3.xyzw, l(0,0,0,0)
ret 
// Approximately 43 instruction slots used
