//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16
//   float4 globalScreenSize;           // Offset:  224 Size:    16
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16
//   float4 gDirectionalColour;         // Offset:   16 Size:    16
//   int gNumForwardLights;             // Offset:   32 Size:     4
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128
//   float gLightConeScale[8];          // Offset:  432 Size:   116
//   float gLightConeOffset[8];         // Offset:  560 Size:   116
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80
//   float4 globalFogColor;             // Offset:  880 Size:    16
//   float4 globalFogColorE;            // Offset:  896 Size:    16
//   float4 globalFogColorN;            // Offset:  912 Size:    16
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer more_stuff
// {
//
//   float4 gEntitySelectColor[2];      // Offset:    0 Size:    32 [unused]
//   float4 gAmbientOcclusionEffect;    // Offset:   32 Size:    16 [unused]
//   float4 gDynamicBakesAndWetness;    // Offset:   48 Size:    16 [unused]
//   float4 gAlphaRefVec0;              // Offset:   64 Size:    16 [unused]
//   float4 gAlphaRefVec1;              // Offset:   80 Size:    16 [unused]
//   float gAlphaTestRef;               // Offset:   96 Size:     4 [unused]
//   bool gTreesUseDiscard;             // Offset:  100 Size:     4 [unused]
//   float gReflectionMipCount;         // Offset:  104 Size:     4 [unused]
//   bool gUseTransparencyAA;           // Offset:  108 Size:     4 [unused]
//   bool gUseFogRay;                   // Offset:  112 Size:     4
//
// }
//
// cbuffer megashader_locals
// {
//
//   float specularFresnel;             // Offset:    0 Size:     4
//   float specularFalloffMult;         // Offset:    4 Size:     4
//   float specularIntensityMult;       // Offset:    8 Size:     4
//   float wetnessMultiplier;           // Offset:   12 Size:     4 [unused]
//   float useTessellation;             // Offset:   16 Size:     4 [unused]
//   float HardAlphaBlend;              // Offset:   20 Size:     4 [unused]
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16
//   float4 gCSMResolution;             // Offset:  224 Size:    16
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// FogRaySampler                     sampler      NA          NA            s11      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// FogRaySampler                     texture  float4          2d            t11      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// more_stuff                        cbuffer      NA          NA            cb5      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// megashader_locals                 cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xy w
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 6   xyzw        3     NONE   float   xyz 
// SV_Position              0   xyzw        4      POS   float   xy  
// SV_ClipDistance          0   xyzw        5  CLIPDST   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB1[16], immediateIndexed
dcl_constantbuffer CB2[19], immediateIndexed
dcl_constantbuffer CB3[59], immediateIndexed
dcl_constantbuffer CB5[8], immediateIndexed
dcl_constantbuffer CB12[1], immediateIndexed
dcl_constantbuffer CB6[15], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s11, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v0.xyw
dcl_input_ps linear v1.xy
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps_siv linear noperspective v4.xy, position
dcl_output o0.xyzw
dcl_temps 25
dcl_indexableTemp x0[4], 4
sample r0.xyzw, v1.xyxx, t0.xyzw, s0
dp3 r1.x, v2.xyzx, v2.xyzx
rsq r1.x, r1.x
mul r1.yzw, r1.xxxx, v2.xxyz
mul r0.w, r0.w, v0.w
mul r2.xy, v0.xyxx, cb2[11].zyzz
mul r0.xyz, r0.xyzx, r0.xyzx
add r3.xyz, -v3.xyzx, cb1[15].xyzx
dp3 r2.z, r3.xyzx, r3.xyzx
rsq r2.z, r2.z
mul r4.xyz, r2.zzzz, r3.xyzx
mad r5.xyz, r3.xyzx, r2.zzzz, -cb3[0].xyzx
dp3 r2.w, r5.xyzx, r5.xyzx
rsq r2.w, r2.w
mul r5.xyz, r2.wwww, r5.xyzx
mov_sat r2.w, cb12[0].z
mul r2.xy, r2.xyxx, r2.xyxx
add r3.w, cb12[0].y, l(-500.000000)
max r3.w, r3.w, l(0.000000)
add r4.w, -r3.w, cb12[0].y
mul r3.w, r3.w, l(558.000000)
mad r3.w, r4.w, l(3.000000), r3.w
dp3 r4.w, r3.xyzx, cb1[14].xyzx
add r6.xyz, v3.xyzx, -cb1[15].xyzx
mul r7.xyz, r6.yyyy, cb6[1].xyzx
mad r7.xyz, r6.xxxx, cb6[0].xyzx, r7.xyzx
mad r7.xyz, r6.zzzz, cb6[2].xyzx, r7.xyzx
mad r8.xyz, r7.xyzx, cb6[4].xyzx, cb6[8].xyzx
mov x0[0].xyz, r8.xyzx
mad r9.xyz, r7.xyzx, cb6[5].xyzx, cb6[9].xyzx
mov x0[1].xyz, r9.xyzx
mad r10.xyz, r7.xyzx, cb6[6].xyzx, cb6[10].xyzx
mov x0[2].xyz, r10.xyzx
mad r7.xyz, r7.xyzx, cb6[7].xyzx, cb6[11].xyzx
mov x0[3].xyz, r7.xyzx
mul r11.yw, cb6[14].zzzw, l(0.000000, -0.346097, 0.000000, 0.328490)
mad r5.w, -cb6[14].z, l(1.500000), l(1.000000)
mul r5.w, r5.w, l(0.500000)
max r6.w, |r10.y|, |r10.x|
lt r6.w, r6.w, r5.w
movc r6.w, r6.w, l(2), l(3)
max r7.z, |r9.y|, |r9.x|
lt r7.z, r7.z, r5.w
movc r6.w, r7.z, l(1), r6.w
max r7.z, |r8.y|, |r8.x|
lt r5.w, r7.z, r5.w
movc r5.w, r5.w, l(0), r6.w
mov r8.xyz, x0[r5.w + 0].xyzx
itof r5.w, r5.w
add r6.w, r5.w, l(0.500000)
mul r6.w, r6.w, l(0.250000)
eq r9.xyzw, l(0.000000, 1.000000, 2.000000, 3.000000), r5.wwww
and r9.xyzw, r9.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
dp4 r5.w, r9.xyzw, cb6[12].xyzw
dp4 r7.z, r9.xyzw, cb6[13].xyzw
add r9.x, r8.x, l(0.500000)
mad r9.y, r8.y, l(0.250000), r6.w
ne r6.w, r5.w, l(0.000000)
add r5.w, -r5.w, r8.z
deriv_rtx r10.xyw, r9.xyxy
deriv_rtx r10.z, r5.w
deriv_rty r12.xyz, r9.yxyy
deriv_rty r12.w, r5.w
mul r8.xy, r10.ywyy, r12.ywyy
mad r13.xy, r10.xzxx, r12.xzxx, -r8.xyxx
div r7.w, l(1.000000, 1.000000, 1.000000, 1.000000), r13.x
mul r8.x, r10.z, r12.y
mad r13.z, r10.x, r12.w, -r8.x
mul r8.xy, r7.wwww, r13.yzyy
max r8.xy, r8.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r8.xy, r8.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mad r5.w, -r7.z, r8.x, r5.w
mad r5.w, -r7.z, r8.y, r5.w
movc r11.z, r6.w, r5.w, r8.z
mov r9.z, l(0)
add r8.xyz, r9.xyzx, r11.ywzy
mul r11.xy, cb6[14].zwzz, l(-0.799291, 0.201741, 0.000000, 0.000000)
add r10.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.031176, 0.179338, 0.000000, 0.000000)
add r12.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(0.514749, 0.253502, 0.000000, 0.000000)
add r13.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.072870, 0.008097, 0.000000, 0.000000)
add r14.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.969781, 0.034522, 0.000000, 0.000000)
add r15.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(0.545547, 0.024129, 0.000000, 0.000000)
add r16.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.028906, -0.136785, 0.000000, 0.000000)
add r17.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.479511, -0.244833, 0.000000, 0.000000)
add r18.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(0.758788, -0.112109, 0.000000, 0.000000)
add r19.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(0.339353, -0.249328, 0.000000, 0.000000)
add r20.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(1.070598, 0.208123, 0.000000, 0.000000)
add r21.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(1.294038, -0.018078, 0.000000, 0.000000)
add r22.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.747563, -0.113974, 0.000000, 0.000000)
add r23.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(0.947722, -0.248764, 0.000000, 0.000000)
add r24.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-1.343153, -0.088584, 0.000000, 0.000000)
add r9.xyz, r9.xyzx, r11.xyzx
sample_c_lz r8.x, r8.xyxx, t15.xxxx, s15, r8.z
sample_c_lz r8.y, r10.xyxx, t15.xxxx, s15, r10.z
sample_c_lz r8.z, r12.xyxx, t15.xxxx, s15, r12.z
sample_c_lz r8.w, r13.xyxx, t15.xxxx, s15, r13.z
sample_c_lz r10.x, r14.xyxx, t15.xxxx, s15, r14.z
sample_c_lz r10.y, r15.xyxx, t15.xxxx, s15, r15.z
sample_c_lz r10.z, r16.xyxx, t15.xxxx, s15, r16.z
sample_c_lz r10.w, r17.xyxx, t15.xxxx, s15, r17.z
sample_c_lz r11.x, r18.xyxx, t15.xxxx, s15, r18.z
sample_c_lz r11.y, r19.xyxx, t15.xxxx, s15, r19.z
sample_c_lz r11.z, r20.xyxx, t15.xxxx, s15, r20.z
sample_c_lz r11.w, r21.xyxx, t15.xxxx, s15, r21.z
sample_c_lz r12.x, r22.xyxx, t15.xxxx, s15, r22.z
sample_c_lz r12.y, r23.xyxx, t15.xxxx, s15, r23.z
sample_c_lz r12.z, r24.xyxx, t15.xxxx, s15, r24.z
sample_c_lz r12.w, r9.xyxx, t15.xxxx, s15, r9.z
add r8.xyzw, r8.xyzw, r10.xyzw
add r8.xyzw, r11.xyzw, r8.xyzw
add r8.xyzw, r12.xyzw, r8.xyzw
dp4 r5.w, r8.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mad_sat r4.w, r4.w, cb6[0].w, cb6[1].w
max r6.w, |r7.y|, |r7.x|
mad_sat r6.w, r6.w, l(15.000000), l(-6.300000)
add r4.w, -r4.w, l(1.000000)
mul r4.w, r6.w, r4.w
mad r4.w, r5.w, l(0.062500), r4.w
mul r4.w, r4.w, r4.w
min r4.w, r4.w, l(1.000000)
mad_sat r5.w, v3.z, cb6[3].x, cb6[3].y
sqrt r5.w, r5.w
mul r5.w, r5.w, cb6[3].z
mad r4.w, r5.w, -r4.w, r4.w
dp3_sat r5.w, r1.yzwy, -cb3[0].xyzx
dp3_sat r7.x, r4.xyzx, r1.yzwy
dp3_sat r7.y, r5.xyzx, -cb3[0].xyzx
add r7.xy, -r7.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r7.zw, r7.xxxy, r7.xxxy
mul r7.zw, r7.zzzw, r7.zzzw
mul r7.xy, r7.xyxx, r7.zwzz
add r6.w, -cb12[0].x, l(1.000000)
mad r7.xy, cb12[0].xxxx, r7.xyxx, r6.wwww
add r7.zw, r3.wwww, l(0.000000, 0.000000, 2.000000, 0.000000)
mul r3.w, r7.z, l(0.125000)
mad r7.x, -r2.w, r7.x, l(1.000000)
dp3 r5.x, r1.yzwy, r5.xyzx
add_sat r5.x, r5.x, l(0.000000)
log r5.x, r5.x
mul r5.x, r5.x, r7.w
exp r5.x, r5.x
mul r5.x, r7.y, r5.x
mul r5.x, r3.w, r5.x
mul r5.x, r2.w, r5.x
mul r5.x, r5.w, r5.x
mul r5.y, r5.w, r7.x
mad r5.xyz, r0.xyzx, r5.yyyy, r5.xxxx
mul r5.xyz, r5.xyzx, cb3[1].xyzx
ige r5.w, l(0), cb3[2].x
if_z r5.w
  eq r7.y, cb3[19].w, l(0.000000)
  add r8.xyz, -v3.xyzx, cb3[3].xyzx
  add r9.xyz, v3.xyzx, -cb3[3].xyzx
  dp3 r7.z, r9.xyzx, cb3[11].xyzx
  div_sat r7.z, r7.z, cb3[19].w
  mul r7.z, r7.z, cb3[19].w
  mad r9.xyz, cb3[11].xyzx, r7.zzzz, cb3[3].xyzx
  add r9.xyz, r9.xyzx, -v3.xyzx
  movc r8.xyz, r7.yyyy, r8.xyzx, r9.xyzx
  dp3 r7.y, r8.xyzx, r8.xyzx
  add r8.xyz, r8.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
  dp3 r7.z, r8.xyzx, r8.xyzx
  rsq r7.z, r7.z
  mul r8.xyz, r7.zzzz, r8.xyzx
  mad_sat r7.y, -r7.y, cb3[3].w, l(1.000000)
  add r7.z, -cb3[11].w, l(1.000000)
  mad r7.z, r7.z, r7.y, cb3[11].w
  div r7.y, r7.y, r7.z
  dp3 r7.z, r8.xyzx, -cb3[11].xyzx
  mad_sat r7.z, r7.z, cb3[27].x, cb3[35].x
  dp3_sat r8.w, r8.xyzx, r1.yzwy
  mul r7.z, r7.z, r8.w
  mul r8.w, r7.y, r7.z
  mul r9.xyz, r8.wwww, cb3[19].xyzx
  mul r9.xyz, r0.xyzx, r9.xyzx
  mad r8.xyz, r3.xyzx, r2.zzzz, r8.xyzx
  dp3 r8.w, r8.xyzx, r8.xyzx
  rsq r8.w, r8.w
  mul r8.xyz, r8.wwww, r8.xyzx
  dp3_sat r8.w, r8.xyzx, r4.xyzx
  add r8.w, -r8.w, l(1.000000)
  mul r9.w, r8.w, r8.w
  mul r9.w, r9.w, r9.w
  mul r8.w, r8.w, r9.w
  mad r8.w, cb12[0].x, r8.w, r6.w
  dp3_sat r8.x, r8.xyzx, r1.yzwy
  log r8.x, r8.x
  mul r8.x, r7.w, r8.x
  exp r8.x, r8.x
  mul r8.x, r8.x, r8.w
  mul r7.z, r7.z, r8.x
  mul r7.y, r7.y, r7.z
  mul r7.y, r3.w, r7.y
  mul r8.xyz, r7.yyyy, cb3[19].xyzx
else 
  mov r9.xyz, l(0,0,0,0)
  mov r8.xyz, l(0,0,0,0)
endif 
ilt r7.y, l(0), cb3[2].x
if_nz r7.y
  ige r7.z, l(1), cb3[2].x
  or r7.y, r5.w, r7.y
  movc r5.w, r7.z, r7.y, r5.w
  if_z r5.w
    eq r7.y, cb3[20].w, l(0.000000)
    add r10.xyz, -v3.xyzx, cb3[4].xyzx
    add r11.xyz, v3.xyzx, -cb3[4].xyzx
    dp3 r7.z, r11.xyzx, cb3[12].xyzx
    div_sat r7.z, r7.z, cb3[20].w
    mul r7.z, r7.z, cb3[20].w
    mad r11.xyz, cb3[12].xyzx, r7.zzzz, cb3[4].xyzx
    add r11.xyz, r11.xyzx, -v3.xyzx
    movc r10.xyz, r7.yyyy, r10.xyzx, r11.xyzx
    dp3 r7.y, r10.xyzx, r10.xyzx
    add r10.xyz, r10.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r7.z, r10.xyzx, r10.xyzx
    rsq r7.z, r7.z
    mul r10.xyz, r7.zzzz, r10.xyzx
    mad_sat r7.y, -r7.y, cb3[4].w, l(1.000000)
    add r7.z, -cb3[12].w, l(1.000000)
    mad r7.z, r7.z, r7.y, cb3[12].w
    div r7.y, r7.y, r7.z
    dp3 r7.z, r10.xyzx, -cb3[12].xyzx
    mad_sat r7.z, r7.z, cb3[28].x, cb3[36].x
    dp3_sat r8.w, r10.xyzx, r1.yzwy
    mul r7.z, r7.z, r8.w
    mul r8.w, r7.y, r7.z
    mul r11.xyz, r8.wwww, cb3[20].xyzx
    mad r9.xyz, r11.xyzx, r0.xyzx, r9.xyzx
    mad r10.xyz, r3.xyzx, r2.zzzz, r10.xyzx
    dp3 r8.w, r10.xyzx, r10.xyzx
    rsq r8.w, r8.w
    mul r10.xyz, r8.wwww, r10.xyzx
    dp3_sat r8.w, r10.xyzx, r4.xyzx
    add r8.w, -r8.w, l(1.000000)
    mul r9.w, r8.w, r8.w
    mul r9.w, r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mad r8.w, cb12[0].x, r8.w, r6.w
    dp3_sat r9.w, r10.xyzx, r1.yzwy
    log r9.w, r9.w
    mul r9.w, r7.w, r9.w
    exp r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mul r7.z, r7.z, r8.w
    mul r7.y, r7.y, r7.z
    mul r7.y, r3.w, r7.y
    mad r8.xyz, r7.yyyy, cb3[20].xyzx, r8.xyzx
  endif 
else 
  mov r5.w, l(-1)
endif 
if_z r5.w
  ige r7.y, l(2), cb3[2].x
  or r5.w, r5.w, r7.y
  if_z r5.w
    eq r7.y, cb3[21].w, l(0.000000)
    add r10.xyz, -v3.xyzx, cb3[5].xyzx
    add r11.xyz, v3.xyzx, -cb3[5].xyzx
    dp3 r7.z, r11.xyzx, cb3[13].xyzx
    div_sat r7.z, r7.z, cb3[21].w
    mul r7.z, r7.z, cb3[21].w
    mad r11.xyz, cb3[13].xyzx, r7.zzzz, cb3[5].xyzx
    add r11.xyz, r11.xyzx, -v3.xyzx
    movc r10.xyz, r7.yyyy, r10.xyzx, r11.xyzx
    dp3 r7.y, r10.xyzx, r10.xyzx
    add r10.xyz, r10.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r7.z, r10.xyzx, r10.xyzx
    rsq r7.z, r7.z
    mul r10.xyz, r7.zzzz, r10.xyzx
    mad_sat r7.y, -r7.y, cb3[5].w, l(1.000000)
    add r7.z, -cb3[13].w, l(1.000000)
    mad r7.z, r7.z, r7.y, cb3[13].w
    div r7.y, r7.y, r7.z
    dp3 r7.z, r10.xyzx, -cb3[13].xyzx
    mad_sat r7.z, r7.z, cb3[29].x, cb3[37].x
    dp3_sat r8.w, r10.xyzx, r1.yzwy
    mul r7.z, r7.z, r8.w
    mul r8.w, r7.y, r7.z
    mul r11.xyz, r8.wwww, cb3[21].xyzx
    mad r9.xyz, r11.xyzx, r0.xyzx, r9.xyzx
    mad r10.xyz, r3.xyzx, r2.zzzz, r10.xyzx
    dp3 r8.w, r10.xyzx, r10.xyzx
    rsq r8.w, r8.w
    mul r10.xyz, r8.wwww, r10.xyzx
    dp3_sat r8.w, r10.xyzx, r4.xyzx
    add r8.w, -r8.w, l(1.000000)
    mul r9.w, r8.w, r8.w
    mul r9.w, r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mad r8.w, cb12[0].x, r8.w, r6.w
    dp3_sat r9.w, r10.xyzx, r1.yzwy
    log r9.w, r9.w
    mul r9.w, r7.w, r9.w
    exp r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mul r7.z, r7.z, r8.w
    mul r7.y, r7.y, r7.z
    mul r7.y, r3.w, r7.y
    mad r8.xyz, r7.yyyy, cb3[21].xyzx, r8.xyzx
  endif 
else 
  mov r5.w, l(-1)
endif 
if_z r5.w
  ige r7.y, l(3), cb3[2].x
  or r5.w, r5.w, r7.y
  if_z r5.w
    eq r5.w, cb3[22].w, l(0.000000)
    add r10.xyz, -v3.xyzx, cb3[6].xyzx
    add r11.xyz, v3.xyzx, -cb3[6].xyzx
    dp3 r7.y, r11.xyzx, cb3[14].xyzx
    div_sat r7.y, r7.y, cb3[22].w
    mul r7.y, r7.y, cb3[22].w
    mad r11.xyz, cb3[14].xyzx, r7.yyyy, cb3[6].xyzx
    add r11.xyz, r11.xyzx, -v3.xyzx
    movc r10.xyz, r5.wwww, r10.xyzx, r11.xyzx
    dp3 r5.w, r10.xyzx, r10.xyzx
    add r10.xyz, r10.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r7.y, r10.xyzx, r10.xyzx
    rsq r7.y, r7.y
    mul r10.xyz, r7.yyyy, r10.xyzx
    mad_sat r5.w, -r5.w, cb3[6].w, l(1.000000)
    add r7.y, -cb3[14].w, l(1.000000)
    mad r7.y, r7.y, r5.w, cb3[14].w
    div r5.w, r5.w, r7.y
    dp3 r7.y, r10.xyzx, -cb3[14].xyzx
    mad_sat r7.y, r7.y, cb3[30].x, cb3[38].x
    dp3_sat r7.z, r10.xyzx, r1.yzwy
    mul r7.y, r7.y, r7.z
    mul r7.z, r5.w, r7.y
    mul r11.xyz, r7.zzzz, cb3[22].xyzx
    mad r9.xyz, r11.xyzx, r0.xyzx, r9.xyzx
    mad r3.xyz, r3.xyzx, r2.zzzz, r10.xyzx
    dp3 r2.z, r3.xyzx, r3.xyzx
    rsq r2.z, r2.z
    mul r3.xyz, r2.zzzz, r3.xyzx
    dp3_sat r2.z, r3.xyzx, r4.xyzx
    add r2.z, -r2.z, l(1.000000)
    mul r4.x, r2.z, r2.z
    mul r4.x, r4.x, r4.x
    mul r2.z, r2.z, r4.x
    mad r2.z, cb12[0].x, r2.z, r6.w
    dp3_sat r3.x, r3.xyzx, r1.yzwy
    log r3.x, r3.x
    mul r3.x, r3.x, r7.w
    exp r3.x, r3.x
    mul r2.z, r2.z, r3.x
    mul r2.z, r7.y, r2.z
    mul r2.z, r5.w, r2.z
    mul r2.z, r3.w, r2.z
    mad r8.xyz, r2.zzzz, cb3[22].xyzx, r8.xyzx
  endif 
endif 
mul r2.z, r7.x, r7.x
mul r2.w, r2.w, r2.w
mul r3.xyz, r8.xyzx, r2.wwww
mad r3.xyz, r2.zzzz, r9.xyzx, r3.xyzx
mad r3.xyz, r5.xyzx, r4.wwww, r3.xyzx
mad r1.x, v2.z, r1.x, cb3[43].w
mul r1.x, r1.x, cb3[44].w
max r1.x, r1.x, l(0.000000)
mad r4.xyz, cb3[47].xyzx, r1.xxxx, cb3[48].xyzx
add r2.z, -cb2[12].z, l(1.000000)
mad r5.xyz, cb3[45].xyzx, r1.xxxx, cb3[46].xyzx
mul r5.xyz, r5.xyzx, cb2[12].zzzz
mad r4.xyz, r4.xyzx, r2.zzzz, r5.xyzx
mul r2.yzw, r2.yyyy, r4.xxyz
mad r4.xyz, cb3[43].xyzx, r1.xxxx, cb3[44].xyzx
mov r5.x, cb3[46].w
mov r5.y, cb3[47].w
mov r5.z, cb3[48].w
dp3_sat r1.x, r5.xyzx, r1.yzwy
mad r1.xyz, cb3[49].xyzx, r1.xxxx, r4.xyzx
mad r1.xyz, r1.xyzx, r2.xxxx, r2.yzwy
mul r1.xyz, r7.xxxx, r1.xyzx
mad r0.xyz, r1.xyzx, r0.xyzx, r3.xyzx
mul o0.w, r0.w, cb2[11].x
if_nz cb5[7].x
  dp3 r0.w, r6.xyzx, r6.xyzx
  sqrt r1.x, r0.w
  add r1.y, r1.x, -cb3[50].x
  max r1.y, r1.y, l(0.000000)
  div r1.x, r1.y, r1.x
  mul r1.x, r1.x, r6.z
  mul r1.z, r1.x, cb3[52].z
  lt r1.x, l(0.010000), |r1.x|
  mul r1.w, r1.z, l(-1.442695)
  exp r1.w, r1.w
  add r1.w, -r1.w, l(1.000000)
  div r1.z, r1.w, r1.z
  movc r1.x, r1.x, r1.z, l(1.000000)
  mul r1.z, r1.y, cb3[51].w
  mul r1.x, r1.x, r1.z
  min r1.x, r1.x, l(1.000000)
  mul r1.x, r1.x, l(1.442695)
  exp r1.x, r1.x
  min r1.x, r1.x, l(1.000000)
  add r1.x, -r1.x, l(1.000000)
  mul r1.z, r1.x, cb3[52].y
  rsq r0.w, r0.w
  mul r2.xyz, r0.wwww, r6.xyzx
  dp3_sat r0.w, r2.xyzx, cb3[54].xyzx
  log r0.w, r0.w
  mul r0.w, r0.w, cb3[54].w
  exp r0.w, r0.w
  dp3_sat r1.w, r2.xyzx, cb3[53].xyzx
  log r1.w, r1.w
  mul r1.w, r1.w, cb3[53].w
  exp r1.w, r1.w
  mad r1.x, -r1.x, cb3[52].y, l(1.000000)
  mul r1.x, r1.x, cb3[51].y
  add r2.x, r1.y, -cb3[52].x
  max r2.x, r2.x, l(0.000000)
  mul r2.x, r2.x, cb3[51].x
  mul r2.x, r2.x, l(1.442695)
  exp r2.x, r2.x
  add r2.x, -r2.x, l(1.000000)
  mad_sat r1.z, r1.x, r2.x, r1.z
  mul r1.y, r1.y, -cb3[51].z
  mul r1.y, r1.y, l(1.442695)
  exp r1.y, r1.y
  add r1.y, -r1.y, l(1.000000)
  add r2.xyz, -cb3[56].xyzx, cb3[58].xyzx
  mad r2.xyz, r0.wwww, r2.xyzx, cb3[56].xyzx
  add r3.xyz, -r2.xyzx, cb3[55].xyzx
  mad r2.xyz, r1.wwww, r3.xyzx, r2.xyzx
  add r2.xyz, r2.xyzx, -cb3[57].xyzx
  mad r2.xyz, r1.yyyy, r2.xyzx, cb3[57].xyzx
  mov r3.x, cb3[55].w
  mov r3.y, cb3[56].w
  mov r3.z, cb3[57].w
  add r3.xyz, -r2.xyzx, r3.xyzx
  mad r1.xyw, r1.xxxx, r3.xyxz, r2.xyxz
  lt r0.w, l(0.000000), cb2[18].y
  if_nz r0.w
    mul r2.xy, v4.xyxx, cb2[14].zwzz
    sample r2.xyzw, r2.xyxx, t11.xyzw, s11
    add r0.w, r2.x, l(-1.000000)
    mad_sat r0.w, cb2[18].y, r0.w, l(1.000000)
  else 
    mov r0.w, l(1.000000)
  endif 
  mad r1.xyw, r1.xyxw, r0.wwww, -r0.xyxz
  mad r1.xyz, r1.zzzz, r1.xywx, r0.xyzx
else 
  dp3 r0.w, r6.xyzx, r6.xyzx
  sqrt r1.w, r0.w
  add r2.x, r1.w, -cb3[50].x
  max r2.x, r2.x, l(0.000000)
  div r1.w, r2.x, r1.w
  mul r1.w, r1.w, r6.z
  mul r2.y, r1.w, cb3[52].z
  lt r1.w, l(0.010000), |r1.w|
  mul r2.z, r2.y, l(-1.442695)
  exp r2.z, r2.z
  add r2.z, -r2.z, l(1.000000)
  div r2.y, r2.z, r2.y
  movc r1.w, r1.w, r2.y, l(1.000000)
  mul r2.y, r2.x, cb3[51].w
  mul r1.w, r1.w, r2.y
  min r1.w, r1.w, l(1.000000)
  mul r1.w, r1.w, l(1.442695)
  exp r1.w, r1.w
  min r1.w, r1.w, l(1.000000)
  add r1.w, -r1.w, l(1.000000)
  mul r2.y, r1.w, cb3[52].y
  rsq r0.w, r0.w
  mul r3.xyz, r0.wwww, r6.xyzx
  dp3_sat r0.w, r3.xyzx, cb3[54].xyzx
  log r0.w, r0.w
  mul r0.w, r0.w, cb3[54].w
  exp r0.w, r0.w
  dp3_sat r2.z, r3.xyzx, cb3[53].xyzx
  log r2.z, r2.z
  mul r2.z, r2.z, cb3[53].w
  exp r2.z, r2.z
  mad r1.w, -r1.w, cb3[52].y, l(1.000000)
  mul r1.w, r1.w, cb3[51].y
  add r2.w, r2.x, -cb3[52].x
  max r2.w, r2.w, l(0.000000)
  mul r2.w, r2.w, cb3[51].x
  mul r2.w, r2.w, l(1.442695)
  exp r2.w, r2.w
  add r2.w, -r2.w, l(1.000000)
  mad_sat r2.y, r1.w, r2.w, r2.y
  mul r2.x, r2.x, -cb3[51].z
  mul r2.x, r2.x, l(1.442695)
  exp r2.x, r2.x
  add r2.x, -r2.x, l(1.000000)
  add r3.xyz, -cb3[56].xyzx, cb3[58].xyzx
  mad r3.xyz, r0.wwww, r3.xyzx, cb3[56].xyzx
  add r4.xyz, -r3.xyzx, cb3[55].xyzx
  mad r3.xyz, r2.zzzz, r4.xyzx, r3.xyzx
  add r3.xyz, r3.xyzx, -cb3[57].xyzx
  mad r2.xzw, r2.xxxx, r3.xxyz, cb3[57].xxyz
  mov r3.x, cb3[55].w
  mov r3.y, cb3[56].w
  mov r3.z, cb3[57].w
  add r3.xyz, -r2.xzwx, r3.xyzx
  mad r2.xzw, r1.wwww, r3.xxyz, r2.xxzw
  add r2.xzw, -r0.xxyz, r2.xxzw
  mad r1.xyz, r2.yyyy, r2.xzwx, r0.xyzx
endif 
mul o0.xyz, r1.xyzx, cb2[13].zzzz
ret 
// Approximately 520 instruction slots used
