//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer edge_mark
// {
//
//   float4 EdgeMarkParams;             // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gbufferTexture1Global             texture  float4        2dMS             t8      1 
// gbufferTexture2Global             texture  float4        2dMS             t9      1 
// gbufferTextureDepthGlobal         texture   float        2dMS            t12      1 
// edge_mark                         cbuffer      NA          NA            cb8      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_resource_texture2dms(0) (float,float,float,float) t8
dcl_resource_texture2dms(0) (float,float,float,float) t9
dcl_resource_texture2dms(0) (float,float,float,float) t12
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_output o0.xyzw
dcl_temps 9
ftou r0.xy, v0.xyxx
mov r0.zw, l(0,0,0,0)
ldms r1.x, r0.xyww, t12.xyzw, l(0)
ldms r2.xyzw, r0.xyww, t8.xyzw, l(0)
mul r1.yzw, r2.wwww, l(0.000000, 0.998047, 7.984375, 63.875000)
frc r1.yzw, r1.yyzw
mad r1.yz, -r1.zzyz, l(0.000000, 0.125000, 0.125000, 0.000000), r1.yyzy
mad r1.yzw, r2.xxyz, l(0.000000, 256.000000, 256.000000, 256.000000), r1.yyzw
add r1.yzw, r1.yyzw, l(0.000000, -128.000000, -128.000000, -128.000000)
dp3 r2.x, r1.yzwy, r1.yzwy
rsq r2.x, r2.x
mul r1.yzw, r1.yyzw, r2.xxxx
ldms r0.x, r0.xyzw, t9.xyzw, l(0)
add r3.xyzw, v0.xyxy, l(1.000000, 0.000000, -1.000000, 0.000000)
ftou r3.xyzw, r3.zwxy
mov r4.xy, r3.zwzz
mov r4.zw, l(0,0,0,0)
ldms r0.y, r4.xyww, t12.yxzw, l(1)
mov r3.zw, l(0,0,0,0)
ldms r0.z, r3.xyww, t12.yzxw, l(1)
add r5.xyzw, v0.xyxy, l(0.000000, 1.000000, 0.000000, -1.000000)
ftou r5.xyzw, r5.zwxy
mov r6.xy, r5.zwzz
mov r6.zw, l(0,0,0,0)
ldms r0.w, r6.xyww, t12.yzwx, l(0)
mov r5.zw, l(0,0,0,0)
ldms r2.x, r5.xyww, t12.xyzw, l(0)
add r0.yz, -r0.yyzy, r1.xxxx
ne r2.y, |r0.y|, l(0.000000)
if_nz r2.y
  ldms r7.xyzw, r4.xyww, t8.xyzw, l(1)
  mul r8.xyz, r7.wwww, l(0.998047, 7.984375, 63.875000, 0.000000)
  frc r8.xyz, r8.xyzx
  mad r8.xy, -r8.yxyy, l(0.125000, 0.125000, 0.000000, 0.000000), r8.xyxx
  mad r7.xyz, r7.xyzx, l(256.000000, 256.000000, 256.000000, 0.000000), r8.xyzx
  add r7.xyz, r7.xyzx, l(-128.000000, -128.000000, -128.000000, 0.000000)
  dp3 r2.y, r7.xyzx, r7.xyzx
  rsq r2.y, r2.y
  mul r7.xyz, r2.yyyy, r7.xyzx
  ldms r2.y, r4.xyzw, t9.yxzw, l(1)
  lt r0.y, cb8[0].w, |r0.y|
  dp3 r2.z, r1.yzwy, r7.xyzx
  lt r2.z, r2.z, cb8[0].y
  or r4.x, r0.y, r2.z
  add r4.y, r2.w, -r7.w
  lt r4.y, cb8[0].z, |r4.y|
  add r2.y, r0.x, -r2.y
  lt r2.y, cb8[0].z, |r2.y|
  or r4.z, r4.x, r2.y
  movc r4.z, r4.y, r4.z, r4.x
  and r2.y, r2.y, r4.y
  and r2.y, r4.z, r2.y
  movc r2.y, r2.z, r4.x, r2.y
  movc r0.y, r0.y, r0.y, r2.y
else 
  mov r0.y, l(0)
endif 
ne r2.y, |r0.z|, l(0.000000)
if_nz r2.y
  ldms r4.xyzw, r3.xyww, t8.xyzw, l(1)
  mul r7.xyz, r4.wwww, l(0.998047, 7.984375, 63.875000, 0.000000)
  frc r7.xyz, r7.xyzx
  mad r7.xy, -r7.yxyy, l(0.125000, 0.125000, 0.000000, 0.000000), r7.xyxx
  mad r4.xyz, r4.xyzx, l(256.000000, 256.000000, 256.000000, 0.000000), r7.xyzx
  add r4.xyz, r4.xyzx, l(-128.000000, -128.000000, -128.000000, 0.000000)
  dp3 r2.y, r4.xyzx, r4.xyzx
  rsq r2.y, r2.y
  mul r4.xyz, r2.yyyy, r4.xyzx
  ldms r2.y, r3.xyzw, t9.yxzw, l(1)
  lt r0.z, cb8[0].w, |r0.z|
  dp3 r2.z, r1.yzwy, r4.xyzx
  lt r2.z, r2.z, cb8[0].y
  or r3.x, r0.z, r2.z
  add r3.y, r2.w, -r4.w
  lt r3.y, cb8[0].z, |r3.y|
  add r2.y, r0.x, -r2.y
  lt r2.y, cb8[0].z, |r2.y|
  or r3.z, r3.x, r2.y
  movc r3.z, r3.y, r3.z, r3.x
  and r2.y, r2.y, r3.y
  and r2.y, r3.z, r2.y
  movc r2.y, r2.z, r3.x, r2.y
  movc r0.z, r0.z, r0.z, r2.y
else 
  mov r0.z, l(0)
endif 
not r0.yz, r0.yyzy
and r0.y, r0.z, r0.y
add r0.z, -r0.w, r1.x
ne r0.w, |r0.z|, l(0.000000)
if_nz r0.w
  ldms r3.xyzw, r6.xyww, t8.xyzw, l(0)
  mul r4.xyz, r3.wwww, l(0.998047, 7.984375, 63.875000, 0.000000)
  frc r4.xyz, r4.xyzx
  mad r4.xy, -r4.yxyy, l(0.125000, 0.125000, 0.000000, 0.000000), r4.xyxx
  mad r3.xyz, r3.xyzx, l(256.000000, 256.000000, 256.000000, 0.000000), r4.xyzx
  add r3.xyz, r3.xyzx, l(-128.000000, -128.000000, -128.000000, 0.000000)
  dp3 r0.w, r3.xyzx, r3.xyzx
  rsq r0.w, r0.w
  mul r3.xyz, r0.wwww, r3.xyzx
  ldms r0.w, r6.xyzw, t9.yzwx, l(0)
  lt r0.z, cb8[0].w, |r0.z|
  dp3 r2.y, r1.yzwy, r3.xyzx
  lt r2.y, r2.y, cb8[0].y
  or r2.z, r0.z, r2.y
  add r3.x, r2.w, -r3.w
  lt r3.x, cb8[0].z, |r3.x|
  add r0.w, -r0.w, r0.x
  lt r0.w, cb8[0].z, |r0.w|
  or r3.y, r2.z, r0.w
  movc r3.y, r3.x, r3.y, r2.z
  and r0.w, r0.w, r3.x
  and r0.w, r3.y, r0.w
  movc r0.w, r2.y, r2.z, r0.w
  movc r0.z, r0.z, r0.z, r0.w
else 
  mov r0.z, l(0)
endif 
not r0.z, r0.z
and r0.y, r0.z, r0.y
add r0.z, r1.x, -r2.x
ne r0.w, |r0.z|, l(0.000000)
if_nz r0.w
  ldms r3.xyzw, r5.xyww, t8.xyzw, l(0)
  mul r2.xyz, r3.wwww, l(0.998047, 7.984375, 63.875000, 0.000000)
  frc r2.xyz, r2.xyzx
  mad r2.xy, -r2.yxyy, l(0.125000, 0.125000, 0.000000, 0.000000), r2.xyxx
  mad r2.xyz, r3.xyzx, l(256.000000, 256.000000, 256.000000, 0.000000), r2.xyzx
  add r2.xyz, r2.xyzx, l(-128.000000, -128.000000, -128.000000, 0.000000)
  dp3 r0.w, r2.xyzx, r2.xyzx
  rsq r0.w, r0.w
  mul r2.xyz, r0.wwww, r2.xyzx
  ldms r0.w, r5.xyzw, t9.yzwx, l(0)
  lt r0.z, cb8[0].w, |r0.z|
  dp3 r1.x, r1.yzwy, r2.xyzx
  lt r1.x, r1.x, cb8[0].y
  or r1.y, r0.z, r1.x
  add r1.z, r2.w, -r3.w
  lt r1.z, cb8[0].z, |r1.z|
  add r0.x, -r0.w, r0.x
  lt r0.x, cb8[0].z, |r0.x|
  or r0.w, r1.y, r0.x
  movc r0.w, r1.z, r0.w, r1.y
  and r0.x, r0.x, r1.z
  and r0.x, r0.w, r0.x
  movc r0.x, r1.x, r1.y, r0.x
  movc r0.x, r0.z, r0.z, r0.x
else 
  mov r0.x, l(0)
endif 
not r0.x, r0.x
and r0.x, r0.x, r0.y
discard_nz r0.x
mov o0.xyzw, l(1.000000,1.000000,1.000000,1.000000)
ret 
// Approximately 155 instruction slots used
