//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer puddle_locals
// {
//
//   float4 g_Puddle_ScaleXY_Range;     // Offset:    0 Size:    16
//   float4 g_PuddleParams;             // Offset:   16 Size:    16 [unused]
//   float4 g_GBufferTexture3Param;     // Offset:   32 Size:    16 [unused]
//
// }
//
// cbuffer ripple_locals
// {
//
//   float3 RippleData;                 // Offset:    0 Size:    12
//   float4 RippleScaleOffset;          // Offset:   16 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PuddleMaskSampler                 sampler      NA          NA             s5      1 
// PuddleMaskSampler                 texture  float4          2d             t5      1 
// ripple_locals                     cbuffer      NA          NA            cb9      1 
// puddle_locals                     cbuffer      NA          NA           cb10      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 2     z         1     NONE   float     z 
// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB10[1], immediateIndexed
dcl_constantbuffer CB9[2], immediateIndexed
dcl_sampler s5, mode_default
dcl_resource_texture2d (float,float,float,float) t5
dcl_input_ps linear v1.xy
dcl_input_ps linear v1.z
dcl_input_ps linear v2.xyzw
dcl_output o0.xyzw
dcl_temps 2
mad r0.xy, v2.xyxx, cb9[1].xyxx, cb9[1].zwzz
mul r0.xy, r0.xyxx, cb10[0].xxxx
sample r0.x, r0.xyxx, t5.xyzw, s5
lt r0.x, l(0.600000), r0.x
and r0.x, r0.x, l(0x3f800000)
mul r0.x, r0.x, v1.z
add r0.yz, v1.xxyx, -v2.xxyx
dp2 r0.w, r0.yzyy, r0.yzyy
sqrt r0.w, r0.w
mad r1.x, r0.w, v2.z, -v2.w
mul r1.y, |r1.x|, l(0.666667)
min r1.y, r1.y, l(1.000000)
mul r1.y, r1.y, r1.y
mad r1.y, -r1.y, r1.y, l(1.000000)
mul r0.x, r0.x, r1.y
lt r1.y, l(-1.000000), r1.x
lt r1.z, r1.x, l(1.500000)
max r1.x, r1.x, l(-1.000000)
min r1.x, r1.x, l(1.500000)
mul r1.x, r1.x, l(6.283185)
sincos null, r1.x, r1.x
div r0.w, r1.x, r0.w
mul r0.yz, r0.wwww, r0.yyzy
mad o0.xy, r0.yzyy, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
and r0.y, r1.y, r1.z
and r0.y, r0.y, l(0x3f800000)
mul r0.x, r0.x, r0.y
mul o0.w, r0.x, cb9[0].z
mov o0.z, l(0)
ret 
// Approximately 30 instruction slots used
