//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16 [unused]
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16 [unused]
//   float4 gCSMResolution;             // Offset:  224 Size:    16 [unused]
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
// cbuffer lighting_locals
// {
//
//   float4 deferredLightParams[14];    // Offset:    0 Size:   224 [unused]
//   float4 deferredLightVolumeParams[2];// Offset:  224 Size:    32 [unused]
//   float4 deferredLightScreenSize;    // Offset:  256 Size:    16 [unused]
//   float4 deferredProjectionParams;   // Offset:  272 Size:    16
//   float3 deferredPerspectiveShearParams0;// Offset:  288 Size:    12 [unused]
//   float3 deferredPerspectiveShearParams1;// Offset:  304 Size:    12 [unused]
//   float3 deferredPerspectiveShearParams2;// Offset:  320 Size:    12 [unused]
//
// }
//
// cbuffer deferred_volume_locals
// {
//
//   float4 deferredVolumePosition;     // Offset:    0 Size:    16
//   float4 deferredVolumeDirection;    // Offset:   16 Size:    16
//   float4 deferredVolumeTangentXAndShaftRadius;// Offset:   32 Size:    16
//   float4 deferredVolumeTangentYAndShaftLength;// Offset:   48 Size:    16 [unused]
//   float4 deferredVolumeColour;       // Offset:   64 Size:    16
//   float4 deferredVolumeShaftPlanes[3];// Offset:   80 Size:    48 [unused]
//   float4 deferredVolumeShaftGradient;// Offset:  128 Size:    16 [unused]
//   float4 deferredVolumeShaftGradientColourInv;// Offset:  144 Size:    16
//   row_major float4x4 deferredVolumeShaftCompositeMtx;// Offset:  160 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// deferredVolumeDepthBufferSamp     sampler      NA          NA             s5      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// deferredVolumeDepthBufferSamp     texture  float4          2d             t5      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// deferred_volume_locals            cbuffer      NA          NA           cb10      1 
// lighting_locals                   cbuffer      NA          NA           cb11      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 2   xyz         3     NONE   float       
// TEXCOORD                 3   xyz         4     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB1[16], immediateIndexed
dcl_constantbuffer CB6[9], immediateIndexed
dcl_constantbuffer CB11[18], immediateIndexed
dcl_constantbuffer CB10[10], immediateIndexed
dcl_sampler s5, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyzw
dcl_output o0.xyzw
dcl_temps 5
add r0.xyz, v1.xyzx, -cb1[15].xyzx
div r1.xy, v2.xyxx, v2.wwww
sample r1.xyzw, r1.xyxx, t5.xyzw, s5
add r0.w, cb11[17].w, l(1.000000)
add r0.w, -r1.x, r0.w
div r0.w, cb11[17].z, r0.w
div r0.w, r0.w, v2.w
add r1.xyz, cb1[15].xyzx, -cb10[0].xyzx
dp3 r1.w, r0.xyzx, r0.xyzx
dp3 r2.x, r1.xyzx, r0.xyzx
dp3 r2.y, r1.xyzx, r1.xyzx
dp3 r1.x, r1.xyzx, cb10[1].xyzx
dp3 r1.y, r0.xyzx, cb10[1].xyzx
mad r1.z, cb10[2].w, cb10[2].w, -r2.y
mad r2.y, r1.x, r1.x, r1.z
mul r2.z, r1.y, r1.y
mul r1.z, r1.z, r2.z
mad r1.z, r2.y, r1.w, -r1.z
mul r2.y, r1.x, r1.y
mad r2.y, -r2.y, l(2.000000), r2.x
mad r1.z, r2.x, r2.y, r1.z
mad r1.x, r1.y, r1.x, -r2.x
sqrt r2.x, r1.z
add r2.y, r1.x, -r2.x
mad r1.y, -r1.y, r1.y, r1.w
div_sat r2.y, r2.y, r1.y
min r2.y, r0.w, r2.y
add r1.x, r1.x, r2.x
div_sat r1.x, r1.x, r1.y
min r0.w, r0.w, r1.x
add_sat r0.w, -r2.y, r0.w
mul r2.xyz, r0.xyzx, r2.yyyy
mul r0.xyz, r0.wwww, r0.xyzx
mul r0.xyz, r0.xyzx, l(0.041667, 0.041667, 0.041667, 0.000000)
mul r3.xyz, r2.yyyy, cb6[1].xyzx
mad r2.xyw, r2.xxxx, cb6[0].xyxz, r3.xyxz
mad r2.xyz, r2.zzzz, cb6[2].xyzx, r2.xywx
mad r2.xyz, r2.xyzx, cb6[4].xyzx, cb6[8].xyzx
add r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.000000, 0.000000)
mul r3.xyz, r0.yyyy, cb6[1].xyzx
mad r3.xyz, r0.xxxx, cb6[0].xyzx, r3.xyzx
mad r0.xyz, r0.zzzz, cb6[2].xyzx, r3.xyzx
mul r3.xyz, r0.xyzx, cb6[4].xyzx
mul r0.x, r2.y, l(0.250000)
mul r3.w, r3.y, l(0.250000)
mov r4.xz, r2.xxzx
mov r4.y, r0.x
mov r0.yz, l(0,0,0,0)
loop 
  ige r1.x, r0.z, l(24)
  breakc_nz r1.x
  sample_c_lz r1.x, r4.xyxx, t15.xxxx, s15, r4.z
  add r0.y, r0.y, r1.x
  add r4.xyz, r3.xwzx, r4.xyzx
  iadd r0.z, r0.z, l(1)
endloop 
mul r0.x, r0.w, r0.y
mul r0.x, r0.x, l(0.041667)
sqrt r0.y, r1.w
lt r0.z, l(0.000000), r1.z
and r0.z, r0.z, l(0x3f800000)
mul r0.y, r0.z, r0.y
mul r0.x, r0.y, r0.x
mul r0.y, r0.x, v2.z
mad r0.x, r0.x, v2.z, l(-1.000000)
mad r0.x, cb10[9].w, r0.x, l(1.000000)
mul r0.x, r0.x, r0.y
mul o0.xyz, r0.xxxx, cb10[4].xyzx
mov o0.w, l(0)
ret 
// Approximately 70 instruction slots used
