//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16
//   float4 gDirectionalColour;         // Offset:   16 Size:    16
//   int gNumForwardLights;             // Offset:   32 Size:     4 [unused]
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128 [unused]
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128 [unused]
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128 [unused]
//   float gLightConeScale[8];          // Offset:  432 Size:   116 [unused]
//   float gLightConeOffset[8];         // Offset:  560 Size:   116 [unused]
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80 [unused]
//   float4 globalFogColor;             // Offset:  880 Size:    16 [unused]
//   float4 globalFogColorE;            // Offset:  896 Size:    16 [unused]
//   float4 globalFogColorN;            // Offset:  912 Size:    16 [unused]
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16 [unused]
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer megashader_locals
// {
//
//   float emissiveMultiplier;          // Offset:    0 Size:     4
//   float useTessellation;             // Offset:    4 Size:     4 [unused]
//   float HardAlphaBlend;              // Offset:    8 Size:     4 [unused]
//   float4 matMaterialColorScale;      // Offset:   16 Size:    16 [unused]
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16
//   float4 gCSMResolution;             // Offset:  224 Size:    16
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// megashader_locals                 cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 6   xyzw        3     NONE   float   xyz 
// SV_Position              0   xyzw        4      POS   float       
// SV_ClipDistance          0   xyzw        5  CLIPDST   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB1[16], immediateIndexed
dcl_constantbuffer CB2[14], immediateIndexed
dcl_constantbuffer CB3[50], immediateIndexed
dcl_constantbuffer CB12[1], immediateIndexed
dcl_constantbuffer CB6[15], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.xy
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_output o0.xyzw
dcl_temps 7
dcl_indexableTemp x0[4], 4
add r0.xyz, v3.xyzx, -cb1[15].xyzx
mul r1.xyz, r0.yyyy, cb6[1].xyzx
mad r0.xyw, r0.xxxx, cb6[0].xyxz, r1.xyxz
mad r0.xyz, r0.zzzz, cb6[2].xyzx, r0.xywx
mad r1.xyz, r0.xyzx, cb6[4].xyzx, cb6[8].xyzx
mov x0[0].xyz, r1.xyzx
max r0.w, |r1.y|, |r1.x|
mad r1.xyz, r0.xyzx, cb6[5].xyzx, cb6[9].xyzx
mov x0[1].xyz, r1.xyzx
max r1.x, |r1.y|, |r1.x|
mad r1.yzw, r0.xxyz, cb6[6].xxyz, cb6[10].xxyz
mad r0.xyz, r0.xyzx, cb6[7].xyzx, cb6[11].xyzx
mov x0[2].xyz, r1.yzwy
max r1.y, |r1.z|, |r1.y|
mov x0[3].xyz, r0.xyzx
max r0.x, |r0.y|, |r0.x|
mad_sat r0.x, r0.x, l(15.000000), l(-6.300000)
mul r2.yw, cb6[14].zzzw, l(0.000000, -0.346097, 0.000000, 0.328490)
mad r0.y, -cb6[14].z, l(1.500000), l(1.000000)
mul r0.y, r0.y, l(0.500000)
lt r0.z, r1.y, r0.y
movc r0.z, r0.z, l(2), l(3)
lt r1.x, r1.x, r0.y
lt r0.y, r0.w, r0.y
movc r0.z, r1.x, l(1), r0.z
movc r0.y, r0.y, l(0), r0.z
mov r1.xyz, x0[r0.y + 0].xyzx
itof r0.y, r0.y
eq r3.xyzw, l(0.000000, 1.000000, 2.000000, 3.000000), r0.yyyy
add r0.y, r0.y, l(0.500000)
mul r0.y, r0.y, l(0.250000)
mad r4.y, r1.y, l(0.250000), r0.y
and r3.xyzw, r3.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
dp4 r0.y, r3.xyzw, cb6[12].xyzw
dp4 r0.z, r3.xyzw, cb6[13].xyzw
ne r0.w, r0.y, l(0.000000)
add r0.y, -r0.y, r1.z
deriv_rtx r3.z, r0.y
deriv_rty r5.w, r0.y
add r4.x, r1.x, l(0.500000)
deriv_rtx r3.xyw, r4.xyxy
deriv_rty r5.xyz, r4.yxyy
mul r1.xy, r5.ywyy, r3.ywyy
mad r6.xy, r3.xzxx, r5.xzxx, -r1.xyxx
mul r1.x, r3.z, r5.y
mad r6.z, r3.x, r5.w, -r1.x
div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r6.x
mul r1.xy, r1.xxxx, r6.yzyy
max r1.xy, r1.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mad r0.y, -r0.z, r1.x, r0.y
mad r0.y, -r0.z, r1.y, r0.y
movc r2.z, r0.w, r0.y, r1.z
mov r4.z, l(0)
add r0.yzw, r2.yywz, r4.xxyz
sample_c_lz r1.x, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(-0.799291, 0.201741, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r1.y, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(-0.031176, 0.179338, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r1.z, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(0.514749, 0.253502, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r1.w, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(-0.072870, 0.008097, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r3.x, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(-0.969781, 0.034522, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r3.y, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(0.545547, 0.024129, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r3.z, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(-0.028906, -0.136785, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r3.w, r0.yzyy, t15.xxxx, s15, r0.w
add r1.xyzw, r1.xyzw, r3.xyzw
mul r2.xy, cb6[14].zwzz, l(-0.479511, -0.244833, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r3.x, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(0.758788, -0.112109, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r3.y, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(0.339353, -0.249328, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r3.z, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(1.070598, 0.208123, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r3.w, r0.yzyy, t15.xxxx, s15, r0.w
add r1.xyzw, r1.xyzw, r3.xyzw
mov r3.z, r2.z
mov r5.z, r3.z
mov r6.z, r5.z
mul r6.xy, cb6[14].zwzz, l(-1.343153, -0.088584, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r6.xxyz
sample_c_lz r6.w, r0.yzyy, t15.xxxx, s15, r0.w
mul r2.xy, cb6[14].zwzz, l(1.294038, -0.018078, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r2.xxyz
sample_c_lz r6.x, r0.yzyy, t15.xxxx, s15, r0.w
mul r3.xy, cb6[14].zwzz, l(-0.747563, -0.113974, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r3.xxyz
sample_c_lz r6.y, r0.yzyy, t15.xxxx, s15, r0.w
mul r5.xy, cb6[14].zwzz, l(0.947722, -0.248764, 0.000000, 0.000000)
add r0.yzw, r4.xxyz, r5.xxyz
sample_c_lz r6.z, r0.yzyy, t15.xxxx, s15, r0.w
add r1.xyzw, r1.xyzw, r6.xyzw
dp4 r0.y, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
add r1.xyz, -v3.xyzx, cb1[15].xyzx
dp3 r0.z, r1.xyzx, cb1[14].xyzx
mad_sat r0.z, r0.z, cb6[0].w, cb6[1].w
add r0.z, -r0.z, l(1.000000)
mul r0.x, r0.x, r0.z
mad r0.x, r0.y, l(0.062500), r0.x
mul r0.x, r0.x, r0.x
min r0.x, r0.x, l(1.000000)
mad_sat r0.y, v3.z, cb6[3].x, cb6[3].y
sqrt r0.y, r0.y
mul r0.y, r0.y, cb6[3].z
mad r0.x, r0.y, -r0.x, r0.x
add r0.y, -cb2[12].z, l(1.000000)
dp3 r0.z, v2.xyzx, v2.xyzx
rsq r0.z, r0.z
mad r0.w, v2.z, r0.z, cb3[43].w
mul r1.xyz, r0.zzzz, v2.xyzx
mul r0.z, r0.w, cb3[44].w
max r0.z, r0.z, l(0.000000)
mad r2.xyz, cb3[45].xyzx, r0.zzzz, cb3[46].xyzx
mul r2.xyz, r2.xyzx, cb2[12].zzzz
mad r3.xyz, cb3[47].xyzx, r0.zzzz, cb3[48].xyzx
mad r4.xyz, cb3[43].xyzx, r0.zzzz, cb3[44].xyzx
mad r0.yzw, r3.xxyz, r0.yyyy, r2.xxyz
mul r2.xy, v0.xyxx, cb2[11].zyzz
mul r2.xy, r2.xyxx, r2.xyxx
mul r0.yzw, r0.yyzw, r2.yyyy
mov r3.x, cb3[46].w
mov r3.y, cb3[47].w
mov r3.z, cb3[48].w
dp3_sat r1.w, r3.xyzx, r1.xyzx
dp3_sat r1.x, r1.xyzx, -cb3[0].xyzx
mad r1.yzw, cb3[49].xxyz, r1.wwww, r4.xxyz
mad r0.yzw, r1.yyzw, r2.xxxx, r0.yyzw
sample r2.xyzw, v1.xyxx, t0.xyzw, s0
mul r1.yzw, r2.wwww, r2.xxyz
mul r1.yzw, r1.yyzw, r1.yyzw
mul r0.yzw, r0.yyzw, r1.yyzw
mul r2.xyz, r1.xxxx, r1.yzwy
mul r2.xyz, r2.xyzx, cb3[1].xyzx
mad r0.xyz, r2.xyzx, r0.xxxx, r0.yzwy
mul r0.w, r2.w, cb12[0].x
mul r1.x, r2.w, v0.w
mul o0.w, r1.x, cb2[11].x
mul r0.w, r0.w, cb2[11].w
mul r0.w, r0.w, v0.z
mad r0.xyz, r1.yzwy, r0.wwww, r0.xyzx
mul o0.xyz, r0.xyzx, cb2[13].zzzz
ret 
// Approximately 157 instruction slots used
