//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16
//   float4 globalScreenSize;           // Offset:  224 Size:    16
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16
//   float4 gDirectionalColour;         // Offset:   16 Size:    16
//   int gNumForwardLights;             // Offset:   32 Size:     4
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128
//   float gLightConeScale[8];          // Offset:  432 Size:   116
//   float gLightConeOffset[8];         // Offset:  560 Size:   116
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80
//   float4 globalFogColor;             // Offset:  880 Size:    16
//   float4 globalFogColorE;            // Offset:  896 Size:    16
//   float4 globalFogColorN;            // Offset:  912 Size:    16
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer more_stuff
// {
//
//   float4 gEntitySelectColor[2];      // Offset:    0 Size:    32 [unused]
//   float4 gAmbientOcclusionEffect;    // Offset:   32 Size:    16 [unused]
//   float4 gDynamicBakesAndWetness;    // Offset:   48 Size:    16 [unused]
//   float4 gAlphaRefVec0;              // Offset:   64 Size:    16
//   float4 gAlphaRefVec1;              // Offset:   80 Size:    16 [unused]
//   float gAlphaTestRef;               // Offset:   96 Size:     4 [unused]
//   bool gTreesUseDiscard;             // Offset:  100 Size:     4 [unused]
//   float gReflectionMipCount;         // Offset:  104 Size:     4 [unused]
//   bool gUseTransparencyAA;           // Offset:  108 Size:     4 [unused]
//   bool gUseFogRay;                   // Offset:  112 Size:     4
//
// }
//
// cbuffer megashader_locals
// {
//
//   float specularFresnel;             // Offset:    0 Size:     4
//   float specularFalloffMult;         // Offset:    4 Size:     4
//   float specularIntensityMult;       // Offset:    8 Size:     4
//   float3 specMapIntMask;             // Offset:   16 Size:    12
//   float bumpiness;                   // Offset:   28 Size:     4
//   float reflectivePower;             // Offset:   32 Size:     4
//   float3 displParams;                // Offset:   36 Size:    12
//   float useTessellation;             // Offset:   48 Size:     4 [unused]
//   float HardAlphaBlend;              // Offset:   52 Size:     4 [unused]
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16
//   float4 gCSMResolution;             // Offset:  224 Size:    16
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// ReflectionSampler                 sampler      NA          NA             s1      1 
// BumpSampler                       sampler      NA          NA             s2      1 
// SpecSampler                       sampler      NA          NA             s3      1 
// EnvironmentSampler                sampler      NA          NA             s4      1 
// FogRaySampler                     sampler      NA          NA            s11      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// ReflectionSampler                 texture  float4          2d             t1      1 
// BumpSampler                       texture  float4          2d             t2      1 
// SpecSampler                       texture  float4          2d             t3      1 
// EnvironmentSampler                texture  float4          2d             t4      1 
// FogRaySampler                     texture  float4          2d            t11      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// more_stuff                        cbuffer      NA          NA            cb5      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// megashader_locals                 cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xy w
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 3   xyz         3     NONE   float   xyz 
// TEXCOORD                 4   xyz         4     NONE   float   xyz 
// TEXCOORD                 5   xyz         5     NONE   float   xyz 
// TEXCOORD                 6   xyzw        6     NONE   float   xyz 
// SV_Position              0   xyzw        7      POS   float   xy  
// SV_ClipDistance          0   xyzw        8  CLIPDST   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB1[16], immediateIndexed
dcl_constantbuffer CB2[19], immediateIndexed
dcl_constantbuffer CB3[59], immediateIndexed
dcl_constantbuffer CB5[8], immediateIndexed
dcl_constantbuffer CB12[3], immediateIndexed
dcl_constantbuffer CB6[15], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s11, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v0.xyw
dcl_input_ps linear v1.xy
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyz
dcl_input_ps_siv linear noperspective v7.xy, position
dcl_output o0.xyzw
dcl_temps 27
dcl_indexableTemp x0[4], 4
sample r0.xyzw, v1.xyxx, t0.xyzw, s0
mul r0.z, r0.w, cb2[11].x
ge r0.z, cb5[4].x, r0.z
discard_nz r0.z
sample r1.xyzw, v1.xyxx, t2.xyzw, s2
mad r0.zw, r1.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
dp2 r1.x, r0.zwzz, r0.zwzz
add r1.x, -r1.x, l(1.000000)
sqrt r1.x, |r1.x|
max r1.y, cb12[1].w, l(0.001000)
mul r0.zw, r0.zzzw, r1.yyyy
mul r1.yzw, r0.wwww, v5.xxyz
mad r1.yzw, r0.zzzz, v4.xxyz, r1.yyzw
mad r1.xyz, r1.xxxx, v2.xyzx, r1.yzwy
dp3 r0.z, r1.xyzx, r1.xyzx
rsq r0.z, r0.z
mul r1.xyw, r0.zzzz, r1.xyxz
sample r2.xyzw, v1.xyxx, t3.xyzw, s3
mul r2.xy, r2.xyxx, r2.xyxx
dp3 r0.w, r2.xyzx, cb12[1].xyzx
mul_sat r0.w, r0.w, cb12[0].z
dp3 r2.x, v3.xyzx, v3.xyzx
rsq r2.y, r2.x
mul r3.xyz, r2.yyyy, v3.xyzx
dp3 r2.y, -r3.xyzx, r1.xywx
add r2.y, r2.y, r2.y
mad r3.xyz, r1.xywx, -r2.yyyy, -r3.xyzx
dp3 r2.y, r3.xyzx, r3.xyzx
rsq r2.y, r2.y
mad r2.yz, r3.xxzx, r2.yyyy, l(0.000000, 1.000000, 1.000000, 0.000000)
mul r2.yz, r2.yyzy, l(0.000000, -0.500000, -0.500000, 0.000000)
sample r3.xyzw, r2.yzyy, t4.xyzw, s4
mul r3.xyz, r3.xyzx, cb12[2].xxxx
mul r4.xyz, v0.xywx, cb2[11].zyxz
add r5.xyz, -v6.xyzx, cb1[15].xyzx
dp3 r2.y, r5.xyzx, r5.xyzx
rsq r2.y, r2.y
mul r6.xyz, r2.yyyy, r5.xyzx
mad r7.xyz, r5.xyzx, r2.yyyy, -cb3[0].xyzx
dp3 r2.z, r7.xyzx, r7.xyzx
rsq r2.z, r2.z
mul r7.xyz, r2.zzzz, r7.xyzx
mul r4.xy, r4.xyxx, r4.xyxx
mad r2.z, r2.w, cb12[0].y, l(-500.000000)
max r2.z, r2.z, l(0.000000)
mad r2.w, r2.w, cb12[0].y, -r2.z
mul r2.z, r2.z, l(558.000000)
mad r2.z, r2.w, l(3.000000), r2.z
dp3 r2.w, r5.xyzx, cb1[14].xyzx
add r8.xyz, v6.xyzx, -cb1[15].xyzx
mul r9.xyz, r8.yyyy, cb6[1].xyzx
mad r9.xyz, r8.xxxx, cb6[0].xyzx, r9.xyzx
mad r9.xyz, r8.zzzz, cb6[2].xyzx, r9.xyzx
mad r10.xyz, r9.xyzx, cb6[4].xyzx, cb6[8].xyzx
mov x0[0].xyz, r10.xyzx
mad r11.xyz, r9.xyzx, cb6[5].xyzx, cb6[9].xyzx
mov x0[1].xyz, r11.xyzx
mad r12.xyz, r9.xyzx, cb6[6].xyzx, cb6[10].xyzx
mov x0[2].xyz, r12.xyzx
mad r9.xyz, r9.xyzx, cb6[7].xyzx, cb6[11].xyzx
mov x0[3].xyz, r9.xyzx
mul r13.yw, cb6[14].zzzw, l(0.000000, -0.346097, 0.000000, 0.328490)
mad r3.w, -cb6[14].z, l(1.500000), l(1.000000)
mul r3.w, r3.w, l(0.500000)
max r4.w, |r12.y|, |r12.x|
lt r4.w, r4.w, r3.w
movc r4.w, r4.w, l(2), l(3)
max r5.w, |r11.y|, |r11.x|
lt r5.w, r5.w, r3.w
movc r4.w, r5.w, l(1), r4.w
max r5.w, |r10.y|, |r10.x|
lt r3.w, r5.w, r3.w
movc r3.w, r3.w, l(0), r4.w
mov r10.xyz, x0[r3.w + 0].xyzx
itof r3.w, r3.w
add r4.w, r3.w, l(0.500000)
mul r4.w, r4.w, l(0.250000)
eq r11.xyzw, l(0.000000, 1.000000, 2.000000, 3.000000), r3.wwww
and r11.xyzw, r11.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
dp4 r3.w, r11.xyzw, cb6[12].xyzw
dp4 r5.w, r11.xyzw, cb6[13].xyzw
add r11.x, r10.x, l(0.500000)
mad r11.y, r10.y, l(0.250000), r4.w
ne r4.w, r3.w, l(0.000000)
add r3.w, -r3.w, r10.z
deriv_rtx r12.xyw, r11.xyxy
deriv_rtx r12.z, r3.w
deriv_rty r14.xyz, r11.yxyy
deriv_rty r14.w, r3.w
mul r9.zw, r12.yyyw, r14.yyyw
mad r15.xy, r12.xzxx, r14.xzxx, -r9.zwzz
div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r15.x
mul r7.w, r12.z, r14.y
mad r15.z, r12.x, r14.w, -r7.w
mul r9.zw, r6.wwww, r15.yyyz
max r9.zw, r9.zzzw, l(0.000000, 0.000000, 0.000000, 0.000000)
min r9.zw, r9.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
mad r3.w, -r5.w, r9.z, r3.w
mad r3.w, -r5.w, r9.w, r3.w
movc r13.z, r4.w, r3.w, r10.z
mov r11.z, l(0)
add r10.xyz, r11.xyzx, r13.ywzy
mul r13.xy, cb6[14].zwzz, l(-0.799291, 0.201741, 0.000000, 0.000000)
add r12.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(-0.031176, 0.179338, 0.000000, 0.000000)
add r14.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(0.514749, 0.253502, 0.000000, 0.000000)
add r15.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(-0.072870, 0.008097, 0.000000, 0.000000)
add r16.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(-0.969781, 0.034522, 0.000000, 0.000000)
add r17.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(0.545547, 0.024129, 0.000000, 0.000000)
add r18.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(-0.028906, -0.136785, 0.000000, 0.000000)
add r19.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(-0.479511, -0.244833, 0.000000, 0.000000)
add r20.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(0.758788, -0.112109, 0.000000, 0.000000)
add r21.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(0.339353, -0.249328, 0.000000, 0.000000)
add r22.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(1.070598, 0.208123, 0.000000, 0.000000)
add r23.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(1.294038, -0.018078, 0.000000, 0.000000)
add r24.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(-0.747563, -0.113974, 0.000000, 0.000000)
add r25.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(0.947722, -0.248764, 0.000000, 0.000000)
add r26.xyz, r11.xyzx, r13.xyzx
mul r13.xy, cb6[14].zwzz, l(-1.343153, -0.088584, 0.000000, 0.000000)
add r11.xyz, r11.xyzx, r13.xyzx
sample_c_lz r10.x, r10.xyxx, t15.xxxx, s15, r10.z
sample_c_lz r10.y, r12.xyxx, t15.xxxx, s15, r12.z
sample_c_lz r10.z, r14.xyxx, t15.xxxx, s15, r14.z
sample_c_lz r10.w, r15.xyxx, t15.xxxx, s15, r15.z
sample_c_lz r12.x, r16.xyxx, t15.xxxx, s15, r16.z
sample_c_lz r12.y, r17.xyxx, t15.xxxx, s15, r17.z
sample_c_lz r12.z, r18.xyxx, t15.xxxx, s15, r18.z
sample_c_lz r12.w, r19.xyxx, t15.xxxx, s15, r19.z
sample_c_lz r13.x, r20.xyxx, t15.xxxx, s15, r20.z
sample_c_lz r13.y, r21.xyxx, t15.xxxx, s15, r21.z
sample_c_lz r13.z, r22.xyxx, t15.xxxx, s15, r22.z
sample_c_lz r13.w, r23.xyxx, t15.xxxx, s15, r23.z
sample_c_lz r14.x, r24.xyxx, t15.xxxx, s15, r24.z
sample_c_lz r14.y, r25.xyxx, t15.xxxx, s15, r25.z
sample_c_lz r14.z, r26.xyxx, t15.xxxx, s15, r26.z
sample_c_lz r14.w, r11.xyxx, t15.xxxx, s15, r11.z
add r10.xyzw, r10.xyzw, r12.xyzw
add r10.xyzw, r13.xyzw, r10.xyzw
add r10.xyzw, r14.xyzw, r10.xyzw
dp4 r3.w, r10.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mad_sat r2.w, r2.w, cb6[0].w, cb6[1].w
max r4.w, |r9.y|, |r9.x|
mad_sat r4.w, r4.w, l(15.000000), l(-6.300000)
add r2.w, -r2.w, l(1.000000)
mul r2.w, r4.w, r2.w
mad r2.w, r3.w, l(0.062500), r2.w
mul r2.w, r2.w, r2.w
min r2.w, r2.w, l(1.000000)
mad_sat r3.w, v6.z, cb6[3].x, cb6[3].y
sqrt r3.w, r3.w
mul r3.w, r3.w, cb6[3].z
mad r2.w, r3.w, -r2.w, r2.w
dp3_sat r3.w, r1.xywx, -cb3[0].xyzx
dp3_sat r9.x, r6.xyzx, r1.xywx
dp3_sat r9.y, r7.xyzx, -cb3[0].xyzx
add r9.xy, -r9.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r9.zw, r9.xxxy, r9.xxxy
mul r9.zw, r9.zzzw, r9.zzzw
mul r9.xy, r9.xyxx, r9.zwzz
add r4.w, -cb12[0].x, l(1.000000)
mad r9.xy, cb12[0].xxxx, r9.xyxx, r4.wwww
add r9.zw, r2.zzzz, l(0.000000, 0.000000, 2.000000, 0.000000)
mul r5.w, r9.z, l(0.125000)
mad r6.w, -r0.w, r9.x, l(1.000000)
dp3 r7.x, r1.xywx, r7.xyzx
add_sat r7.x, r7.x, l(0.000000)
log r7.x, r7.x
mul r7.x, r7.x, r9.w
exp r7.x, r7.x
mul r7.x, r9.y, r7.x
mul r7.x, r5.w, r7.x
mul r7.x, r0.w, r7.x
mul r7.x, r3.w, r7.x
mad r3.w, r3.w, r6.w, r7.x
mul r7.xyz, r3.wwww, cb3[1].xyzx
ige r3.w, l(0), cb3[2].x
if_z r3.w
  eq r7.w, cb3[19].w, l(0.000000)
  add r9.xyz, -v6.xyzx, cb3[3].xyzx
  add r10.xyz, v6.xyzx, -cb3[3].xyzx
  dp3 r8.w, r10.xyzx, cb3[11].xyzx
  div_sat r8.w, r8.w, cb3[19].w
  mul r8.w, r8.w, cb3[19].w
  mad r10.xyz, cb3[11].xyzx, r8.wwww, cb3[3].xyzx
  add r10.xyz, r10.xyzx, -v6.xyzx
  movc r9.xyz, r7.wwww, r9.xyzx, r10.xyzx
  dp3 r7.w, r9.xyzx, r9.xyzx
  add r9.xyz, r9.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
  dp3 r8.w, r9.xyzx, r9.xyzx
  rsq r8.w, r8.w
  mul r9.xyz, r8.wwww, r9.xyzx
  mad_sat r7.w, -r7.w, cb3[3].w, l(1.000000)
  add r8.w, -cb3[11].w, l(1.000000)
  mad r8.w, r8.w, r7.w, cb3[11].w
  div r7.w, r7.w, r8.w
  dp3 r8.w, r9.xyzx, -cb3[11].xyzx
  mad_sat r8.w, r8.w, cb3[27].x, cb3[35].x
  dp3_sat r10.x, r9.xyzx, r1.xywx
  mul r8.w, r8.w, r10.x
  mul r10.x, r7.w, r8.w
  mul r10.xyz, r10.xxxx, cb3[19].xyzx
  mad r9.xyz, r5.xyzx, r2.yyyy, r9.xyzx
  dp3 r10.w, r9.xyzx, r9.xyzx
  rsq r10.w, r10.w
  mul r9.xyz, r9.xyzx, r10.wwww
  dp3_sat r10.w, r9.xyzx, r6.xyzx
  add r10.w, -r10.w, l(1.000000)
  mul r11.x, r10.w, r10.w
  mul r11.x, r11.x, r11.x
  mul r10.w, r10.w, r11.x
  mad r10.w, cb12[0].x, r10.w, r4.w
  dp3_sat r9.x, r9.xyzx, r1.xywx
  log r9.x, r9.x
  mul r9.x, r9.x, r9.w
  exp r9.x, r9.x
  mul r9.x, r9.x, r10.w
  mul r8.w, r8.w, r9.x
  mul r7.w, r7.w, r8.w
  mul r7.w, r5.w, r7.w
  mul r9.xyz, r7.wwww, cb3[19].xyzx
else 
  mov r10.xyz, l(0,0,0,0)
  mov r9.xyz, l(0,0,0,0)
endif 
ilt r7.w, l(0), cb3[2].x
if_nz r7.w
  ige r8.w, l(1), cb3[2].x
  or r7.w, r3.w, r7.w
  movc r3.w, r8.w, r7.w, r3.w
  if_z r3.w
    eq r7.w, cb3[20].w, l(0.000000)
    add r11.xyz, -v6.xyzx, cb3[4].xyzx
    add r12.xyz, v6.xyzx, -cb3[4].xyzx
    dp3 r8.w, r12.xyzx, cb3[12].xyzx
    div_sat r8.w, r8.w, cb3[20].w
    mul r8.w, r8.w, cb3[20].w
    mad r12.xyz, cb3[12].xyzx, r8.wwww, cb3[4].xyzx
    add r12.xyz, r12.xyzx, -v6.xyzx
    movc r11.xyz, r7.wwww, r11.xyzx, r12.xyzx
    dp3 r7.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    mad_sat r7.w, -r7.w, cb3[4].w, l(1.000000)
    add r8.w, -cb3[12].w, l(1.000000)
    mad r8.w, r8.w, r7.w, cb3[12].w
    div r7.w, r7.w, r8.w
    dp3 r8.w, r11.xyzx, -cb3[12].xyzx
    mad_sat r8.w, r8.w, cb3[28].x, cb3[36].x
    dp3_sat r10.w, r11.xyzx, r1.xywx
    mul r8.w, r8.w, r10.w
    mul r10.w, r7.w, r8.w
    mad r10.xyz, r10.wwww, cb3[20].xyzx, r10.xyzx
    mad r11.xyz, r5.xyzx, r2.yyyy, r11.xyzx
    dp3 r10.w, r11.xyzx, r11.xyzx
    rsq r10.w, r10.w
    mul r11.xyz, r10.wwww, r11.xyzx
    dp3_sat r10.w, r11.xyzx, r6.xyzx
    add r10.w, -r10.w, l(1.000000)
    mul r11.w, r10.w, r10.w
    mul r11.w, r11.w, r11.w
    mul r10.w, r10.w, r11.w
    mad r10.w, cb12[0].x, r10.w, r4.w
    dp3_sat r11.x, r11.xyzx, r1.xywx
    log r11.x, r11.x
    mul r11.x, r9.w, r11.x
    exp r11.x, r11.x
    mul r10.w, r10.w, r11.x
    mul r8.w, r8.w, r10.w
    mul r7.w, r7.w, r8.w
    mul r7.w, r5.w, r7.w
    mad r9.xyz, r7.wwww, cb3[20].xyzx, r9.xyzx
  endif 
else 
  mov r3.w, l(-1)
endif 
if_z r3.w
  ige r7.w, l(2), cb3[2].x
  or r3.w, r3.w, r7.w
  if_z r3.w
    eq r7.w, cb3[21].w, l(0.000000)
    add r11.xyz, -v6.xyzx, cb3[5].xyzx
    add r12.xyz, v6.xyzx, -cb3[5].xyzx
    dp3 r8.w, r12.xyzx, cb3[13].xyzx
    div_sat r8.w, r8.w, cb3[21].w
    mul r8.w, r8.w, cb3[21].w
    mad r12.xyz, cb3[13].xyzx, r8.wwww, cb3[5].xyzx
    add r12.xyz, r12.xyzx, -v6.xyzx
    movc r11.xyz, r7.wwww, r11.xyzx, r12.xyzx
    dp3 r7.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    mad_sat r7.w, -r7.w, cb3[5].w, l(1.000000)
    add r8.w, -cb3[13].w, l(1.000000)
    mad r8.w, r8.w, r7.w, cb3[13].w
    div r7.w, r7.w, r8.w
    dp3 r8.w, r11.xyzx, -cb3[13].xyzx
    mad_sat r8.w, r8.w, cb3[29].x, cb3[37].x
    dp3_sat r10.w, r11.xyzx, r1.xywx
    mul r8.w, r8.w, r10.w
    mul r10.w, r7.w, r8.w
    mad r10.xyz, r10.wwww, cb3[21].xyzx, r10.xyzx
    mad r11.xyz, r5.xyzx, r2.yyyy, r11.xyzx
    dp3 r10.w, r11.xyzx, r11.xyzx
    rsq r10.w, r10.w
    mul r11.xyz, r10.wwww, r11.xyzx
    dp3_sat r10.w, r11.xyzx, r6.xyzx
    add r10.w, -r10.w, l(1.000000)
    mul r11.w, r10.w, r10.w
    mul r11.w, r11.w, r11.w
    mul r10.w, r10.w, r11.w
    mad r10.w, cb12[0].x, r10.w, r4.w
    dp3_sat r11.x, r11.xyzx, r1.xywx
    log r11.x, r11.x
    mul r11.x, r9.w, r11.x
    exp r11.x, r11.x
    mul r10.w, r10.w, r11.x
    mul r8.w, r8.w, r10.w
    mul r7.w, r7.w, r8.w
    mul r7.w, r5.w, r7.w
    mad r9.xyz, r7.wwww, cb3[21].xyzx, r9.xyzx
  endif 
else 
  mov r3.w, l(-1)
endif 
if_z r3.w
  ige r7.w, l(3), cb3[2].x
  or r3.w, r3.w, r7.w
  if_z r3.w
    eq r7.w, cb3[22].w, l(0.000000)
    add r11.xyz, -v6.xyzx, cb3[6].xyzx
    add r12.xyz, v6.xyzx, -cb3[6].xyzx
    dp3 r8.w, r12.xyzx, cb3[14].xyzx
    div_sat r8.w, r8.w, cb3[22].w
    mul r8.w, r8.w, cb3[22].w
    mad r12.xyz, cb3[14].xyzx, r8.wwww, cb3[6].xyzx
    add r12.xyz, r12.xyzx, -v6.xyzx
    movc r11.xyz, r7.wwww, r11.xyzx, r12.xyzx
    dp3 r7.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    mad_sat r7.w, -r7.w, cb3[6].w, l(1.000000)
    add r8.w, -cb3[14].w, l(1.000000)
    mad r8.w, r8.w, r7.w, cb3[14].w
    div r7.w, r7.w, r8.w
    dp3 r8.w, r11.xyzx, -cb3[14].xyzx
    mad_sat r8.w, r8.w, cb3[30].x, cb3[38].x
    dp3_sat r10.w, r11.xyzx, r1.xywx
    mul r8.w, r8.w, r10.w
    mul r10.w, r7.w, r8.w
    mad r10.xyz, r10.wwww, cb3[22].xyzx, r10.xyzx
    mad r11.xyz, r5.xyzx, r2.yyyy, r11.xyzx
    dp3 r10.w, r11.xyzx, r11.xyzx
    rsq r10.w, r10.w
    mul r11.xyz, r10.wwww, r11.xyzx
    dp3_sat r10.w, r11.xyzx, r6.xyzx
    add r10.w, -r10.w, l(1.000000)
    mul r11.w, r10.w, r10.w
    mul r11.w, r11.w, r11.w
    mul r10.w, r10.w, r11.w
    mad r10.w, cb12[0].x, r10.w, r4.w
    dp3_sat r11.x, r11.xyzx, r1.xywx
    log r11.x, r11.x
    mul r11.x, r9.w, r11.x
    exp r11.x, r11.x
    mul r10.w, r10.w, r11.x
    mul r8.w, r8.w, r10.w
    mul r7.w, r7.w, r8.w
    mul r7.w, r5.w, r7.w
    mad r9.xyz, r7.wwww, cb3[22].xyzx, r9.xyzx
  endif 
else 
  mov r3.w, l(-1)
endif 
if_z r3.w
  ige r7.w, l(4), cb3[2].x
  or r3.w, r3.w, r7.w
  if_z r3.w
    eq r7.w, cb3[23].w, l(0.000000)
    add r11.xyz, -v6.xyzx, cb3[7].xyzx
    add r12.xyz, v6.xyzx, -cb3[7].xyzx
    dp3 r8.w, r12.xyzx, cb3[15].xyzx
    div_sat r8.w, r8.w, cb3[23].w
    mul r8.w, r8.w, cb3[23].w
    mad r12.xyz, cb3[15].xyzx, r8.wwww, cb3[7].xyzx
    add r12.xyz, r12.xyzx, -v6.xyzx
    movc r11.xyz, r7.wwww, r11.xyzx, r12.xyzx
    dp3 r7.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    mad_sat r7.w, -r7.w, cb3[7].w, l(1.000000)
    add r8.w, -cb3[15].w, l(1.000000)
    mad r8.w, r8.w, r7.w, cb3[15].w
    div r7.w, r7.w, r8.w
    dp3 r8.w, r11.xyzx, -cb3[15].xyzx
    mad_sat r8.w, r8.w, cb3[31].x, cb3[39].x
    dp3_sat r10.w, r11.xyzx, r1.xywx
    mul r8.w, r8.w, r10.w
    mul r10.w, r7.w, r8.w
    mad r10.xyz, r10.wwww, cb3[23].xyzx, r10.xyzx
    mad r11.xyz, r5.xyzx, r2.yyyy, r11.xyzx
    dp3 r10.w, r11.xyzx, r11.xyzx
    rsq r10.w, r10.w
    mul r11.xyz, r10.wwww, r11.xyzx
    dp3_sat r10.w, r11.xyzx, r6.xyzx
    add r10.w, -r10.w, l(1.000000)
    mul r11.w, r10.w, r10.w
    mul r11.w, r11.w, r11.w
    mul r10.w, r10.w, r11.w
    mad r10.w, cb12[0].x, r10.w, r4.w
    dp3_sat r11.x, r11.xyzx, r1.xywx
    log r11.x, r11.x
    mul r11.x, r9.w, r11.x
    exp r11.x, r11.x
    mul r10.w, r10.w, r11.x
    mul r8.w, r8.w, r10.w
    mul r7.w, r7.w, r8.w
    mul r7.w, r5.w, r7.w
    mad r9.xyz, r7.wwww, cb3[23].xyzx, r9.xyzx
  endif 
else 
  mov r3.w, l(-1)
endif 
if_z r3.w
  ige r7.w, l(5), cb3[2].x
  or r3.w, r3.w, r7.w
  if_z r3.w
    eq r7.w, cb3[24].w, l(0.000000)
    add r11.xyz, -v6.xyzx, cb3[8].xyzx
    add r12.xyz, v6.xyzx, -cb3[8].xyzx
    dp3 r8.w, r12.xyzx, cb3[16].xyzx
    div_sat r8.w, r8.w, cb3[24].w
    mul r8.w, r8.w, cb3[24].w
    mad r12.xyz, cb3[16].xyzx, r8.wwww, cb3[8].xyzx
    add r12.xyz, r12.xyzx, -v6.xyzx
    movc r11.xyz, r7.wwww, r11.xyzx, r12.xyzx
    dp3 r7.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    mad_sat r7.w, -r7.w, cb3[8].w, l(1.000000)
    add r8.w, -cb3[16].w, l(1.000000)
    mad r8.w, r8.w, r7.w, cb3[16].w
    div r7.w, r7.w, r8.w
    dp3 r8.w, r11.xyzx, -cb3[16].xyzx
    mad_sat r8.w, r8.w, cb3[32].x, cb3[40].x
    dp3_sat r10.w, r11.xyzx, r1.xywx
    mul r8.w, r8.w, r10.w
    mul r10.w, r7.w, r8.w
    mad r10.xyz, r10.wwww, cb3[24].xyzx, r10.xyzx
    mad r11.xyz, r5.xyzx, r2.yyyy, r11.xyzx
    dp3 r10.w, r11.xyzx, r11.xyzx
    rsq r10.w, r10.w
    mul r11.xyz, r10.wwww, r11.xyzx
    dp3_sat r10.w, r11.xyzx, r6.xyzx
    add r10.w, -r10.w, l(1.000000)
    mul r11.w, r10.w, r10.w
    mul r11.w, r11.w, r11.w
    mul r10.w, r10.w, r11.w
    mad r10.w, cb12[0].x, r10.w, r4.w
    dp3_sat r11.x, r11.xyzx, r1.xywx
    log r11.x, r11.x
    mul r11.x, r9.w, r11.x
    exp r11.x, r11.x
    mul r10.w, r10.w, r11.x
    mul r8.w, r8.w, r10.w
    mul r7.w, r7.w, r8.w
    mul r7.w, r5.w, r7.w
    mad r9.xyz, r7.wwww, cb3[24].xyzx, r9.xyzx
  endif 
else 
  mov r3.w, l(-1)
endif 
if_z r3.w
  ige r7.w, l(6), cb3[2].x
  or r3.w, r3.w, r7.w
  if_z r3.w
    eq r7.w, cb3[25].w, l(0.000000)
    add r11.xyz, -v6.xyzx, cb3[9].xyzx
    add r12.xyz, v6.xyzx, -cb3[9].xyzx
    dp3 r8.w, r12.xyzx, cb3[17].xyzx
    div_sat r8.w, r8.w, cb3[25].w
    mul r8.w, r8.w, cb3[25].w
    mad r12.xyz, cb3[17].xyzx, r8.wwww, cb3[9].xyzx
    add r12.xyz, r12.xyzx, -v6.xyzx
    movc r11.xyz, r7.wwww, r11.xyzx, r12.xyzx
    dp3 r7.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    mad_sat r7.w, -r7.w, cb3[9].w, l(1.000000)
    add r8.w, -cb3[17].w, l(1.000000)
    mad r8.w, r8.w, r7.w, cb3[17].w
    div r7.w, r7.w, r8.w
    dp3 r8.w, r11.xyzx, -cb3[17].xyzx
    mad_sat r8.w, r8.w, cb3[33].x, cb3[41].x
    dp3_sat r10.w, r11.xyzx, r1.xywx
    mul r8.w, r8.w, r10.w
    mul r10.w, r7.w, r8.w
    mad r10.xyz, r10.wwww, cb3[25].xyzx, r10.xyzx
    mad r11.xyz, r5.xyzx, r2.yyyy, r11.xyzx
    dp3 r10.w, r11.xyzx, r11.xyzx
    rsq r10.w, r10.w
    mul r11.xyz, r10.wwww, r11.xyzx
    dp3_sat r10.w, r11.xyzx, r6.xyzx
    add r10.w, -r10.w, l(1.000000)
    mul r11.w, r10.w, r10.w
    mul r11.w, r11.w, r11.w
    mul r10.w, r10.w, r11.w
    mad r10.w, cb12[0].x, r10.w, r4.w
    dp3_sat r11.x, r11.xyzx, r1.xywx
    log r11.x, r11.x
    mul r11.x, r9.w, r11.x
    exp r11.x, r11.x
    mul r10.w, r10.w, r11.x
    mul r8.w, r8.w, r10.w
    mul r7.w, r7.w, r8.w
    mul r7.w, r5.w, r7.w
    mad r9.xyz, r7.wwww, cb3[25].xyzx, r9.xyzx
  endif 
else 
  mov r3.w, l(-1)
endif 
if_z r3.w
  ige r7.w, l(7), cb3[2].x
  or r3.w, r3.w, r7.w
  if_z r3.w
    eq r3.w, cb3[26].w, l(0.000000)
    add r11.xyz, -v6.xyzx, cb3[10].xyzx
    add r12.xyz, v6.xyzx, -cb3[10].xyzx
    dp3 r7.w, r12.xyzx, cb3[18].xyzx
    div_sat r7.w, r7.w, cb3[26].w
    mul r7.w, r7.w, cb3[26].w
    mad r12.xyz, cb3[18].xyzx, r7.wwww, cb3[10].xyzx
    add r12.xyz, r12.xyzx, -v6.xyzx
    movc r11.xyz, r3.wwww, r11.xyzx, r12.xyzx
    dp3 r3.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r7.w, r11.xyzx, r11.xyzx
    rsq r7.w, r7.w
    mul r11.xyz, r7.wwww, r11.xyzx
    mad_sat r3.w, -r3.w, cb3[10].w, l(1.000000)
    add r7.w, -cb3[18].w, l(1.000000)
    mad r7.w, r7.w, r3.w, cb3[18].w
    div r3.w, r3.w, r7.w
    dp3 r7.w, r11.xyzx, -cb3[18].xyzx
    mad_sat r7.w, r7.w, cb3[34].x, cb3[42].x
    dp3_sat r8.w, r11.xyzx, r1.xywx
    mul r7.w, r7.w, r8.w
    mul r8.w, r3.w, r7.w
    mad r10.xyz, r8.wwww, cb3[26].xyzx, r10.xyzx
    mad r5.xyz, r5.xyzx, r2.yyyy, r11.xyzx
    dp3 r2.y, r5.xyzx, r5.xyzx
    rsq r2.y, r2.y
    mul r5.xyz, r2.yyyy, r5.xyzx
    dp3_sat r2.y, r5.xyzx, r6.xyzx
    add r2.y, -r2.y, l(1.000000)
    mul r6.x, r2.y, r2.y
    mul r6.x, r6.x, r6.x
    mul r2.y, r2.y, r6.x
    mad r2.y, cb12[0].x, r2.y, r4.w
    dp3_sat r4.w, r5.xyzx, r1.xywx
    log r4.w, r4.w
    mul r4.w, r4.w, r9.w
    exp r4.w, r4.w
    mul r2.y, r2.y, r4.w
    mul r2.y, r7.w, r2.y
    mul r2.y, r3.w, r2.y
    mul r2.y, r5.w, r2.y
    mad r9.xyz, r2.yyyy, cb3[26].xyzx, r9.xyzx
  endif 
endif 
mul r2.y, r6.w, r6.w
mul r0.w, r0.w, r0.w
mul r5.xyz, r9.xyzx, r0.wwww
mad r5.xyz, r2.yyyy, r10.xyzx, r5.xyzx
mad r5.xyz, r7.xyzx, r2.wwww, r5.xyzx
mad r0.z, r1.z, r0.z, cb3[43].w
mul r0.z, r0.z, cb3[44].w
max r0.z, r0.z, l(0.000000)
mad r6.xyz, cb3[47].xyzx, r0.zzzz, cb3[48].xyzx
add r0.w, -cb2[12].z, l(1.000000)
mad r7.xyz, cb3[45].xyzx, r0.zzzz, cb3[46].xyzx
mul r7.xyz, r7.xyzx, cb2[12].zzzz
mad r6.xyz, r6.xyzx, r0.wwww, r7.xyzx
mul r6.xyz, r4.yyyy, r6.xyzx
mad r7.xyz, cb3[43].xyzx, r0.zzzz, cb3[44].xyzx
mov r9.x, cb3[46].w
mov r9.y, cb3[47].w
mov r9.z, cb3[48].w
dp3_sat r0.z, r9.xyzx, r1.xywx
mad r1.xyz, cb3[49].xyzx, r0.zzzz, r7.xyzx
mad r1.xyz, r1.xyzx, r4.xxxx, r6.xyzx
mad r1.xyz, r1.xyzx, r6.wwww, r5.xyzx
add r0.z, -r6.w, l(1.000000)
max r0.w, r4.y, r4.x
mul r3.xyz, r0.wwww, r3.xyzx
mul_sat r0.w, r2.z, l(0.001776)
mul r2.yzw, r0.wwww, r3.xxyz
mul r2.yzw, r2.yyzw, l(0.000000, 0.681690, 0.681690, 0.681690)
mad r2.yzw, r3.xxyz, l(0.000000, 0.318310, 0.318310, 0.318310), r2.yyzw
mad r1.xyz, r2.yzwy, r0.zzzz, r1.xyzx
mul r0.xy, r0.xyxx, cb12[2].yzyy
sqrt r0.z, r2.x
add r0.z, -r0.z, cb12[2].w
div_sat r0.z, r0.z, cb12[2].w
mad r0.xy, r0.xyxx, r0.zzzz, v7.xyxx
div_sat r0.xy, r0.xyxx, cb2[14].xyxx
sample_l r0.xyzw, r0.xyxx, t1.xyzw, s1, l(0.000000)
add r1.xyz, -r0.xyzx, r1.xyzx
mad r0.xyz, r4.zzzz, r1.xyzx, r0.xyzx
if_nz cb5[7].x
  dp3 r0.w, r8.xyzx, r8.xyzx
  sqrt r1.x, r0.w
  add r1.y, r1.x, -cb3[50].x
  max r1.y, r1.y, l(0.000000)
  div r1.x, r1.y, r1.x
  mul r1.x, r1.x, r8.z
  mul r1.z, r1.x, cb3[52].z
  lt r1.x, l(0.010000), |r1.x|
  mul r1.w, r1.z, l(-1.442695)
  exp r1.w, r1.w
  add r1.w, -r1.w, l(1.000000)
  div r1.z, r1.w, r1.z
  movc r1.x, r1.x, r1.z, l(1.000000)
  mul r1.z, r1.y, cb3[51].w
  mul r1.x, r1.x, r1.z
  min r1.x, r1.x, l(1.000000)
  mul r1.x, r1.x, l(1.442695)
  exp r1.x, r1.x
  min r1.x, r1.x, l(1.000000)
  add r1.x, -r1.x, l(1.000000)
  mul r1.z, r1.x, cb3[52].y
  rsq r0.w, r0.w
  mul r2.xyz, r0.wwww, r8.xyzx
  dp3_sat r0.w, r2.xyzx, cb3[54].xyzx
  log r0.w, r0.w
  mul r0.w, r0.w, cb3[54].w
  exp r0.w, r0.w
  dp3_sat r1.w, r2.xyzx, cb3[53].xyzx
  log r1.w, r1.w
  mul r1.w, r1.w, cb3[53].w
  exp r1.w, r1.w
  mad r1.x, -r1.x, cb3[52].y, l(1.000000)
  mul r1.x, r1.x, cb3[51].y
  add r2.x, r1.y, -cb3[52].x
  max r2.x, r2.x, l(0.000000)
  mul r2.x, r2.x, cb3[51].x
  mul r2.x, r2.x, l(1.442695)
  exp r2.x, r2.x
  add r2.x, -r2.x, l(1.000000)
  mad_sat r1.z, r1.x, r2.x, r1.z
  mul r1.y, r1.y, -cb3[51].z
  mul r1.y, r1.y, l(1.442695)
  exp r1.y, r1.y
  add r1.y, -r1.y, l(1.000000)
  add r2.xyz, -cb3[56].xyzx, cb3[58].xyzx
  mad r2.xyz, r0.wwww, r2.xyzx, cb3[56].xyzx
  add r3.xyz, -r2.xyzx, cb3[55].xyzx
  mad r2.xyz, r1.wwww, r3.xyzx, r2.xyzx
  add r2.xyz, r2.xyzx, -cb3[57].xyzx
  mad r2.xyz, r1.yyyy, r2.xyzx, cb3[57].xyzx
  mov r3.x, cb3[55].w
  mov r3.y, cb3[56].w
  mov r3.z, cb3[57].w
  add r3.xyz, -r2.xyzx, r3.xyzx
  mad r1.xyw, r1.xxxx, r3.xyxz, r2.xyxz
  lt r0.w, l(0.000000), cb2[18].y
  if_nz r0.w
    mul r2.xy, v7.xyxx, cb2[14].zwzz
    sample r2.xyzw, r2.xyxx, t11.xyzw, s11
    add r0.w, r2.x, l(-1.000000)
    mad_sat r0.w, cb2[18].y, r0.w, l(1.000000)
  else 
    mov r0.w, l(1.000000)
  endif 
  mad r1.xyw, r1.xyxw, r0.wwww, -r0.xyxz
  mad r1.xyz, r1.zzzz, r1.xywx, r0.xyzx
else 
  dp3 r0.w, r8.xyzx, r8.xyzx
  sqrt r1.w, r0.w
  add r2.x, r1.w, -cb3[50].x
  max r2.x, r2.x, l(0.000000)
  div r1.w, r2.x, r1.w
  mul r1.w, r1.w, r8.z
  mul r2.y, r1.w, cb3[52].z
  lt r1.w, l(0.010000), |r1.w|
  mul r2.z, r2.y, l(-1.442695)
  exp r2.z, r2.z
  add r2.z, -r2.z, l(1.000000)
  div r2.y, r2.z, r2.y
  movc r1.w, r1.w, r2.y, l(1.000000)
  mul r2.y, r2.x, cb3[51].w
  mul r1.w, r1.w, r2.y
  min r1.w, r1.w, l(1.000000)
  mul r1.w, r1.w, l(1.442695)
  exp r1.w, r1.w
  min r1.w, r1.w, l(1.000000)
  add r1.w, -r1.w, l(1.000000)
  mul r2.y, r1.w, cb3[52].y
  rsq r0.w, r0.w
  mul r3.xyz, r0.wwww, r8.xyzx
  dp3_sat r0.w, r3.xyzx, cb3[54].xyzx
  log r0.w, r0.w
  mul r0.w, r0.w, cb3[54].w
  exp r0.w, r0.w
  dp3_sat r2.z, r3.xyzx, cb3[53].xyzx
  log r2.z, r2.z
  mul r2.z, r2.z, cb3[53].w
  exp r2.z, r2.z
  mad r1.w, -r1.w, cb3[52].y, l(1.000000)
  mul r1.w, r1.w, cb3[51].y
  add r2.w, r2.x, -cb3[52].x
  max r2.w, r2.w, l(0.000000)
  mul r2.w, r2.w, cb3[51].x
  mul r2.w, r2.w, l(1.442695)
  exp r2.w, r2.w
  add r2.w, -r2.w, l(1.000000)
  mad_sat r2.y, r1.w, r2.w, r2.y
  mul r2.x, r2.x, -cb3[51].z
  mul r2.x, r2.x, l(1.442695)
  exp r2.x, r2.x
  add r2.x, -r2.x, l(1.000000)
  add r3.xyz, -cb3[56].xyzx, cb3[58].xyzx
  mad r3.xyz, r0.wwww, r3.xyzx, cb3[56].xyzx
  add r4.xyz, -r3.xyzx, cb3[55].xyzx
  mad r3.xyz, r2.zzzz, r4.xyzx, r3.xyzx
  add r3.xyz, r3.xyzx, -cb3[57].xyzx
  mad r2.xzw, r2.xxxx, r3.xxyz, cb3[57].xxyz
  mov r3.x, cb3[55].w
  mov r3.y, cb3[56].w
  mov r3.z, cb3[57].w
  add r3.xyz, -r2.xzwx, r3.xyzx
  mad r2.xzw, r1.wwww, r3.xxyz, r2.xxzw
  add r2.xzw, -r0.xxyz, r2.xxzw
  mad r1.xyz, r2.yyyy, r2.xzwx, r0.xyzx
endif 
mul o0.xyz, r1.xyzx, cb2[13].zzzz
mov o0.w, l(1.000000)
ret 
// Approximately 761 instruction slots used
