//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16
//   float4 globalScreenSize;           // Offset:  224 Size:    16
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16
//   float4 gDirectionalColour;         // Offset:   16 Size:    16
//   int gNumForwardLights;             // Offset:   32 Size:     4
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128
//   float gLightConeScale[8];          // Offset:  432 Size:   116
//   float gLightConeOffset[8];         // Offset:  560 Size:   116
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80
//   float4 globalFogColor;             // Offset:  880 Size:    16
//   float4 globalFogColorE;            // Offset:  896 Size:    16
//   float4 globalFogColorN;            // Offset:  912 Size:    16
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer more_stuff
// {
//
//   float4 gEntitySelectColor[2];      // Offset:    0 Size:    32 [unused]
//   float4 gAmbientOcclusionEffect;    // Offset:   32 Size:    16 [unused]
//   float4 gDynamicBakesAndWetness;    // Offset:   48 Size:    16 [unused]
//   float4 gAlphaRefVec0;              // Offset:   64 Size:    16 [unused]
//   float4 gAlphaRefVec1;              // Offset:   80 Size:    16 [unused]
//   float gAlphaTestRef;               // Offset:   96 Size:     4 [unused]
//   bool gTreesUseDiscard;             // Offset:  100 Size:     4 [unused]
//   float gReflectionMipCount;         // Offset:  104 Size:     4
//   bool gUseTransparencyAA;           // Offset:  108 Size:     4 [unused]
//   bool gUseFogRay;                   // Offset:  112 Size:     4
//
// }
//
// cbuffer megashader_locals
// {
//
//   float specularFresnel;             // Offset:    0 Size:     4
//   float specularFalloffMult;         // Offset:    4 Size:     4 [unused]
//   float specularIntensityMult;       // Offset:    8 Size:     4 [unused]
//   float3 specMapIntMask;             // Offset:   16 Size:    12
//   float bumpiness;                   // Offset:   28 Size:     4
//   float useTessellation;             // Offset:   32 Size:     4 [unused]
//   float HardAlphaBlend;              // Offset:   36 Size:     4 [unused]
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16
//   float4 gCSMResolution;             // Offset:  224 Size:    16
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
// cbuffer glass_breakable_locals
// {
//
//   float4 BrokenDiffuseColor;         // Offset:    0 Size:    16
//   float4 BrokenSpecularColor;        // Offset:   16 Size:    16
//   float4 CrackMatrix;                // Offset:   32 Size:    16 [unused]
//   float4 CrackOffset;                // Offset:   48 Size:    16 [unused]
//   float2 CrackEdgeBumpTileScale;     // Offset:   64 Size:     8
//   float2 CrackDecalBumpTileScale;    // Offset:   72 Size:     8 [unused]
//   float CrackEdgeBumpAmount;         // Offset:   80 Size:     4
//   float CrackDecalBumpAmount;        // Offset:   84 Size:     4 [unused]
//   float CrackDecalBumpAlphaThreshold;// Offset:   88 Size:     4 [unused]
//   float4 DecalTint;                  // Offset:   96 Size:    16 [unused]
//   float4 gDecalChannelSelection[4];  // Offset:  112 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// ReflectionSampler                 sampler      NA          NA             s1      1 
// BumpSampler                       sampler      NA          NA             s2      1 
// DecalSampler                      sampler      NA          NA             s4      1 
// BrokenBumpSampler                 sampler      NA          NA             s5      1 
// FogRaySampler                     sampler      NA          NA            s11      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// ReflectionSampler                 texture  float4          2d             t1      1 
// BumpSampler                       texture  float4          2d             t2      1 
// DecalSampler                      texture  float4          2d             t4      1 
// BrokenBumpSampler                 texture  float4          2d             t5      1 
// FogRaySampler                     texture  float4          2d            t11      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// more_stuff                        cbuffer      NA          NA            cb5      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// glass_breakable_locals            cbuffer      NA          NA           cb10      1 
// megashader_locals                 cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// COLOR                    1   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyz         3     NONE   float   xyz 
// TEXCOORD                 2   xyz         4     NONE   float   xyz 
// TEXCOORD                 3   xyz         5     NONE   float   xyz 
// TEXCOORD                 4   xyz         6     NONE   float       
// TEXCOORD                 5   xyz         7     NONE   float   xyz 
// TEXCOORD                 6   xy          8     NONE   float   xy  
// SV_Position              0   xyzw        9      POS   float   xy  
// SV_ClipDistance          0   xyzw       10  CLIPDST   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB1[16], immediateIndexed
dcl_constantbuffer CB2[19], immediateIndexed
dcl_constantbuffer CB3[59], immediateIndexed
dcl_constantbuffer CB5[8], immediateIndexed
dcl_constantbuffer CB12[2], immediateIndexed
dcl_constantbuffer CB6[15], immediateIndexed
dcl_constantbuffer CB10[6], immediateIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s11, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps linear v7.xyz
dcl_input_ps linear v8.xy
dcl_input_ps_siv linear noperspective v9.xy, position
dcl_output o0.xyzw
dcl_temps 26
dcl_indexableTemp x0[4], 4
sample r0.xyzw, v2.zwzz, t4.xyzw, s4
dp4 r0.x, v1.xyzw, r0.xyzw
mul r0.yz, v2.xxyx, cb10[4].xxyx
sample r1.xyzw, r0.yzyy, t5.xyzw, s5
mad r0.yz, r1.xxyx, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
mad r1.xy, r0.yzyy, cb10[5].xxxx, v3.xyxx
mov r1.z, v3.z
dp3 r0.y, r1.xyzx, r1.xyzx
rsq r0.y, r0.y
mul r0.yzw, r0.yyyy, r1.xxyz
sample r1.xyzw, v2.xyxx, t2.xyzw, s2
mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r1.z, r1.xyxx, r1.xyxx
add r1.z, -r1.z, l(1.000000)
sqrt r1.z, |r1.z|
max r1.w, cb12[1].w, l(0.001000)
mul r1.xy, r1.wwww, r1.xyxx
mul r2.xyz, r1.yyyy, v5.xyzx
mad r1.xyw, r1.xxxx, v4.xyxz, r2.xyxz
mad r0.yzw, r1.zzzz, r0.yyzw, r1.xxyw
dp3 r1.x, r0.yzwy, r0.yzwy
rsq r1.x, r1.x
mul r1.yzw, r0.yyzw, r1.xxxx
mad_sat r2.xyzw, r0.xxxx, v0.xyzw, cb10[0].xyzw
mov_sat r0.y, v8.y
dp3 r0.z, r0.xxxx, cb12[1].xyzx
max r0.x, r0.x, cb10[1].w
max r0.y, r0.z, r0.y
mul r2.xyz, r2.xyzx, r2.xyzx
add r3.xyz, -v7.xyzx, cb1[15].xyzx
dp3 r0.z, r3.xyzx, r3.xyzx
rsq r0.z, r0.z
mul r4.xyz, r0.zzzz, r3.xyzx
mad r5.xyz, r3.xyzx, r0.zzzz, -cb3[0].xyzx
dp3 r3.w, r5.xyzx, r5.xyzx
rsq r3.w, r3.w
mul r5.xyz, r3.wwww, r5.xyzx
min r0.y, r0.y, l(1.000000)
mul r6.xy, cb2[11].zyzz, cb2[11].zyzz
add r3.w, r0.x, l(-500.000000)
max r3.w, r3.w, l(0.000000)
add r0.x, r0.x, -r3.w
mul r3.w, r3.w, l(558.000000)
mad r0.x, r0.x, l(3.000000), r3.w
dp3 r3.w, r3.xyzx, cb1[14].xyzx
add r7.xyz, v7.xyzx, -cb1[15].xyzx
mul r8.xyz, r7.yyyy, cb6[1].xyzx
mad r8.xyz, r7.xxxx, cb6[0].xyzx, r8.xyzx
mad r8.xyz, r7.zzzz, cb6[2].xyzx, r8.xyzx
mad r9.xyz, r8.xyzx, cb6[4].xyzx, cb6[8].xyzx
mov x0[0].xyz, r9.xyzx
mad r10.xyz, r8.xyzx, cb6[5].xyzx, cb6[9].xyzx
mov x0[1].xyz, r10.xyzx
mad r11.xyz, r8.xyzx, cb6[6].xyzx, cb6[10].xyzx
mov x0[2].xyz, r11.xyzx
mad r8.xyz, r8.xyzx, cb6[7].xyzx, cb6[11].xyzx
mov x0[3].xyz, r8.xyzx
mul r12.yw, cb6[14].zzzw, l(0.000000, -0.346097, 0.000000, 0.328490)
mad r4.w, -cb6[14].z, l(1.500000), l(1.000000)
mul r4.w, r4.w, l(0.500000)
max r5.w, |r11.y|, |r11.x|
lt r5.w, r5.w, r4.w
movc r5.w, r5.w, l(2), l(3)
max r6.z, |r10.y|, |r10.x|
lt r6.z, r6.z, r4.w
movc r5.w, r6.z, l(1), r5.w
max r6.z, |r9.y|, |r9.x|
lt r4.w, r6.z, r4.w
movc r4.w, r4.w, l(0), r5.w
mov r9.xyz, x0[r4.w + 0].xyzx
itof r4.w, r4.w
add r5.w, r4.w, l(0.500000)
mul r5.w, r5.w, l(0.250000)
eq r10.xyzw, l(0.000000, 1.000000, 2.000000, 3.000000), r4.wwww
and r10.xyzw, r10.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
dp4 r4.w, r10.xyzw, cb6[12].xyzw
dp4 r6.z, r10.xyzw, cb6[13].xyzw
add r10.x, r9.x, l(0.500000)
mad r10.y, r9.y, l(0.250000), r5.w
ne r5.w, r4.w, l(0.000000)
add r4.w, -r4.w, r9.z
deriv_rtx r11.xyw, r10.xyxy
deriv_rtx r11.z, r4.w
deriv_rty r13.xyz, r10.yxyy
deriv_rty r13.w, r4.w
mul r8.zw, r11.yyyw, r13.yyyw
mad r14.xy, r11.xzxx, r13.xzxx, -r8.zwzz
div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r14.x
mul r7.w, r11.z, r13.y
mad r14.z, r11.x, r13.w, -r7.w
mul r8.zw, r6.wwww, r14.yyyz
max r8.zw, r8.zzzw, l(0.000000, 0.000000, 0.000000, 0.000000)
min r8.zw, r8.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
mad r4.w, -r6.z, r8.z, r4.w
mad r4.w, -r6.z, r8.w, r4.w
movc r12.z, r5.w, r4.w, r9.z
mov r10.z, l(0)
add r9.xyz, r10.xyzx, r12.ywzy
mul r12.xy, cb6[14].zwzz, l(-0.799291, 0.201741, 0.000000, 0.000000)
add r11.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(-0.031176, 0.179338, 0.000000, 0.000000)
add r13.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(0.514749, 0.253502, 0.000000, 0.000000)
add r14.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(-0.072870, 0.008097, 0.000000, 0.000000)
add r15.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(-0.969781, 0.034522, 0.000000, 0.000000)
add r16.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(0.545547, 0.024129, 0.000000, 0.000000)
add r17.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(-0.028906, -0.136785, 0.000000, 0.000000)
add r18.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(-0.479511, -0.244833, 0.000000, 0.000000)
add r19.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(0.758788, -0.112109, 0.000000, 0.000000)
add r20.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(0.339353, -0.249328, 0.000000, 0.000000)
add r21.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(1.070598, 0.208123, 0.000000, 0.000000)
add r22.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(1.294038, -0.018078, 0.000000, 0.000000)
add r23.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(-0.747563, -0.113974, 0.000000, 0.000000)
add r24.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(0.947722, -0.248764, 0.000000, 0.000000)
add r25.xyz, r10.xyzx, r12.xyzx
mul r12.xy, cb6[14].zwzz, l(-1.343153, -0.088584, 0.000000, 0.000000)
add r10.xyz, r10.xyzx, r12.xyzx
sample_c_lz r9.x, r9.xyxx, t15.xxxx, s15, r9.z
sample_c_lz r9.y, r11.xyxx, t15.xxxx, s15, r11.z
sample_c_lz r9.z, r13.xyxx, t15.xxxx, s15, r13.z
sample_c_lz r9.w, r14.xyxx, t15.xxxx, s15, r14.z
sample_c_lz r11.x, r15.xyxx, t15.xxxx, s15, r15.z
sample_c_lz r11.y, r16.xyxx, t15.xxxx, s15, r16.z
sample_c_lz r11.z, r17.xyxx, t15.xxxx, s15, r17.z
sample_c_lz r11.w, r18.xyxx, t15.xxxx, s15, r18.z
sample_c_lz r12.x, r19.xyxx, t15.xxxx, s15, r19.z
sample_c_lz r12.y, r20.xyxx, t15.xxxx, s15, r20.z
sample_c_lz r12.z, r21.xyxx, t15.xxxx, s15, r21.z
sample_c_lz r12.w, r22.xyxx, t15.xxxx, s15, r22.z
sample_c_lz r13.x, r23.xyxx, t15.xxxx, s15, r23.z
sample_c_lz r13.y, r24.xyxx, t15.xxxx, s15, r24.z
sample_c_lz r13.z, r25.xyxx, t15.xxxx, s15, r25.z
sample_c_lz r13.w, r10.xyxx, t15.xxxx, s15, r10.z
add r9.xyzw, r9.xyzw, r11.xyzw
add r9.xyzw, r12.xyzw, r9.xyzw
add r9.xyzw, r13.xyzw, r9.xyzw
dp4 r4.w, r9.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mad_sat r3.w, r3.w, cb6[0].w, cb6[1].w
max r5.w, |r8.y|, |r8.x|
mad_sat r5.w, r5.w, l(15.000000), l(-6.300000)
add r3.w, -r3.w, l(1.000000)
mul r3.w, r5.w, r3.w
mad r3.w, r4.w, l(0.062500), r3.w
mul r3.w, r3.w, r3.w
min r3.w, r3.w, l(1.000000)
mad_sat r4.w, v7.z, cb6[3].x, cb6[3].y
sqrt r4.w, r4.w
mul r4.w, r4.w, cb6[3].z
mad r3.w, r4.w, -r3.w, r3.w
dp3 r4.w, r1.yzwy, -cb3[0].xyzx
mov_sat r5.w, r4.w
add r5.w, -|r4.w|, r5.w
mad r4.w, r2.w, r5.w, |r4.w|
dp3_sat r8.x, r4.xyzx, r1.yzwy
dp3_sat r8.y, r5.xyzx, -cb3[0].xyzx
add r6.zw, -r8.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
mul r8.xy, r6.zwzz, r6.zwzz
mul r8.xy, r8.xyxx, r8.xyxx
mul r6.zw, r6.zzzw, r8.xxxy
add r5.w, -cb12[0].x, l(1.000000)
mad r6.zw, cb12[0].xxxx, r6.zzzw, r5.wwww
add r8.xy, r0.xxxx, l(2.000000, 0.000000, 0.000000, 0.000000)
mul r7.w, r8.x, l(0.125000)
max r8.x, r2.w, r6.z
add r6.z, r6.z, l(-1.000000)
mad r6.z, r8.x, r6.z, l(1.000000)
mad r6.z, -r0.y, r6.z, l(1.000000)
dp3 r5.x, r1.yzwy, r5.xyzx
add_sat r5.x, r5.x, l(0.000000)
log r5.x, r5.x
mul r5.x, r5.x, r8.y
exp r5.x, r5.x
mul r5.x, r6.w, r5.x
mul r5.x, r7.w, r5.x
mul r5.x, r0.y, r5.x
mul r5.x, r4.w, r5.x
mul r4.w, r4.w, r6.z
mad r5.xyz, r2.xyzx, r4.wwww, r5.xxxx
mul r5.xyz, r5.xyzx, cb3[1].xyzx
ige r4.w, l(0), cb3[2].x
if_z r4.w
  eq r6.w, cb3[19].w, l(0.000000)
  add r9.xyz, -v7.xyzx, cb3[3].xyzx
  add r10.xyz, v7.xyzx, -cb3[3].xyzx
  dp3 r8.z, r10.xyzx, cb3[11].xyzx
  div_sat r8.z, r8.z, cb3[19].w
  mul r8.z, r8.z, cb3[19].w
  mad r10.xyz, cb3[11].xyzx, r8.zzzz, cb3[3].xyzx
  add r10.xyz, r10.xyzx, -v7.xyzx
  movc r9.xyz, r6.wwww, r9.xyzx, r10.xyzx
  dp3 r6.w, r9.xyzx, r9.xyzx
  add r9.xyz, r9.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
  dp3 r8.z, r9.xyzx, r9.xyzx
  rsq r8.z, r8.z
  mul r9.xyz, r8.zzzz, r9.xyzx
  mad_sat r6.w, -r6.w, cb3[3].w, l(1.000000)
  add r8.z, -cb3[11].w, l(1.000000)
  mad r8.z, r8.z, r6.w, cb3[11].w
  div r6.w, r6.w, r8.z
  dp3 r8.z, r9.xyzx, -cb3[11].xyzx
  mad_sat r8.z, r8.z, cb3[27].x, cb3[35].x
  dp3 r8.w, r9.xyzx, r1.yzwy
  mov_sat r9.w, r8.w
  add r9.w, -|r8.w|, r9.w
  mad r8.w, r2.w, r9.w, |r8.w|
  mul r8.z, r8.z, r8.w
  mul r8.w, r6.w, r8.z
  mul r10.xyz, r8.wwww, cb3[19].xyzx
  mul r10.xyz, r2.xyzx, r10.xyzx
  mad r9.xyz, r3.xyzx, r0.zzzz, r9.xyzx
  dp3 r8.w, r9.xyzx, r9.xyzx
  rsq r8.w, r8.w
  mul r9.xyz, r8.wwww, r9.xyzx
  dp3_sat r8.w, r9.xyzx, r4.xyzx
  add r8.w, -r8.w, l(1.000000)
  mul r9.w, r8.w, r8.w
  mul r9.w, r9.w, r9.w
  mul r8.w, r8.w, r9.w
  mad r8.w, cb12[0].x, r8.w, r5.w
  dp3_sat r9.x, r9.xyzx, r1.yzwy
  log r9.x, r9.x
  mul r9.x, r8.y, r9.x
  exp r9.x, r9.x
  mul r8.w, r8.w, r9.x
  mul r8.z, r8.z, r8.w
  mul r6.w, r6.w, r8.z
  mul r6.w, r7.w, r6.w
  mul r9.xyz, r6.wwww, cb3[19].xyzx
else 
  mov r10.xyz, l(0,0,0,0)
  mov r9.xyz, l(0,0,0,0)
endif 
ilt r6.w, l(0), cb3[2].x
if_nz r6.w
  ige r8.z, l(1), cb3[2].x
  or r6.w, r4.w, r6.w
  movc r4.w, r8.z, r6.w, r4.w
  if_z r4.w
    eq r6.w, cb3[20].w, l(0.000000)
    add r11.xyz, -v7.xyzx, cb3[4].xyzx
    add r12.xyz, v7.xyzx, -cb3[4].xyzx
    dp3 r8.z, r12.xyzx, cb3[12].xyzx
    div_sat r8.z, r8.z, cb3[20].w
    mul r8.z, r8.z, cb3[20].w
    mad r12.xyz, cb3[12].xyzx, r8.zzzz, cb3[4].xyzx
    add r12.xyz, r12.xyzx, -v7.xyzx
    movc r11.xyz, r6.wwww, r11.xyzx, r12.xyzx
    dp3 r6.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.z, r11.xyzx, r11.xyzx
    rsq r8.z, r8.z
    mul r11.xyz, r8.zzzz, r11.xyzx
    mad_sat r6.w, -r6.w, cb3[4].w, l(1.000000)
    add r8.z, -cb3[12].w, l(1.000000)
    mad r8.z, r8.z, r6.w, cb3[12].w
    div r6.w, r6.w, r8.z
    dp3 r8.z, r11.xyzx, -cb3[12].xyzx
    mad_sat r8.z, r8.z, cb3[28].x, cb3[36].x
    dp3 r8.w, r11.xyzx, r1.yzwy
    mov_sat r9.w, r8.w
    add r9.w, -|r8.w|, r9.w
    mad r8.w, r2.w, r9.w, |r8.w|
    mul r8.z, r8.z, r8.w
    mul r8.w, r6.w, r8.z
    mul r12.xyz, r8.wwww, cb3[20].xyzx
    mad r10.xyz, r12.xyzx, r2.xyzx, r10.xyzx
    mad r11.xyz, r3.xyzx, r0.zzzz, r11.xyzx
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    dp3_sat r8.w, r11.xyzx, r4.xyzx
    add r8.w, -r8.w, l(1.000000)
    mul r9.w, r8.w, r8.w
    mul r9.w, r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mad r8.w, cb12[0].x, r8.w, r5.w
    dp3_sat r9.w, r11.xyzx, r1.yzwy
    log r9.w, r9.w
    mul r9.w, r8.y, r9.w
    exp r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mul r8.z, r8.z, r8.w
    mul r6.w, r6.w, r8.z
    mul r6.w, r7.w, r6.w
    mad r9.xyz, r6.wwww, cb3[20].xyzx, r9.xyzx
  endif 
else 
  mov r4.w, l(-1)
endif 
if_z r4.w
  ige r6.w, l(2), cb3[2].x
  or r4.w, r4.w, r6.w
  if_z r4.w
    eq r6.w, cb3[21].w, l(0.000000)
    add r11.xyz, -v7.xyzx, cb3[5].xyzx
    add r12.xyz, v7.xyzx, -cb3[5].xyzx
    dp3 r8.z, r12.xyzx, cb3[13].xyzx
    div_sat r8.z, r8.z, cb3[21].w
    mul r8.z, r8.z, cb3[21].w
    mad r12.xyz, cb3[13].xyzx, r8.zzzz, cb3[5].xyzx
    add r12.xyz, r12.xyzx, -v7.xyzx
    movc r11.xyz, r6.wwww, r11.xyzx, r12.xyzx
    dp3 r6.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.z, r11.xyzx, r11.xyzx
    rsq r8.z, r8.z
    mul r11.xyz, r8.zzzz, r11.xyzx
    mad_sat r6.w, -r6.w, cb3[5].w, l(1.000000)
    add r8.z, -cb3[13].w, l(1.000000)
    mad r8.z, r8.z, r6.w, cb3[13].w
    div r6.w, r6.w, r8.z
    dp3 r8.z, r11.xyzx, -cb3[13].xyzx
    mad_sat r8.z, r8.z, cb3[29].x, cb3[37].x
    dp3 r8.w, r11.xyzx, r1.yzwy
    mov_sat r9.w, r8.w
    add r9.w, -|r8.w|, r9.w
    mad r8.w, r2.w, r9.w, |r8.w|
    mul r8.z, r8.z, r8.w
    mul r8.w, r6.w, r8.z
    mul r12.xyz, r8.wwww, cb3[21].xyzx
    mad r10.xyz, r12.xyzx, r2.xyzx, r10.xyzx
    mad r11.xyz, r3.xyzx, r0.zzzz, r11.xyzx
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    dp3_sat r8.w, r11.xyzx, r4.xyzx
    add r8.w, -r8.w, l(1.000000)
    mul r9.w, r8.w, r8.w
    mul r9.w, r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mad r8.w, cb12[0].x, r8.w, r5.w
    dp3_sat r9.w, r11.xyzx, r1.yzwy
    log r9.w, r9.w
    mul r9.w, r8.y, r9.w
    exp r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mul r8.z, r8.z, r8.w
    mul r6.w, r6.w, r8.z
    mul r6.w, r7.w, r6.w
    mad r9.xyz, r6.wwww, cb3[21].xyzx, r9.xyzx
  endif 
else 
  mov r4.w, l(-1)
endif 
if_z r4.w
  ige r6.w, l(3), cb3[2].x
  or r4.w, r4.w, r6.w
  if_z r4.w
    eq r6.w, cb3[22].w, l(0.000000)
    add r11.xyz, -v7.xyzx, cb3[6].xyzx
    add r12.xyz, v7.xyzx, -cb3[6].xyzx
    dp3 r8.z, r12.xyzx, cb3[14].xyzx
    div_sat r8.z, r8.z, cb3[22].w
    mul r8.z, r8.z, cb3[22].w
    mad r12.xyz, cb3[14].xyzx, r8.zzzz, cb3[6].xyzx
    add r12.xyz, r12.xyzx, -v7.xyzx
    movc r11.xyz, r6.wwww, r11.xyzx, r12.xyzx
    dp3 r6.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.z, r11.xyzx, r11.xyzx
    rsq r8.z, r8.z
    mul r11.xyz, r8.zzzz, r11.xyzx
    mad_sat r6.w, -r6.w, cb3[6].w, l(1.000000)
    add r8.z, -cb3[14].w, l(1.000000)
    mad r8.z, r8.z, r6.w, cb3[14].w
    div r6.w, r6.w, r8.z
    dp3 r8.z, r11.xyzx, -cb3[14].xyzx
    mad_sat r8.z, r8.z, cb3[30].x, cb3[38].x
    dp3 r8.w, r11.xyzx, r1.yzwy
    mov_sat r9.w, r8.w
    add r9.w, -|r8.w|, r9.w
    mad r8.w, r2.w, r9.w, |r8.w|
    mul r8.z, r8.z, r8.w
    mul r8.w, r6.w, r8.z
    mul r12.xyz, r8.wwww, cb3[22].xyzx
    mad r10.xyz, r12.xyzx, r2.xyzx, r10.xyzx
    mad r11.xyz, r3.xyzx, r0.zzzz, r11.xyzx
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    dp3_sat r8.w, r11.xyzx, r4.xyzx
    add r8.w, -r8.w, l(1.000000)
    mul r9.w, r8.w, r8.w
    mul r9.w, r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mad r8.w, cb12[0].x, r8.w, r5.w
    dp3_sat r9.w, r11.xyzx, r1.yzwy
    log r9.w, r9.w
    mul r9.w, r8.y, r9.w
    exp r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mul r8.z, r8.z, r8.w
    mul r6.w, r6.w, r8.z
    mul r6.w, r7.w, r6.w
    mad r9.xyz, r6.wwww, cb3[22].xyzx, r9.xyzx
  endif 
else 
  mov r4.w, l(-1)
endif 
if_z r4.w
  ige r6.w, l(4), cb3[2].x
  or r4.w, r4.w, r6.w
  if_z r4.w
    eq r6.w, cb3[23].w, l(0.000000)
    add r11.xyz, -v7.xyzx, cb3[7].xyzx
    add r12.xyz, v7.xyzx, -cb3[7].xyzx
    dp3 r8.z, r12.xyzx, cb3[15].xyzx
    div_sat r8.z, r8.z, cb3[23].w
    mul r8.z, r8.z, cb3[23].w
    mad r12.xyz, cb3[15].xyzx, r8.zzzz, cb3[7].xyzx
    add r12.xyz, r12.xyzx, -v7.xyzx
    movc r11.xyz, r6.wwww, r11.xyzx, r12.xyzx
    dp3 r6.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.z, r11.xyzx, r11.xyzx
    rsq r8.z, r8.z
    mul r11.xyz, r8.zzzz, r11.xyzx
    mad_sat r6.w, -r6.w, cb3[7].w, l(1.000000)
    add r8.z, -cb3[15].w, l(1.000000)
    mad r8.z, r8.z, r6.w, cb3[15].w
    div r6.w, r6.w, r8.z
    dp3 r8.z, r11.xyzx, -cb3[15].xyzx
    mad_sat r8.z, r8.z, cb3[31].x, cb3[39].x
    dp3 r8.w, r11.xyzx, r1.yzwy
    mov_sat r9.w, r8.w
    add r9.w, -|r8.w|, r9.w
    mad r8.w, r2.w, r9.w, |r8.w|
    mul r8.z, r8.z, r8.w
    mul r8.w, r6.w, r8.z
    mul r12.xyz, r8.wwww, cb3[23].xyzx
    mad r10.xyz, r12.xyzx, r2.xyzx, r10.xyzx
    mad r11.xyz, r3.xyzx, r0.zzzz, r11.xyzx
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    dp3_sat r8.w, r11.xyzx, r4.xyzx
    add r8.w, -r8.w, l(1.000000)
    mul r9.w, r8.w, r8.w
    mul r9.w, r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mad r8.w, cb12[0].x, r8.w, r5.w
    dp3_sat r9.w, r11.xyzx, r1.yzwy
    log r9.w, r9.w
    mul r9.w, r8.y, r9.w
    exp r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mul r8.z, r8.z, r8.w
    mul r6.w, r6.w, r8.z
    mul r6.w, r7.w, r6.w
    mad r9.xyz, r6.wwww, cb3[23].xyzx, r9.xyzx
  endif 
else 
  mov r4.w, l(-1)
endif 
if_z r4.w
  ige r6.w, l(5), cb3[2].x
  or r4.w, r4.w, r6.w
  if_z r4.w
    eq r6.w, cb3[24].w, l(0.000000)
    add r11.xyz, -v7.xyzx, cb3[8].xyzx
    add r12.xyz, v7.xyzx, -cb3[8].xyzx
    dp3 r8.z, r12.xyzx, cb3[16].xyzx
    div_sat r8.z, r8.z, cb3[24].w
    mul r8.z, r8.z, cb3[24].w
    mad r12.xyz, cb3[16].xyzx, r8.zzzz, cb3[8].xyzx
    add r12.xyz, r12.xyzx, -v7.xyzx
    movc r11.xyz, r6.wwww, r11.xyzx, r12.xyzx
    dp3 r6.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.z, r11.xyzx, r11.xyzx
    rsq r8.z, r8.z
    mul r11.xyz, r8.zzzz, r11.xyzx
    mad_sat r6.w, -r6.w, cb3[8].w, l(1.000000)
    add r8.z, -cb3[16].w, l(1.000000)
    mad r8.z, r8.z, r6.w, cb3[16].w
    div r6.w, r6.w, r8.z
    dp3 r8.z, r11.xyzx, -cb3[16].xyzx
    mad_sat r8.z, r8.z, cb3[32].x, cb3[40].x
    dp3 r8.w, r11.xyzx, r1.yzwy
    mov_sat r9.w, r8.w
    add r9.w, -|r8.w|, r9.w
    mad r8.w, r2.w, r9.w, |r8.w|
    mul r8.z, r8.z, r8.w
    mul r8.w, r6.w, r8.z
    mul r12.xyz, r8.wwww, cb3[24].xyzx
    mad r10.xyz, r12.xyzx, r2.xyzx, r10.xyzx
    mad r11.xyz, r3.xyzx, r0.zzzz, r11.xyzx
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    dp3_sat r8.w, r11.xyzx, r4.xyzx
    add r8.w, -r8.w, l(1.000000)
    mul r9.w, r8.w, r8.w
    mul r9.w, r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mad r8.w, cb12[0].x, r8.w, r5.w
    dp3_sat r9.w, r11.xyzx, r1.yzwy
    log r9.w, r9.w
    mul r9.w, r8.y, r9.w
    exp r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mul r8.z, r8.z, r8.w
    mul r6.w, r6.w, r8.z
    mul r6.w, r7.w, r6.w
    mad r9.xyz, r6.wwww, cb3[24].xyzx, r9.xyzx
  endif 
else 
  mov r4.w, l(-1)
endif 
if_z r4.w
  ige r6.w, l(6), cb3[2].x
  or r4.w, r4.w, r6.w
  if_z r4.w
    eq r6.w, cb3[25].w, l(0.000000)
    add r11.xyz, -v7.xyzx, cb3[9].xyzx
    add r12.xyz, v7.xyzx, -cb3[9].xyzx
    dp3 r8.z, r12.xyzx, cb3[17].xyzx
    div_sat r8.z, r8.z, cb3[25].w
    mul r8.z, r8.z, cb3[25].w
    mad r12.xyz, cb3[17].xyzx, r8.zzzz, cb3[9].xyzx
    add r12.xyz, r12.xyzx, -v7.xyzx
    movc r11.xyz, r6.wwww, r11.xyzx, r12.xyzx
    dp3 r6.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r8.z, r11.xyzx, r11.xyzx
    rsq r8.z, r8.z
    mul r11.xyz, r8.zzzz, r11.xyzx
    mad_sat r6.w, -r6.w, cb3[9].w, l(1.000000)
    add r8.z, -cb3[17].w, l(1.000000)
    mad r8.z, r8.z, r6.w, cb3[17].w
    div r6.w, r6.w, r8.z
    dp3 r8.z, r11.xyzx, -cb3[17].xyzx
    mad_sat r8.z, r8.z, cb3[33].x, cb3[41].x
    dp3 r8.w, r11.xyzx, r1.yzwy
    mov_sat r9.w, r8.w
    add r9.w, -|r8.w|, r9.w
    mad r8.w, r2.w, r9.w, |r8.w|
    mul r8.z, r8.z, r8.w
    mul r8.w, r6.w, r8.z
    mul r12.xyz, r8.wwww, cb3[25].xyzx
    mad r10.xyz, r12.xyzx, r2.xyzx, r10.xyzx
    mad r11.xyz, r3.xyzx, r0.zzzz, r11.xyzx
    dp3 r8.w, r11.xyzx, r11.xyzx
    rsq r8.w, r8.w
    mul r11.xyz, r8.wwww, r11.xyzx
    dp3_sat r8.w, r11.xyzx, r4.xyzx
    add r8.w, -r8.w, l(1.000000)
    mul r9.w, r8.w, r8.w
    mul r9.w, r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mad r8.w, cb12[0].x, r8.w, r5.w
    dp3_sat r9.w, r11.xyzx, r1.yzwy
    log r9.w, r9.w
    mul r9.w, r8.y, r9.w
    exp r9.w, r9.w
    mul r8.w, r8.w, r9.w
    mul r8.z, r8.z, r8.w
    mul r6.w, r6.w, r8.z
    mul r6.w, r7.w, r6.w
    mad r9.xyz, r6.wwww, cb3[25].xyzx, r9.xyzx
  endif 
else 
  mov r4.w, l(-1)
endif 
if_z r4.w
  ige r6.w, l(7), cb3[2].x
  or r4.w, r4.w, r6.w
  if_z r4.w
    eq r4.w, cb3[26].w, l(0.000000)
    add r11.xyz, -v7.xyzx, cb3[10].xyzx
    add r12.xyz, v7.xyzx, -cb3[10].xyzx
    dp3 r6.w, r12.xyzx, cb3[18].xyzx
    div_sat r6.w, r6.w, cb3[26].w
    mul r6.w, r6.w, cb3[26].w
    mad r12.xyz, cb3[18].xyzx, r6.wwww, cb3[10].xyzx
    add r12.xyz, r12.xyzx, -v7.xyzx
    movc r11.xyz, r4.wwww, r11.xyzx, r12.xyzx
    dp3 r4.w, r11.xyzx, r11.xyzx
    add r11.xyz, r11.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r6.w, r11.xyzx, r11.xyzx
    rsq r6.w, r6.w
    mul r11.xyz, r6.wwww, r11.xyzx
    mad_sat r4.w, -r4.w, cb3[10].w, l(1.000000)
    add r6.w, -cb3[18].w, l(1.000000)
    mad r6.w, r6.w, r4.w, cb3[18].w
    div r4.w, r4.w, r6.w
    dp3 r6.w, r11.xyzx, -cb3[18].xyzx
    mad_sat r6.w, r6.w, cb3[34].x, cb3[42].x
    dp3 r8.z, r11.xyzx, r1.yzwy
    mov_sat r8.w, r8.z
    add r8.w, -|r8.z|, r8.w
    mad r2.w, r2.w, r8.w, |r8.z|
    mul r2.w, r6.w, r2.w
    mul r6.w, r4.w, r2.w
    mul r12.xyz, r6.wwww, cb3[26].xyzx
    mad r10.xyz, r12.xyzx, r2.xyzx, r10.xyzx
    mad r3.xyz, r3.xyzx, r0.zzzz, r11.xyzx
    dp3 r0.z, r3.xyzx, r3.xyzx
    rsq r0.z, r0.z
    mul r3.xyz, r0.zzzz, r3.xyzx
    dp3_sat r0.z, r3.xyzx, r4.xyzx
    add r0.z, -r0.z, l(1.000000)
    mul r6.w, r0.z, r0.z
    mul r6.w, r6.w, r6.w
    mul r0.z, r0.z, r6.w
    mad r0.z, cb12[0].x, r0.z, r5.w
    dp3_sat r3.x, r3.xyzx, r1.yzwy
    log r3.x, r3.x
    mul r3.x, r3.x, r8.y
    exp r3.x, r3.x
    mul r0.z, r0.z, r3.x
    mul r0.z, r2.w, r0.z
    mul r0.z, r4.w, r0.z
    mul r0.z, r7.w, r0.z
    mad r9.xyz, r0.zzzz, cb3[26].xyzx, r9.xyzx
  endif 
endif 
mul r0.z, r6.z, r6.z
mul r0.y, r0.y, r0.y
mul r3.xyz, r9.xyzx, r0.yyyy
mad r3.xyz, r0.zzzz, r10.xyzx, r3.xyzx
mad r3.xyz, r5.xyzx, r3.wwww, r3.xyzx
mad r0.y, r0.w, r1.x, cb3[43].w
mul r0.y, r0.y, cb3[44].w
max r0.y, r0.y, l(0.000000)
mad r5.xyz, cb3[47].xyzx, r0.yyyy, cb3[48].xyzx
add r0.z, -cb2[12].z, l(1.000000)
mad r8.yzw, cb3[45].xxyz, r0.yyyy, cb3[46].xxyz
mul r8.yzw, r8.yyzw, cb2[12].zzzz
mad r5.xyz, r5.xyzx, r0.zzzz, r8.yzwy
mul r5.xyz, r6.yyyy, r5.xyzx
mad r0.yzw, cb3[43].xxyz, r0.yyyy, cb3[44].xxyz
mov r9.x, cb3[46].w
mov r9.y, cb3[47].w
mov r9.z, cb3[48].w
dp3_sat r1.x, r9.xyzx, r1.yzwy
mad r0.yzw, cb3[49].xxyz, r1.xxxx, r0.yyzw
mad r0.yzw, r0.yyzw, r6.xxxx, r5.xxyz
mul r0.yzw, r6.zzzz, r0.yyzw
mad r0.yzw, r0.yyzw, r2.xxyz, r3.xxyz
add r1.x, -r6.z, l(1.000000)
dp3 r2.x, -r4.xyzx, r1.yzwy
add r2.x, r2.x, r2.x
mad r1.yzw, r1.yyzw, -r2.xxxx, -r4.xxyz
mul_sat r2.xy, r0.xxxx, l(0.000667, 0.001776, 0.000000, 0.000000)
add r0.x, -r2.x, l(1.000000)
add r2.x, cb5[6].z, l(-5.000000)
mul r2.z, r0.x, cb5[6].z
lt r2.z, r2.z, r2.x
mad r2.w, r0.x, cb5[6].z, l(-5.000000)
mul r0.x, r0.x, r0.x
mad r0.x, r0.x, l(5.000000), r2.x
movc r0.x, r2.z, r2.w, r0.x
mul r2.xzw, r1.yyzy, l(-0.250000, 0.000000, 0.500000, 0.250000)
add r1.y, |r1.w|, l(1.000000)
div r2.xzw, r2.xxzw, r1.yyyy
add r2.xzw, -r2.xxzw, l(0.750000, 0.000000, 0.500000, 0.250000)
lt r1.y, l(0.000000), r1.w
movc r1.yz, r1.yyyy, r2.xxzx, r2.wwzw
sample_l r3.xyzw, r1.yzyy, t1.xyzw, s1, r0.x
max r0.x, r6.y, r6.x
mul r1.yzw, r0.xxxx, r3.xxyz
mul r2.xyz, r2.yyyy, r1.yzwy
mul r2.xyz, r2.xyzx, l(0.681690, 0.681690, 0.681690, 0.000000)
mad r1.yzw, r1.yyzw, l(0.000000, 0.318310, 0.318310, 0.318310), r2.xxyz
mad r0.xyz, r1.yzwy, r1.xxxx, r0.yzwy
mul r0.w, r8.x, cb2[11].x
if_nz cb5[7].x
  dp3 r1.x, r7.xyzx, r7.xyzx
  sqrt r1.y, r1.x
  add r1.z, r1.y, -cb3[50].x
  max r1.z, r1.z, l(0.000000)
  div r1.y, r1.z, r1.y
  mul r1.y, r1.y, r7.z
  mul r1.w, r1.y, cb3[52].z
  lt r1.y, l(0.010000), |r1.y|
  mul r2.x, r1.w, l(-1.442695)
  exp r2.x, r2.x
  add r2.x, -r2.x, l(1.000000)
  div r1.w, r2.x, r1.w
  movc r1.y, r1.y, r1.w, l(1.000000)
  mul r1.w, r1.z, cb3[51].w
  mul r1.y, r1.y, r1.w
  min r1.y, r1.y, l(1.000000)
  mul r1.y, r1.y, l(1.442695)
  exp r1.y, r1.y
  min r1.y, r1.y, l(1.000000)
  add r1.y, -r1.y, l(1.000000)
  mul r1.w, r1.y, cb3[52].y
  rsq r1.x, r1.x
  mul r2.xyz, r1.xxxx, r7.xyzx
  dp3_sat r1.x, r2.xyzx, cb3[54].xyzx
  log r1.x, r1.x
  mul r1.x, r1.x, cb3[54].w
  exp r1.x, r1.x
  dp3_sat r2.x, r2.xyzx, cb3[53].xyzx
  log r2.x, r2.x
  mul r2.x, r2.x, cb3[53].w
  exp r2.x, r2.x
  mad r1.y, -r1.y, cb3[52].y, l(1.000000)
  mul r1.y, r1.y, cb3[51].y
  add r2.y, r1.z, -cb3[52].x
  max r2.y, r2.y, l(0.000000)
  mul r2.y, r2.y, cb3[51].x
  mul r2.y, r2.y, l(1.442695)
  exp r2.y, r2.y
  add r2.y, -r2.y, l(1.000000)
  mad_sat r1.w, r1.y, r2.y, r1.w
  mul r1.z, r1.z, -cb3[51].z
  mul r1.z, r1.z, l(1.442695)
  exp r1.z, r1.z
  add r1.z, -r1.z, l(1.000000)
  add r2.yzw, -cb3[56].xxyz, cb3[58].xxyz
  mad r2.yzw, r1.xxxx, r2.yyzw, cb3[56].xxyz
  add r3.xyz, -r2.yzwy, cb3[55].xyzx
  mad r2.xyz, r2.xxxx, r3.xyzx, r2.yzwy
  add r2.xyz, r2.xyzx, -cb3[57].xyzx
  mad r2.xyz, r1.zzzz, r2.xyzx, cb3[57].xyzx
  mov r3.x, cb3[55].w
  mov r3.y, cb3[56].w
  mov r3.z, cb3[57].w
  add r3.xyz, -r2.xyzx, r3.xyzx
  mad r1.xyz, r1.yyyy, r3.xyzx, r2.xyzx
  lt r2.x, l(0.000000), cb2[18].y
  if_nz r2.x
    mul r2.xy, v9.xyxx, cb2[14].zwzz
    sample r2.xyzw, r2.xyxx, t11.xyzw, s11
    add r2.x, r2.x, l(-1.000000)
    mad_sat r2.x, cb2[18].y, r2.x, l(1.000000)
  else 
    mov r2.x, l(1.000000)
  endif 
  mad r1.xyz, r1.xyzx, r2.xxxx, -r0.xyzx
  mad r1.xyz, r1.wwww, r1.xyzx, r0.xyzx
else 
  dp3 r1.w, r7.xyzx, r7.xyzx
  sqrt r2.x, r1.w
  add r2.y, r2.x, -cb3[50].x
  max r2.y, r2.y, l(0.000000)
  div r2.x, r2.y, r2.x
  mul r2.x, r2.x, r7.z
  mul r2.z, r2.x, cb3[52].z
  lt r2.x, l(0.010000), |r2.x|
  mul r2.w, r2.z, l(-1.442695)
  exp r2.w, r2.w
  add r2.w, -r2.w, l(1.000000)
  div r2.z, r2.w, r2.z
  movc r2.x, r2.x, r2.z, l(1.000000)
  mul r2.z, r2.y, cb3[51].w
  mul r2.x, r2.x, r2.z
  min r2.x, r2.x, l(1.000000)
  mul r2.x, r2.x, l(1.442695)
  exp r2.x, r2.x
  min r2.x, r2.x, l(1.000000)
  add r2.x, -r2.x, l(1.000000)
  mul r2.z, r2.x, cb3[52].y
  rsq r1.w, r1.w
  mul r3.xyz, r1.wwww, r7.xyzx
  dp3_sat r1.w, r3.xyzx, cb3[54].xyzx
  log r1.w, r1.w
  mul r1.w, r1.w, cb3[54].w
  exp r1.w, r1.w
  dp3_sat r2.w, r3.xyzx, cb3[53].xyzx
  log r2.w, r2.w
  mul r2.w, r2.w, cb3[53].w
  exp r2.w, r2.w
  mad r2.x, -r2.x, cb3[52].y, l(1.000000)
  mul r2.x, r2.x, cb3[51].y
  add r3.x, r2.y, -cb3[52].x
  max r3.x, r3.x, l(0.000000)
  mul r3.x, r3.x, cb3[51].x
  mul r3.x, r3.x, l(1.442695)
  exp r3.x, r3.x
  add r3.x, -r3.x, l(1.000000)
  mad_sat r2.z, r2.x, r3.x, r2.z
  mul r2.y, r2.y, -cb3[51].z
  mul r2.y, r2.y, l(1.442695)
  exp r2.y, r2.y
  add r2.y, -r2.y, l(1.000000)
  add r3.xyz, -cb3[56].xyzx, cb3[58].xyzx
  mad r3.xyz, r1.wwww, r3.xyzx, cb3[56].xyzx
  add r4.xyz, -r3.xyzx, cb3[55].xyzx
  mad r3.xyz, r2.wwww, r4.xyzx, r3.xyzx
  add r3.xyz, r3.xyzx, -cb3[57].xyzx
  mad r3.xyz, r2.yyyy, r3.xyzx, cb3[57].xyzx
  mov r4.x, cb3[55].w
  mov r4.y, cb3[56].w
  mov r4.z, cb3[57].w
  add r4.xyz, -r3.xyzx, r4.xyzx
  mad r2.xyw, r2.xxxx, r4.xyxz, r3.xyxz
  add r2.xyw, -r0.xyxz, r2.xyxw
  mad r1.xyz, r2.zzzz, r2.xywx, r0.xyzx
endif 
mul o0.w, r0.w, v8.x
mul o0.xyz, r1.xyzx, cb2[13].zzzz
ret 
// Approximately 807 instruction slots used
