//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer hdao_locals
// {
//
//   float4 g_projParams;               // Offset:    0 Size:    16 [unused]
//   float4 g_projShear;                // Offset:   16 Size:    16 [unused]
//   float4 g_targetSize;               // Offset:   32 Size:    16 [unused]
//   float4 g_HDAOComputeParams;        // Offset:   48 Size:    16 [unused]
//   float4 g_HDAOApplyParams;          // Offset:   64 Size:    16
//   float4 g_HDAOValleyParams;         // Offset:   80 Size:    16 [unused]
//   float4 g_HDAOExtraParams;          // Offset:   96 Size:    16 [unused]
//   float4 g_OcclusionTextureParams;   // Offset:  112 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// occlusionSampler                  sampler      NA          NA             s4      1 
// occlusionTexture                  texture   float          2d             t4      1 
// hdao_locals                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB12[8], immediateIndexed
dcl_sampler s4, mode_default
dcl_resource_texture2d (float,float,float,float) t4
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_output o0.xyzw
dcl_temps 5
mul r0.xy, v0.xyxx, cb12[7].xyxx
sample_l r0.xyzw, r0.xyxx, t4.xyzw, s4, l(0.000000)
mul r0.yz, cb12[4].xxyx, cb12[7].xxyx
mul r1.xyzw, r0.yzyz, l(1.466301, 1.466301, 3.421895, 3.421895)
mad r2.xyzw, v0.xyxy, cb12[7].xyxy, r1.xyzw
mad r1.xyzw, v0.xyxy, cb12[7].xyxy, -r1.xyzw
sample_l r3.xyzw, r2.xyxx, t4.xyzw, s4, l(0.000000)
sample_l r2.xyzw, r2.zwzz, t4.xyzw, s4, l(0.000000)
sample_l r4.xyzw, r1.xyxx, t4.xyzw, s4, l(0.000000)
sample_l r1.xyzw, r1.zwzz, t4.xyzw, s4, l(0.000000)
add r0.w, r1.x, r2.x
add r1.x, r3.x, r4.x
mad r0.x, r1.x, l(1.791268), r0.x
mad r0.x, r0.w, l(1.153729), r0.x
mul r1.xyzw, r0.yzyz, l(5.378716, 5.378716, 7.337378, 7.337378)
mul r0.yz, r0.yyzy, l(0.000000, 9.298385, 9.298385, 0.000000)
mad r2.xyzw, v0.xyxy, cb12[7].xyxy, r1.xyzw
mad r1.xyzw, v0.xyxy, cb12[7].xyxy, -r1.xyzw
sample_l r3.xyzw, r2.xyxx, t4.xyzw, s4, l(0.000000)
sample_l r2.xyzw, r2.zwzz, t4.xyzw, s4, l(0.000000)
sample_l r4.xyzw, r1.xyxx, t4.xyzw, s4, l(0.000000)
sample_l r1.xyzw, r1.zwzz, t4.xyzw, s4, l(0.000000)
add r0.w, r1.x, r2.x
add r1.x, r3.x, r4.x
mad r0.x, r1.x, l(0.522551), r0.x
mad r0.x, r0.w, l(0.166385), r0.x
mad r1.xy, v0.xyxx, cb12[7].xyxx, r0.yzyy
mad r0.yz, v0.xxyx, cb12[7].xxyx, -r0.yyzy
sample_l r2.xyzw, r0.yzyy, t4.xyzw, s4, l(0.000000)
sample_l r1.xyzw, r1.xyxx, t4.xyzw, s4, l(0.000000)
add r0.y, r2.x, r1.x
mad r0.x, r0.y, l(0.037230), r0.x
mul o0.xyzw, r0.xxxx, l(0.119871, 0.119871, 0.119871, 0.119871)
ret 
// Approximately 34 instruction slots used
