//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer im_cbuffer
// {
//
//   float4 TexelSize;                  // Offset:    0 Size:    16 [unused]
//   float4 refMipBlurParams;           // Offset:   16 Size:    16
//   float4 GeneralParams0;             // Offset:   32 Size:    16 [unused]
//   float4 GeneralParams1;             // Offset:   48 Size:    16 [unused]
//   float g_fBilateralCoefficient;     // Offset:   64 Size:     4 [unused]
//   float g_fBilateralEdgeThreshold;   // Offset:   68 Size:     4 [unused]
//   float DistantCarAlpha;             // Offset:   72 Size:     4 [unused]
//   float4 tonemapColorFilterParams0;  // Offset:   80 Size:    16 [unused]
//   float4 tonemapColorFilterParams1;  // Offset:   96 Size:    16 [unused]
//   float4 RenderTexMSAAParam;         // Offset:  112 Size:    16 [unused]
//   float4 RenderPointMapINTParam;     // Offset:  128 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// RenderTexArraySampler             sampler      NA          NA             s7      1 
// RenderTexArray                    texture  float4     2darray             t7      1 
// im_cbuffer                        cbuffer      NA          NA            cb5      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyzw        1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB5[2], immediateIndexed
dcl_sampler s7, mode_default
dcl_resource_texture2darray (float,float,float,float) t7
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 1
mov r0.xy, v1.xyxx
mov r0.z, cb5[1].y
sample_l o0.xyzw, r0.xyzx, t7.xyzw, s7, cb5[1].x
ret 
// Approximately 4 instruction slots used
