//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer MLAA_locals
// {
//
//   float4 g_vTexelSize;               // Offset:    0 Size:    16
//   float g_fLuminanceThreshold;       // Offset:   16 Size:     4 [unused]
//   float4 g_vRelativeLuminanceThresholdParams;// Offset:   32 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// MLAAPointSampler                  sampler      NA          NA             s2      1 
// MLAAPointSampler                  texture  float4          2d             t2      1 
// MLAA_locals                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB12[1], immediateIndexed
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 4
sample r0.xyzw, v1.xyxx, t2.xyzw, s2
mad r1.xyzw, cb12[0].xyxy, l(-1.000000, 0.000000, 1.000000, 0.000000), v1.xyxy
sample r2.xyzw, r1.xyxx, t2.xyzw, s2
sample r1.xyzw, r1.zwzz, t2.xyzw, s2
mov r2.z, r1.x
mad r1.xyzw, cb12[0].xyxy, l(0.000000, -1.000000, 0.000000, 1.000000), v1.xyxy
sample r3.xyzw, r1.xyxx, t2.xyzw, s2
sample r1.xyzw, r1.zwzz, t2.xyzw, s2
mov r2.w, r1.x
mov r2.y, r3.x
add r0.xyzw, r0.xxxx, -r2.xyzw
ge r0.xyzw, |r0.xyzw|, l(0.001000, 0.001000, 0.001000, 0.001000)
and r0.xyzw, r0.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
dp4 r1.x, r0.xyzw, r0.xyzw
mov o0.xyzw, r0.xyzw
ne r0.x, r1.x, l(0.000000)
ieq r0.x, r0.x, l(0)
discard_nz r0.x
ret 
// Approximately 19 instruction slots used
