//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer MLAA_locals
// {
//
//   float4 g_vTexelSize;               // Offset:    0 Size:    16
//   float g_fLuminanceThreshold;       // Offset:   16 Size:     4 [unused]
//   float4 g_vRelativeLuminanceThresholdParams;// Offset:   32 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// MLAAPointSampler                  sampler      NA          NA             s2      1 
// MLAALinearSampler                 sampler      NA          NA             s3      1 
// MLAAAreaLUTSampler                sampler      NA          NA             s4      1 
// MLAAPointSampler                  texture  float4          2d             t2      1 
// MLAALinearSampler                 texture  float4          2d             t3      1 
// MLAAAreaLUTSampler                texture  float4          2d             t4      1 
// MLAA_locals                       cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB12[1], immediateIndexed
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 4
sample r0.xyzw, v1.xyxx, t2.xyzw, s2
ne r0.xy, l(0.000000, 0.000000, 0.000000, 0.000000), r0.yxyy
if_nz r0.x
  mad r0.xz, -cb12[0].xxyx, l(1.500000, 0.000000, 0.000000, 0.000000), v1.xxyx
  mov r1.xy, r0.xzxx
  mov r0.w, l(0)
  mov r1.z, l(0)
  loop 
    ige r1.w, r1.z, l(32)
    breakc_nz r1.w
    sample_l r2.xyzw, r1.xyxx, t3.xyzw, s3, l(0.000000)
    lt r1.w, r2.y, l(0.900000)
    if_nz r1.w
      mov r0.w, r2.y
      break 
    endif 
    mad r1.xy, -cb12[0].xyxx, l(2.000000, 0.000000, 0.000000, 0.000000), r1.xyxx
    iadd r1.z, r1.z, l(1)
    mov r0.w, r2.y
  endloop 
  itof r0.x, r1.z
  add r0.z, r0.w, r0.w
  mad r0.x, r0.x, l(-2.000000), -r0.z
  max r1.x, r0.x, l(-64.000000)
  mad r0.xz, cb12[0].xxyx, l(1.500000, 0.000000, 0.000000, 0.000000), v1.xxyx
  mov r2.xy, r0.xzxx
  mov r0.w, l(0)
  mov r2.z, l(0)
  loop 
    ige r2.w, r2.z, l(32)
    breakc_nz r2.w
    sample_l r3.xyzw, r2.xyxx, t3.xyzw, s3, l(0.000000)
    lt r2.w, r3.y, l(0.900000)
    if_nz r2.w
      mov r0.w, r3.y
      break 
    endif 
    mad r2.xy, cb12[0].xyxx, l(2.000000, 0.000000, 0.000000, 0.000000), r2.xyxx
    iadd r2.z, r2.z, l(1)
    mov r0.w, r3.y
  endloop 
  itof r0.x, r2.z
  add r0.z, r0.w, r0.w
  mad r0.x, r0.x, l(2.000000), r0.z
  min r1.w, r0.x, l(64.000000)
  add r1.y, r1.w, l(1.000000)
  mov r1.z, l(-0.250000)
  mad r0.xzw, r1.xxzy, cb12[0].xxyx, v1.xxyx
  sample_l r2.xyzw, r0.xzxx, t3.xyzw, s3, l(0.000000)
  sample_l r3.xyzw, r0.wzww, t3.yxzw, s3, l(0.000000)
  mov r3.x, r2.x
  mul r0.xz, r3.xxyx, l(4.000000, 0.000000, 4.000000, 0.000000)
  round_ne r0.xz, r0.xxzx
  mad r0.xz, r0.xxzx, l(32.000000, 0.000000, 32.000000, 0.000000), |r1.xxwx|
  mul r0.xz, r0.xxzx, l(0.006289, 0.000000, 0.006289, 0.000000)
  sample_l r1.xyzw, r0.xzxx, t4.xyzw, s4, l(0.000000)
  mov o0.xy, r1.xyxx
else 
  mov o0.xy, l(0,0,0,0)
endif 
if_nz r0.y
  mad r0.xy, -cb12[0].xyxx, l(0.000000, 1.500000, 0.000000, 0.000000), v1.xyxx
  mov r0.zw, r0.xxxy
  mov r1.xy, l(0,0,0,0)
  loop 
    ige r1.z, r1.y, l(32)
    breakc_nz r1.z
    sample_l r2.xyzw, r0.zwzz, t3.xyzw, s3, l(0.000000)
    lt r1.z, r2.x, l(0.900000)
    if_nz r1.z
      mov r1.x, r2.x
      break 
    endif 
    mad r0.zw, -cb12[0].xxxy, l(0.000000, 0.000000, 0.000000, 2.000000), r0.zzzw
    iadd r1.y, r1.y, l(1)
    mov r1.x, r2.x
  endloop 
  itof r0.x, r1.y
  add r0.y, r1.x, r1.x
  mad r0.x, r0.x, l(-2.000000), -r0.y
  max r0.x, r0.x, l(-64.000000)
  mad r1.xy, cb12[0].xyxx, l(0.000000, 1.500000, 0.000000, 0.000000), v1.xyxx
  mov r1.zw, r1.xxxy
  mov r2.xy, l(0,0,0,0)
  loop 
    ige r2.z, r2.y, l(32)
    breakc_nz r2.z
    sample_l r3.xyzw, r1.zwzz, t3.xyzw, s3, l(0.000000)
    lt r2.z, r3.x, l(0.900000)
    if_nz r2.z
      mov r2.x, r3.x
      break 
    endif 
    mad r1.zw, cb12[0].xxxy, l(0.000000, 0.000000, 0.000000, 2.000000), r1.zzzw
    iadd r2.y, r2.y, l(1)
    mov r2.x, r3.x
  endloop 
  itof r1.x, r2.y
  add r1.y, r2.x, r2.x
  mad r1.x, r1.x, l(2.000000), r1.y
  min r0.w, r1.x, l(64.000000)
  add r0.y, r0.w, l(1.000000)
  mov r0.z, l(-0.250000)
  mad r1.xyz, r0.zxyz, cb12[0].xyyx, v1.xyyx
  sample_l r2.xyzw, r1.xyxx, t3.xyzw, s3, l(0.000000)
  sample_l r1.xyzw, r1.xzxx, t3.xyzw, s3, l(0.000000)
  mov r1.x, r2.y
  mul r0.yz, r1.xxyx, l(0.000000, 4.000000, 4.000000, 0.000000)
  round_ne r0.yz, r0.yyzy
  mad r0.xy, r0.yzyy, l(32.000000, 32.000000, 0.000000, 0.000000), |r0.xwxx|
  mul r0.xy, r0.xyxx, l(0.006289, 0.006289, 0.000000, 0.000000)
  sample_l r0.xyzw, r0.xyxx, t4.xyzw, s4, l(0.000000)
  mov o0.zw, r0.xxxy
else 
  mov o0.zw, l(0,0,0,0)
endif 
ret 
// Approximately 117 instruction slots used
