//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16
//   float4 globalScreenSize;           // Offset:  224 Size:    16
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16
//   float4 gDirectionalColour;         // Offset:   16 Size:    16
//   int gNumForwardLights;             // Offset:   32 Size:     4 [unused]
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128 [unused]
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128 [unused]
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128 [unused]
//   float gLightConeScale[8];          // Offset:  432 Size:   116 [unused]
//   float gLightConeOffset[8];         // Offset:  560 Size:   116 [unused]
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80
//   float4 globalFogColor;             // Offset:  880 Size:    16
//   float4 globalFogColorE;            // Offset:  896 Size:    16
//   float4 globalFogColorN;            // Offset:  912 Size:    16
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer more_stuff
// {
//
//   float4 gEntitySelectColor[2];      // Offset:    0 Size:    32 [unused]
//   float4 gAmbientOcclusionEffect;    // Offset:   32 Size:    16 [unused]
//   float4 gDynamicBakesAndWetness;    // Offset:   48 Size:    16 [unused]
//   float4 gAlphaRefVec0;              // Offset:   64 Size:    16 [unused]
//   float4 gAlphaRefVec1;              // Offset:   80 Size:    16 [unused]
//   float gAlphaTestRef;               // Offset:   96 Size:     4 [unused]
//   bool gTreesUseDiscard;             // Offset:  100 Size:     4 [unused]
//   float gReflectionMipCount;         // Offset:  104 Size:     4
//   bool gUseTransparencyAA;           // Offset:  108 Size:     4 [unused]
//   bool gUseFogRay;                   // Offset:  112 Size:     4
//
// }
//
// cbuffer megashader_locals
// {
//
//   float tessellationMultiplier;      // Offset:    0 Size:     4 [unused]
//   float specularFresnel;             // Offset:    4 Size:     4
//   float specularFalloffMult;         // Offset:    8 Size:     4
//   float specularIntensityMult;       // Offset:   12 Size:     4
//   float3 specMapIntMask;             // Offset:   16 Size:    12
//   float bumpiness;                   // Offset:   28 Size:     4
//   float heightScale;                 // Offset:   32 Size:     4 [unused]
//   float heightBias;                  // Offset:   36 Size:     4 [unused]
//   float wetnessMultiplier;           // Offset:   40 Size:     4 [unused]
//   float useTessellation;             // Offset:   44 Size:     4 [unused]
//   float HardAlphaBlend;              // Offset:   48 Size:     4 [unused]
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16
//   float4 gCSMResolution;             // Offset:  224 Size:    16
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// ReflectionSampler                 sampler      NA          NA             s1      1 
// BumpSampler                       sampler      NA          NA             s3      1 
// SpecSampler                       sampler      NA          NA             s4      1 
// FogRaySampler                     sampler      NA          NA            s11      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// ReflectionSampler                 texture  float4          2d             t1      1 
// BumpSampler                       texture  float4          2d             t3      1 
// SpecSampler                       texture  float4          2d             t4      1 
// FogRaySampler                     texture  float4          2d            t11      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// more_stuff                        cbuffer      NA          NA            cb5      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// megashader_locals                 cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xy w
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                10     z         1     NONE   float     z 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 3   xyz         3     NONE   float       
// TEXCOORD                 4   xyz         4     NONE   float   xyz 
// TEXCOORD                 5   xyz         5     NONE   float   xyz 
// TEXCOORD                 6   xyzw        6     NONE   float   xyz 
// SV_Position              0   xyzw        7      POS   float   xy  
// SV_ClipDistance          0   xyzw        8  CLIPDST   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   x           1   TARGET   float   x   
// SV_Target                2   x           2   TARGET   float   x   
//
ps_4_0
dcl_constantbuffer CB1[16], immediateIndexed
dcl_constantbuffer CB2[19], immediateIndexed
dcl_constantbuffer CB3[59], immediateIndexed
dcl_constantbuffer CB5[8], immediateIndexed
dcl_constantbuffer CB12[2], immediateIndexed
dcl_constantbuffer CB6[15], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s11, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v0.xyw
dcl_input_ps linear v1.xy
dcl_input_ps linear v1.z
dcl_input_ps linear v2.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyz
dcl_input_ps_siv linear noperspective v7.xy, position
dcl_output o0.xyzw
dcl_output o1.x
dcl_output o2.x
dcl_temps 25
dcl_indexableTemp x0[4], 4
sample r0.xyzw, v1.xyxx, t0.xyzw, s0
sample r1.xyzw, v1.xyxx, t3.xyzw, s3
mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r1.z, r1.xyxx, r1.xyxx
add r1.z, -r1.z, l(1.000000)
sqrt r1.z, |r1.z|
max r1.w, cb12[1].w, l(0.001000)
mul r1.xy, r1.wwww, r1.xyxx
mul r2.xyz, r1.yyyy, v5.xyzx
mad r1.xyw, r1.xxxx, v4.xyxz, r2.xyxz
mad r1.xyz, r1.zzzz, v2.xyzx, r1.xywx
dp3 r1.w, r1.xyzx, r1.xyzx
rsq r1.w, r1.w
mul r2.xyz, r1.wwww, r1.xyzx
sample r3.xyzw, v1.xyxx, t4.xyzw, s4
mul r3.xy, r3.xyxx, r3.xyxx
dp3 r1.x, r3.xyzx, cb12[1].xyzx
mul_sat r1.x, r1.x, cb12[0].w
mul r0.w, r0.w, v0.w
mul r3.xy, v0.xyxx, cb2[11].zyzz
mul r0.xyz, r0.xyzx, r0.xyzx
add r4.xyz, -v6.xyzx, cb1[15].xyzx
dp3 r1.y, r4.xyzx, r4.xyzx
rsq r1.y, r1.y
mul r5.xyz, r1.yyyy, r4.xyzx
mad r6.xyz, r4.xyzx, r1.yyyy, -cb3[0].xyzx
dp3 r1.y, r6.xyzx, r6.xyzx
rsq r1.y, r1.y
mul r6.xyz, r1.yyyy, r6.xyzx
mul r3.xy, r3.xyxx, r3.xyxx
mad r1.y, r3.w, cb12[0].z, l(-500.000000)
max r1.y, r1.y, l(0.000000)
mad r2.w, r3.w, cb12[0].z, -r1.y
mul r1.y, r1.y, l(558.000000)
mad r1.y, r2.w, l(3.000000), r1.y
dp3 r2.w, r4.xyzx, cb1[14].xyzx
add r4.xyz, v6.xyzx, -cb1[15].xyzx
mul r7.xyz, r4.yyyy, cb6[1].xyzx
mad r7.xyz, r4.xxxx, cb6[0].xyzx, r7.xyzx
mad r7.xyz, r4.zzzz, cb6[2].xyzx, r7.xyzx
mad r8.xyz, r7.xyzx, cb6[4].xyzx, cb6[8].xyzx
mov x0[0].xyz, r8.xyzx
mad r9.xyz, r7.xyzx, cb6[5].xyzx, cb6[9].xyzx
mov x0[1].xyz, r9.xyzx
mad r10.xyz, r7.xyzx, cb6[6].xyzx, cb6[10].xyzx
mov x0[2].xyz, r10.xyzx
mad r7.xyz, r7.xyzx, cb6[7].xyzx, cb6[11].xyzx
mov x0[3].xyz, r7.xyzx
mul r11.yw, cb6[14].zzzw, l(0.000000, -0.346097, 0.000000, 0.328490)
mad r3.z, -cb6[14].z, l(1.500000), l(1.000000)
mul r3.z, r3.z, l(0.500000)
max r3.w, |r10.y|, |r10.x|
lt r3.w, r3.w, r3.z
movc r3.w, r3.w, l(2), l(3)
max r4.w, |r9.y|, |r9.x|
lt r4.w, r4.w, r3.z
movc r3.w, r4.w, l(1), r3.w
max r4.w, |r8.y|, |r8.x|
lt r3.z, r4.w, r3.z
movc r3.z, r3.z, l(0), r3.w
mov r8.xyz, x0[r3.z + 0].xyzx
itof r3.z, r3.z
add r3.w, r3.z, l(0.500000)
mul r3.w, r3.w, l(0.250000)
eq r9.xyzw, l(0.000000, 1.000000, 2.000000, 3.000000), r3.zzzz
and r9.xyzw, r9.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
dp4 r3.z, r9.xyzw, cb6[12].xyzw
dp4 r4.w, r9.xyzw, cb6[13].xyzw
add r9.x, r8.x, l(0.500000)
mad r9.y, r8.y, l(0.250000), r3.w
ne r3.w, r3.z, l(0.000000)
add r3.z, -r3.z, r8.z
deriv_rtx r10.xyw, r9.xyxy
deriv_rtx r10.z, r3.z
deriv_rty r12.xyz, r9.yxyy
deriv_rty r12.w, r3.z
mul r7.zw, r10.yyyw, r12.yyyw
mad r13.xy, r10.xzxx, r12.xzxx, -r7.zwzz
div r5.w, l(1.000000, 1.000000, 1.000000, 1.000000), r13.x
mul r6.w, r10.z, r12.y
mad r13.z, r10.x, r12.w, -r6.w
mul r7.zw, r5.wwww, r13.yyyz
max r7.zw, r7.zzzw, l(0.000000, 0.000000, 0.000000, 0.000000)
min r7.zw, r7.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
mad r3.z, -r4.w, r7.z, r3.z
mad r3.z, -r4.w, r7.w, r3.z
movc r11.z, r3.w, r3.z, r8.z
mov r9.z, l(0)
add r8.xyz, r9.xyzx, r11.ywzy
mul r11.xy, cb6[14].zwzz, l(-0.799291, 0.201741, 0.000000, 0.000000)
add r10.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.031176, 0.179338, 0.000000, 0.000000)
add r12.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(0.514749, 0.253502, 0.000000, 0.000000)
add r13.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.072870, 0.008097, 0.000000, 0.000000)
add r14.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.969781, 0.034522, 0.000000, 0.000000)
add r15.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(0.545547, 0.024129, 0.000000, 0.000000)
add r16.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.028906, -0.136785, 0.000000, 0.000000)
add r17.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.479511, -0.244833, 0.000000, 0.000000)
add r18.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(0.758788, -0.112109, 0.000000, 0.000000)
add r19.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(0.339353, -0.249328, 0.000000, 0.000000)
add r20.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(1.070598, 0.208123, 0.000000, 0.000000)
add r21.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(1.294038, -0.018078, 0.000000, 0.000000)
add r22.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-0.747563, -0.113974, 0.000000, 0.000000)
add r23.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(0.947722, -0.248764, 0.000000, 0.000000)
add r24.xyz, r9.xyzx, r11.xyzx
mul r11.xy, cb6[14].zwzz, l(-1.343153, -0.088584, 0.000000, 0.000000)
add r9.xyz, r9.xyzx, r11.xyzx
sample_c_lz r8.x, r8.xyxx, t15.xxxx, s15, r8.z
sample_c_lz r8.y, r10.xyxx, t15.xxxx, s15, r10.z
sample_c_lz r8.z, r12.xyxx, t15.xxxx, s15, r12.z
sample_c_lz r8.w, r13.xyxx, t15.xxxx, s15, r13.z
sample_c_lz r10.x, r14.xyxx, t15.xxxx, s15, r14.z
sample_c_lz r10.y, r15.xyxx, t15.xxxx, s15, r15.z
sample_c_lz r10.z, r16.xyxx, t15.xxxx, s15, r16.z
sample_c_lz r10.w, r17.xyxx, t15.xxxx, s15, r17.z
sample_c_lz r11.x, r18.xyxx, t15.xxxx, s15, r18.z
sample_c_lz r11.y, r19.xyxx, t15.xxxx, s15, r19.z
sample_c_lz r11.z, r20.xyxx, t15.xxxx, s15, r20.z
sample_c_lz r11.w, r21.xyxx, t15.xxxx, s15, r21.z
sample_c_lz r12.x, r22.xyxx, t15.xxxx, s15, r22.z
sample_c_lz r12.y, r23.xyxx, t15.xxxx, s15, r23.z
sample_c_lz r12.z, r24.xyxx, t15.xxxx, s15, r24.z
sample_c_lz r12.w, r9.xyxx, t15.xxxx, s15, r9.z
add r8.xyzw, r8.xyzw, r10.xyzw
add r8.xyzw, r11.xyzw, r8.xyzw
add r8.xyzw, r12.xyzw, r8.xyzw
dp4 r3.z, r8.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mad_sat r2.w, r2.w, cb6[0].w, cb6[1].w
max r3.w, |r7.y|, |r7.x|
mad_sat r3.w, r3.w, l(15.000000), l(-6.300000)
add r2.w, -r2.w, l(1.000000)
mul r2.w, r3.w, r2.w
mad r2.w, r3.z, l(0.062500), r2.w
mul r2.w, r2.w, r2.w
min r2.w, r2.w, l(1.000000)
mad_sat r3.z, v6.z, cb6[3].x, cb6[3].y
sqrt r3.z, r3.z
mul r3.z, r3.z, cb6[3].z
mad r2.w, r3.z, -r2.w, r2.w
dp3_sat r3.z, r2.xyzx, -cb3[0].xyzx
dp3_sat r7.x, r5.xyzx, r2.xyzx
dp3_sat r7.y, r6.xyzx, -cb3[0].xyzx
add r7.xy, -r7.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r7.zw, r7.xxxy, r7.xxxy
mul r7.zw, r7.zzzw, r7.zzzw
mul r7.xy, r7.xyxx, r7.zwzz
add r3.w, -cb12[0].y, l(1.000000)
mad r7.xy, cb12[0].yyyy, r7.xyxx, r3.wwww
add r7.zw, r1.yyyy, l(0.000000, 0.000000, 2.000000, 0.000000)
mul r3.w, r7.z, l(0.125000)
mad r4.w, -r1.x, r7.x, l(1.000000)
dp3 r5.w, r2.xyzx, r6.xyzx
add_sat r5.w, r5.w, l(0.000000)
log r5.w, r5.w
mul r5.w, r5.w, r7.w
exp r5.w, r5.w
mul r5.w, r7.y, r5.w
mul r3.w, r3.w, r5.w
mul r1.x, r1.x, r3.w
mul r1.x, r3.z, r1.x
mul r3.z, r3.z, r4.w
mad r6.xyz, r0.xyzx, r3.zzzz, r1.xxxx
mul r6.xyz, r6.xyzx, cb3[1].xyzx
mad r1.x, r1.z, r1.w, cb3[43].w
mul r1.x, r1.x, cb3[44].w
max r1.x, r1.x, l(0.000000)
mad r7.xyz, cb3[47].xyzx, r1.xxxx, cb3[48].xyzx
add r1.z, -cb2[12].z, l(1.000000)
mad r8.xyz, cb3[45].xyzx, r1.xxxx, cb3[46].xyzx
mul r8.xyz, r8.xyzx, cb2[12].zzzz
mad r7.xyz, r7.xyzx, r1.zzzz, r8.xyzx
mul r7.xyz, r3.yyyy, r7.xyzx
mad r1.xzw, cb3[43].xxyz, r1.xxxx, cb3[44].xxyz
mov r8.x, cb3[46].w
mov r8.y, cb3[47].w
mov r8.z, cb3[48].w
dp3_sat r3.z, r8.xyzx, r2.xyzx
mad r1.xzw, cb3[49].xxyz, r3.zzzz, r1.xxzw
mad r1.xzw, r1.xxzw, r3.xxxx, r7.xxyz
mul r1.xzw, r4.wwww, r1.xxzw
mul r0.xyz, r0.xyzx, r1.xzwx
mad r0.xyz, r6.xyzx, r2.wwww, r0.xyzx
add r1.x, -r4.w, l(1.000000)
dp3 r1.z, -r5.xyzx, r2.xyzx
add r1.z, r1.z, r1.z
mad r2.xyz, r2.xyzx, -r1.zzzz, -r5.xyzx
mul_sat r1.yz, r1.yyyy, l(0.000000, 0.000667, 0.001776, 0.000000)
add r1.y, -r1.y, l(1.000000)
add r1.w, cb5[6].z, l(-5.000000)
mul r2.w, r1.y, cb5[6].z
lt r2.w, r2.w, r1.w
mad r3.z, r1.y, cb5[6].z, l(-5.000000)
mul r1.y, r1.y, r1.y
mad r1.y, r1.y, l(5.000000), r1.w
movc r1.y, r2.w, r3.z, r1.y
mul r2.xyw, r2.xyxx, l(-0.250000, 0.500000, 0.000000, 0.250000)
add r1.w, |r2.z|, l(1.000000)
div r2.xyw, r2.xyxw, r1.wwww
add r2.xyw, -r2.xyxw, l(0.750000, 0.500000, 0.000000, 0.250000)
lt r1.w, l(0.000000), r2.z
movc r2.xy, r1.wwww, r2.xyxx, r2.wyww
sample_l r2.xyzw, r2.xyxx, t1.xyzw, s1, r1.y
max r1.y, r3.y, r3.x
mul r2.xyz, r1.yyyy, r2.xyzx
mul r1.yzw, r1.zzzz, r2.xxyz
mul r1.yzw, r1.yyzw, l(0.000000, 0.681690, 0.681690, 0.681690)
mad r1.yzw, r2.xxyz, l(0.000000, 0.318310, 0.318310, 0.318310), r1.yyzw
mad r0.xyz, r1.yzwy, r1.xxxx, r0.xyzx
mul r0.w, r0.w, cb2[11].x
if_nz cb5[7].x
  dp3 r1.x, r4.xyzx, r4.xyzx
  sqrt r1.y, r1.x
  add r1.z, r1.y, -cb3[50].x
  max r1.z, r1.z, l(0.000000)
  div r1.y, r1.z, r1.y
  mul r1.y, r1.y, r4.z
  mul r1.w, r1.y, cb3[52].z
  lt r1.y, l(0.010000), |r1.y|
  mul r2.x, r1.w, l(-1.442695)
  exp r2.x, r2.x
  add r2.x, -r2.x, l(1.000000)
  div r1.w, r2.x, r1.w
  movc r1.y, r1.y, r1.w, l(1.000000)
  mul r1.w, r1.z, cb3[51].w
  mul r1.y, r1.y, r1.w
  min r1.y, r1.y, l(1.000000)
  mul r1.y, r1.y, l(1.442695)
  exp r1.y, r1.y
  min r1.y, r1.y, l(1.000000)
  add r1.y, -r1.y, l(1.000000)
  mul r1.w, r1.y, cb3[52].y
  rsq r1.x, r1.x
  mul r2.xyz, r1.xxxx, r4.xyzx
  dp3_sat r1.x, r2.xyzx, cb3[54].xyzx
  log r1.x, r1.x
  mul r1.x, r1.x, cb3[54].w
  exp r1.x, r1.x
  dp3_sat r2.x, r2.xyzx, cb3[53].xyzx
  log r2.x, r2.x
  mul r2.x, r2.x, cb3[53].w
  exp r2.x, r2.x
  mad r1.y, -r1.y, cb3[52].y, l(1.000000)
  mul r1.y, r1.y, cb3[51].y
  add r2.y, r1.z, -cb3[52].x
  max r2.y, r2.y, l(0.000000)
  mul r2.y, r2.y, cb3[51].x
  mul r2.y, r2.y, l(1.442695)
  exp r2.y, r2.y
  add r2.y, -r2.y, l(1.000000)
  mad_sat r1.w, r1.y, r2.y, r1.w
  mul r1.z, r1.z, -cb3[51].z
  mul r1.z, r1.z, l(1.442695)
  exp r1.z, r1.z
  add r1.z, -r1.z, l(1.000000)
  add r2.yzw, -cb3[56].xxyz, cb3[58].xxyz
  mad r2.yzw, r1.xxxx, r2.yyzw, cb3[56].xxyz
  add r3.xyz, -r2.yzwy, cb3[55].xyzx
  mad r2.xyz, r2.xxxx, r3.xyzx, r2.yzwy
  add r2.xyz, r2.xyzx, -cb3[57].xyzx
  mad r2.xyz, r1.zzzz, r2.xyzx, cb3[57].xyzx
  mov r3.x, cb3[55].w
  mov r3.y, cb3[56].w
  mov r3.z, cb3[57].w
  add r3.xyz, -r2.xyzx, r3.xyzx
  mad r1.xyz, r1.yyyy, r3.xyzx, r2.xyzx
  lt r2.x, l(0.000000), cb2[18].y
  if_nz r2.x
    mul r2.xy, v7.xyxx, cb2[14].zwzz
    sample r2.xyzw, r2.xyxx, t11.xyzw, s11
    add r2.x, r2.x, l(-1.000000)
    mad_sat r2.x, cb2[18].y, r2.x, l(1.000000)
  else 
    mov r2.x, l(1.000000)
  endif 
  mad r1.xyz, r1.xyzx, r2.xxxx, -r0.xyzx
  mad r1.xyz, r1.wwww, r1.xyzx, r0.xyzx
else 
  dp3 r1.w, r4.xyzx, r4.xyzx
  sqrt r2.x, r1.w
  add r2.y, r2.x, -cb3[50].x
  max r2.y, r2.y, l(0.000000)
  div r2.x, r2.y, r2.x
  mul r2.x, r2.x, r4.z
  mul r2.z, r2.x, cb3[52].z
  lt r2.x, l(0.010000), |r2.x|
  mul r2.w, r2.z, l(-1.442695)
  exp r2.w, r2.w
  add r2.w, -r2.w, l(1.000000)
  div r2.z, r2.w, r2.z
  movc r2.x, r2.x, r2.z, l(1.000000)
  mul r2.z, r2.y, cb3[51].w
  mul r2.x, r2.x, r2.z
  min r2.x, r2.x, l(1.000000)
  mul r2.x, r2.x, l(1.442695)
  exp r2.x, r2.x
  min r2.x, r2.x, l(1.000000)
  add r2.x, -r2.x, l(1.000000)
  mul r2.z, r2.x, cb3[52].y
  rsq r1.w, r1.w
  mul r3.xyz, r1.wwww, r4.xyzx
  dp3_sat r1.w, r3.xyzx, cb3[54].xyzx
  log r1.w, r1.w
  mul r1.w, r1.w, cb3[54].w
  exp r1.w, r1.w
  dp3_sat r2.w, r3.xyzx, cb3[53].xyzx
  log r2.w, r2.w
  mul r2.w, r2.w, cb3[53].w
  exp r2.w, r2.w
  mad r2.x, -r2.x, cb3[52].y, l(1.000000)
  mul r2.x, r2.x, cb3[51].y
  add r3.x, r2.y, -cb3[52].x
  max r3.x, r3.x, l(0.000000)
  mul r3.x, r3.x, cb3[51].x
  mul r3.x, r3.x, l(1.442695)
  exp r3.x, r3.x
  add r3.x, -r3.x, l(1.000000)
  mad_sat r2.z, r2.x, r3.x, r2.z
  mul r2.y, r2.y, -cb3[51].z
  mul r2.y, r2.y, l(1.442695)
  exp r2.y, r2.y
  add r2.y, -r2.y, l(1.000000)
  add r3.xyz, -cb3[56].xyzx, cb3[58].xyzx
  mad r3.xyz, r1.wwww, r3.xyzx, cb3[56].xyzx
  add r4.xyz, -r3.xyzx, cb3[55].xyzx
  mad r3.xyz, r2.wwww, r4.xyzx, r3.xyzx
  add r3.xyz, r3.xyzx, -cb3[57].xyzx
  mad r3.xyz, r2.yyyy, r3.xyzx, cb3[57].xyzx
  mov r4.x, cb3[55].w
  mov r4.y, cb3[56].w
  mov r4.z, cb3[57].w
  add r4.xyz, -r3.xyzx, r4.xyzx
  mad r2.xyw, r2.xxxx, r4.xyxz, r3.xyxz
  add r2.xyw, -r0.xyxz, r2.xyxw
  mad r1.xyz, r2.zzzz, r2.xywx, r0.xyzx
endif 
mul o0.xyz, r1.xyzx, cb2[13].zzzz
lt r0.x, l(0.300000), r0.w
and r0.x, r0.x, l(0x3f800000)
mul o1.x, r0.x, v1.z
mov o0.w, r0.w
mov o2.x, r0.x
ret 
// Approximately 354 instruction slots used
