//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16 [unused]
//   float4 gDirectionalColour;         // Offset:   16 Size:    16 [unused]
//   int gNumForwardLights;             // Offset:   32 Size:     4 [unused]
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128 [unused]
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128 [unused]
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128 [unused]
//   float gLightConeScale[8];          // Offset:  432 Size:   116 [unused]
//   float gLightConeOffset[8];         // Offset:  560 Size:   116 [unused]
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16 [unused]
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16 [unused]
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16 [unused]
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16 [unused]
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16 [unused]
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16 [unused]
//   float4 globalFogParams[5];         // Offset:  800 Size:    80 [unused]
//   float4 globalFogColor;             // Offset:  880 Size:    16 [unused]
//   float4 globalFogColorE;            // Offset:  896 Size:    16 [unused]
//   float4 globalFogColorN;            // Offset:  912 Size:    16 [unused]
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16 [unused]
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer more_stuff
// {
//
//   float4 gEntitySelectColor[2];      // Offset:    0 Size:    32 [unused]
//   float4 gAmbientOcclusionEffect;    // Offset:   32 Size:    16 [unused]
//   float4 gDynamicBakesAndWetness;    // Offset:   48 Size:    16
//   float4 gAlphaRefVec0;              // Offset:   64 Size:    16
//   float4 gAlphaRefVec1;              // Offset:   80 Size:    16 [unused]
//   float gAlphaTestRef;               // Offset:   96 Size:     4 [unused]
//   bool gTreesUseDiscard;             // Offset:  100 Size:     4 [unused]
//   float gReflectionMipCount;         // Offset:  104 Size:     4 [unused]
//   bool gUseTransparencyAA;           // Offset:  108 Size:     4 [unused]
//   bool gUseFogRay;                   // Offset:  112 Size:     4 [unused]
//
// }
//
// cbuffer megashader_locals
// {
//
//   float tessellationMultiplier;      // Offset:    0 Size:     4 [unused]
//   float specularFresnel;             // Offset:    4 Size:     4
//   float specularFalloffMult;         // Offset:    8 Size:     4
//   float specularIntensityMult;       // Offset:   12 Size:     4
//   float3 specMapIntMask;             // Offset:   16 Size:    12
//   float bumpiness;                   // Offset:   28 Size:     4
//   float heightScale;                 // Offset:   32 Size:     4 [unused]
//   float heightBias;                  // Offset:   36 Size:     4 [unused]
//   float wetnessMultiplier;           // Offset:   40 Size:     4
//   float useTessellation;             // Offset:   44 Size:     4 [unused]
//   float HardAlphaBlend;              // Offset:   48 Size:     4 [unused]
//
// }
//
// cbuffer detail_map_locals
// {
//
//   float4 detailSettings;             // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// DetailSampler                     sampler      NA          NA             s3      1 
// DiffuseSampler2                   sampler      NA          NA             s5      1 
// BumpSampler                       sampler      NA          NA             s6      1 
// SpecSampler                       sampler      NA          NA             s7      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// DetailSampler                     texture  float4          2d             t3      1 
// DiffuseSampler2                   texture  float4          2d             t5      1 
// BumpSampler                       texture  float4          2d             t6      1 
// SpecSampler                       texture  float4          2d             t7      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// more_stuff                        cbuffer      NA          NA            cb5      1 
// detail_map_locals                 cbuffer      NA          NA           cb11      1 
// megashader_locals                 cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// COLOR                    0   xyzw        1     NONE   float   xy w
// COLOR                    1   xyzw        2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
// TEXCOORD                 9     zw        3     NONE   float     zw
// TEXCOORD                 1   xyz         4     NONE   float   xyz 
// TEXCOORD                 4   xyz         5     NONE   float   xyz 
// TEXCOORD                 5   xyz         6     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
//
ps_4_0
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000} }
dcl_constantbuffer CB2[13], immediateIndexed
dcl_constantbuffer CB3[46], immediateIndexed
dcl_constantbuffer CB5[5], immediateIndexed
dcl_constantbuffer CB12[3], immediateIndexed
dcl_constantbuffer CB11[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s3, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xy
dcl_input_ps linear v3.zw
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyz
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_temps 6
ftou r0.xy, v0.xyxx
and r0.xy, r0.xyxx, l(1, 1, 0, 0)
ishl r0.y, r0.y, l(1)
iadd r0.x, r0.x, r0.y
dp4 r0.x, cb2[0].xyzw, icb[r0.x + 0].xyzw
lt r0.x, r0.x, l(1.000000)
discard_nz r0.x
sample r0.xyzw, v3.xyxx, t0.xyzw, s0
mul r1.x, r0.w, cb2[11].x
ge r1.x, cb5[4].x, r1.x
discard_nz r1.x
sample r1.xyzw, v3.zwzz, t5.xyzw, s5
sample r2.xyzw, v3.xyxx, t7.xyzw, s7
mul r3.xy, v3.xyxx, cb11[0].zwzz
sample r4.xyzw, r3.xyxx, t3.xyzw, s3
mad r3.zw, r4.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
mul r3.xy, r3.xyxx, l(3.170000, 3.170000, 0.000000, 0.000000)
sample r4.xyzw, r3.xyxx, t3.xyzw, s3
mad r3.xy, r4.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mad r3.xy, r3.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000), r3.xyxx
mul r3.z, -r3.x, cb11[0].x
mad r3.z, r3.z, r2.w, l(1.000000)
mul r3.xy, r3.xyxx, cb11[0].yyyy
mul r0.xyzw, r0.xyzw, r3.zzzz
sample r4.xyzw, v3.xyxx, t6.xyzw, s6
mad r3.xy, r3.xyxx, r2.wwww, r4.xyxx
mad r3.xy, r3.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r3.w, r3.xyxx, r3.xyxx
add r3.w, -r3.w, l(1.000000)
sqrt r3.w, |r3.w|
max r4.x, cb12[1].w, l(0.001000)
mul r3.xy, r3.xyxx, r4.xxxx
mul r4.xyz, r3.yyyy, v6.xyzx
mad r4.xyz, r3.xxxx, v5.xyzx, r4.xyzx
mad r3.xyw, r3.wwww, v4.xyxz, r4.xyxz
dp3 r4.x, r3.xywx, r3.xywx
rsq r4.x, r4.x
mul r4.yzw, r3.xxyw, r4.xxxx
mul r2.xy, r2.xyxx, r2.xyxx
dp3 r2.x, r2.xyzx, cb12[1].xyzx
mul r2.xy, r2.xwxx, cb12[0].wzww
mul r5.x, r3.z, r2.x
mad_sat r2.z, v4.z, l(128.000000), l(-127.000000)
mul r0.xyz, r0.xyzx, v2.xyzx
add r2.w, -r1.w, l(1.000000)
mul r1.xyz, r1.wwww, r1.xyzx
mad r0.xyz, r0.xyzx, r2.wwww, r1.xyzx
mul r0.w, r0.w, v1.w
mul r1.yz, v1.xxyx, cb2[11].zzyz
mul o0.w, r0.w, cb2[11].x
mad o1.xyz, r4.yzwy, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
add r0.w, cb12[2].z, l(-0.200000)
mul_sat r0.w, r0.w, l(10.000000)
mul o1.w, r0.w, r2.z
mul r5.y, r2.y, l(0.001953)
mad r1.x, v1.x, cb2[11].z, cb3[45].w
mul r1.xz, r1.xxzx, l(0.500000, 0.000000, 0.500000, 0.000000)
sqrt o3.xy, r1.xzxx
mad r0.w, r3.w, r4.x, l(-0.350000)
mul_sat r0.w, r0.w, l(1.538462)
mul r0.w, r0.w, cb5[3].z
add r1.x, -cb2[12].z, l(1.000000)
mul r0.w, r0.w, r1.x
mul r0.w, r1.y, r0.w
mad r1.x, -r5.x, l(0.500000), l(1.000000)
mul r1.x, r0.w, r1.x
mul r0.w, r0.w, cb12[2].z
mad r1.x, r1.x, l(-0.500000), l(1.000000)
mul o0.xyz, r0.xyzx, r1.xxxx
mad_sat r0.x, r2.x, r3.z, l(0.400000)
mul r0.xy, r0.xxxx, l(0.500000, 0.488281, 0.000000, 0.000000)
mov r5.z, cb12[0].y
mov r0.z, l(0.970000)
add r0.xyz, r0.xyzx, -r5.xyzx
max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r0.xyz, r0.xyzx, r0.wwww, r5.xyzx
sqrt o2.xy, r0.xyxx
mov o2.z, r0.z
mov o2.w, l(1.000000)
mov o3.zw, l(0,0,0,1.001884)
ret 
// Approximately 82 instruction slots used
