//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16 [unused]
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer ped_common_shared_locals
// {
//
//   float4 matWetClothesData;          // Offset:    0 Size:    16 [unused]
//   float4 umPedGlobalOverrideParams;  // Offset:   16 Size:    16 [unused]
//   float4 envEffFatSweatScale;        // Offset:   32 Size:    16 [unused]
//   float paletteSelector;             // Offset:   48 Size:     4 [unused]
//   float2 StubbleGrowth;              // Offset:   52 Size:     8 [unused]
//   float4 _matMaterialColorScale[2];  // Offset:   64 Size:    32
//   float4 PedDamageColors[3];         // Offset:   96 Size:    48 [unused]
//   float4 envEffColorModCpvAdd;       // Offset:  144 Size:    16 [unused]
//   float4 wrinkleMaskStrengths0;      // Offset:  160 Size:    16 [unused]
//   float4 wrinkleMaskStrengths1;      // Offset:  176 Size:    16 [unused]
//   float4 wrinkleMaskStrengths2;      // Offset:  192 Size:    16 [unused]
//   float4 wrinkleMaskStrengths3;      // Offset:  208 Size:    16 [unused]
//   float4 wrinkleMaskStrengths4;      // Offset:  224 Size:    16 [unused]
//   float4 wrinkleMaskStrengths5;      // Offset:  240 Size:    16 [unused]
//   float4 PedDamageData;              // Offset:  256 Size:    16 [unused]
//   float4 wetnessAdjust;              // Offset:  272 Size:    16 [unused]
//   float alphaToCoverageScale;        // Offset:  288 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SpecSampler                       sampler      NA          NA             s5      1 
// SpecSampler                       texture  float4          2d             t5      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// ped_common_shared_locals          cbuffer      NA          NA           cb13      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1     zw        1     NONE   float     zw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB2[13], immediateIndexed
dcl_constantbuffer CB13[5], immediateIndexed
dcl_sampler s5, mode_default
dcl_resource_texture2d (float,float,float,float) t5
dcl_input_ps linear v1.xy
dcl_input_ps linear v1.zw
dcl_output o0.xyzw
dcl_temps 1
sample r0.xyzw, v1.zwzz, t5.xyzw, s5
add r0.x, r0.z, l(-0.875000)
mad_sat r0.x, -|r0.x|, l(8.000000), l(1.500000)
mad r0.x, r0.x, l(0.500000), l(1.000000)
add r0.y, -v1.y, cb2[12].y
add r0.z, -cb2[12].x, cb2[12].y
div_sat r0.y, r0.y, r0.z
mul r0.x, r0.x, r0.y
mul o0.z, r0.x, cb13[4].w
mul r0.x, v1.x, l(65536.000000)
min r0.x, r0.x, l(8191.000000)
mul r0.y, r0.x, l(0.003906)
round_ni r0.y, r0.y
mad r0.x, -r0.y, l(256.000000), r0.x
mul r0.y, r0.y, l(0.003906)
mov o0.x, r0.y
round_ni r0.x, r0.x
mul o0.y, r0.x, l(0.003906)
mov o0.w, l(1.000000)
ret 
// Approximately 20 instruction slots used
