//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16
//   float4 gDirectionalColour;         // Offset:   16 Size:    16
//   int gNumForwardLights;             // Offset:   32 Size:     4 [unused]
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128 [unused]
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128 [unused]
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128 [unused]
//   float gLightConeScale[8];          // Offset:  432 Size:   116 [unused]
//   float gLightConeOffset[8];         // Offset:  560 Size:   116 [unused]
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80
//   float4 globalFogColor;             // Offset:  880 Size:    16
//   float4 globalFogColorE;            // Offset:  896 Size:    16
//   float4 globalFogColorN;            // Offset:  912 Size:    16
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer more_stuff
// {
//
//   float4 gEntitySelectColor[2];      // Offset:    0 Size:    32 [unused]
//   float4 gAmbientOcclusionEffect;    // Offset:   32 Size:    16 [unused]
//   float4 gDynamicBakesAndWetness;    // Offset:   48 Size:    16
//   float4 gAlphaRefVec0;              // Offset:   64 Size:    16 [unused]
//   float4 gAlphaRefVec1;              // Offset:   80 Size:    16 [unused]
//   float gAlphaTestRef;               // Offset:   96 Size:     4 [unused]
//   bool gTreesUseDiscard;             // Offset:  100 Size:     4 [unused]
//   float gReflectionMipCount;         // Offset:  104 Size:     4 [unused]
//   bool gUseTransparencyAA;           // Offset:  108 Size:     4 [unused]
//   bool gUseFogRay;                   // Offset:  112 Size:     4 [unused]
//
// }
//
// cbuffer ped_common_shared_locals
// {
//
//   float4 matWetClothesData;          // Offset:    0 Size:    16 [unused]
//   float4 umPedGlobalOverrideParams;  // Offset:   16 Size:    16 [unused]
//   float4 envEffFatSweatScale;        // Offset:   32 Size:    16 [unused]
//   float paletteSelector;             // Offset:   48 Size:     4 [unused]
//   float2 StubbleGrowth;              // Offset:   52 Size:     8 [unused]
//   float4 _matMaterialColorScale[2];  // Offset:   64 Size:    32
//   float4 PedDamageColors[3];         // Offset:   96 Size:    48
//   float4 envEffColorModCpvAdd;       // Offset:  144 Size:    16 [unused]
//   float4 wrinkleMaskStrengths0;      // Offset:  160 Size:    16 [unused]
//   float4 wrinkleMaskStrengths1;      // Offset:  176 Size:    16 [unused]
//   float4 wrinkleMaskStrengths2;      // Offset:  192 Size:    16 [unused]
//   float4 wrinkleMaskStrengths3;      // Offset:  208 Size:    16 [unused]
//   float4 wrinkleMaskStrengths4;      // Offset:  224 Size:    16 [unused]
//   float4 wrinkleMaskStrengths5;      // Offset:  240 Size:    16 [unused]
//   float4 PedDamageData;              // Offset:  256 Size:    16
//   float4 wetnessAdjust;              // Offset:  272 Size:    16 [unused]
//   float alphaToCoverageScale;        // Offset:  288 Size:     4 [unused]
//
// }
//
// cbuffer ped_common_locals2
// {
//
//   float bumpiness;                   // Offset:    0 Size:     4
//   float specularFresnel;             // Offset:    4 Size:     4
//   float specularFalloffMult;         // Offset:    8 Size:     4
//   float specularIntensityMult;       // Offset:   12 Size:     4
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16
//   float4 gCSMResolution;             // Offset:  224 Size:    16
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// BumpSampler                       sampler      NA          NA             s3      1 
// SpecSampler                       sampler      NA          NA             s4      1 
// pedTattooTargetSampler            sampler      NA          NA            s14      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// BumpSampler                       texture  float4          2d             t3      1 
// SpecSampler                       texture  float4          2d             t4      1 
// pedTattooTargetSampler            texture  float4          2d            t14      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// more_stuff                        cbuffer      NA          NA            cb5      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// ped_common_locals2                cbuffer      NA          NA           cb10      1 
// ped_common_shared_locals          cbuffer      NA          NA           cb13      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xy w
// TEXCOORD                 1   xyzw        1     NONE   float   xyzw
// TEXCOORD                 2   xyzw        2     NONE   float   xyz 
// TEXCOORD                 3   xyzw        3     NONE   float   x   
// TEXCOORD                 5   xyz         4     NONE   float   xyz 
// TEXCOORD                 6   xyz         5     NONE   float   xyz 
// TEXCOORD                 7   xyzw        6     NONE   float   xyzw
// SV_Position              0   xyzw        7      POS   float       
// SV_ClipDistance          0   xyzw        8  CLIPDST   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB1[16], immediateIndexed
dcl_constantbuffer CB2[14], immediateIndexed
dcl_constantbuffer CB3[59], immediateIndexed
dcl_constantbuffer CB5[4], immediateIndexed
dcl_constantbuffer CB13[17], immediateIndexed
dcl_constantbuffer CB10[1], immediateIndexed
dcl_constantbuffer CB6[15], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s14, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v0.xyw
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.x
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyzw
dcl_output o0.xyzw
dcl_temps 24
dcl_indexableTemp x0[4], 4
sample r0.xyzw, v0.xyxx, t0.xyzw, s0
mul r0.w, r0.w, cb2[11].x
ge r0.w, l(0.501961), r0.w
discard_nz r0.w
sample r1.xyzw, v0.xyxx, t3.xyzw, s3
mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.w, r1.xyxx, r1.xyxx
add r0.w, -r0.w, l(1.000000)
sqrt r0.w, |r0.w|
max r1.z, cb10[0].x, l(0.001000)
mul r1.xy, r1.zzzz, r1.xyxx
mul r1.yzw, r1.yyyy, v5.xxyz
mad r1.xyz, r1.xxxx, v4.xyzx, r1.yzwy
mad r1.xyz, r0.wwww, v1.xyzx, r1.xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r1.xyw, r0.wwww, r1.xyxz
sample r2.xyzw, v0.xyxx, t4.xyzw, s4
mul r2.xy, r2.yxyy, r2.yxyy
mad r2.z, -r2.z, l(16.000000), l(14.000000)
ge r2.z, l(1.000000), |r2.z|
and o0.w, r2.z, l(0x3f800000)
mul r2.zw, r2.yyyx, cb10[0].wwwz
mul r3.xy, v3.xxxx, cb2[11].zyzz
mad r3.z, r1.w, l(0.500000), l(0.500000)
mad r4.x, r3.z, cb5[3].y, cb5[3].x
add r4.y, r3.z, l(0.300000)
mul r3.xy, r3.xyxx, r4.xyxx
mul r3.z, v6.z, cb13[16].x
ne r3.z, r3.z, l(0.000000)
if_nz r3.z
  frc r4.xz, v6.yyxy
  mad r4.w, r4.x, v0.w, v1.w
  frc r3.z, cb13[16].z
  add r4.y, -r4.z, l(1.000000)
  ge r3.w, cb13[16].z, l(1.000000)
  movc r5.xy, r3.wwww, r4.wyww, r4.zwzz
  sample_l r5.xyzw, r5.xyxx, t14.xyzw, s14, l(0.000000)
  lt r3.w, l(0.600000), r3.z
  if_nz r3.w
    mad r4.x, r4.x, |v6.z|, |v6.w|
    lt r3.z, l(0.100000), r3.z
    movc r3.zw, r3.zzzz, r4.xxxy, r4.zzzx
    sample_l r4.xyzw, r3.zwzz, t14.xyzw, s14, l(0.000000)
  else 
    mov r4.xyz, l(0,0,1.000000,0)
  endif 
  ge r3.z, l(0.501961), r5.w
  lt r3.w, l(0.000000), cb13[16].x
  and r3.z, r3.z, r3.w
  movc r5.xyzw, r3.zzzz, r5.xyzw, l(0,0,0,0.500000)
  mad r3.z, r5.w, l(2.000000), l(-1.000000)
  add r3.z, -|r3.z|, l(1.000000)
  add r3.w, -r4.z, l(1.000000)
  mul r3.w, r3.w, r3.w
  mul r3.w, r4.x, r3.w
  mad r2.x, -r2.x, cb10[0].z, cb13[6].w
  mad r2.w, r3.w, r2.x, r2.w
  mad r2.x, -r2.y, cb10[0].w, cb13[7].w
  mad r2.z, r3.w, r2.x, r2.z
  mad r5.xyz, r0.xyzx, r3.zzzz, r5.xyzx
  mad r6.xyz, r5.xyzx, cb13[7].xyzx, -r5.xyzx
  mad r5.xyz, r4.yyyy, r6.xyzx, r5.xyzx
  mul r4.xyw, r4.xxxx, cb13[6].xyxz
  mad r0.xyz, r5.xyzx, r4.zzzz, r4.xywx
endif 
mul r0.xyz, r0.xyzx, r0.xyzx
add r4.xyz, -v2.xyzx, cb1[15].xyzx
dp3 r2.x, r4.xyzx, r4.xyzx
rsq r2.x, r2.x
mul r5.xyz, r2.xxxx, r4.xyzx
mad r6.xyz, r4.xyzx, r2.xxxx, -cb3[0].xyzx
dp3 r2.x, r6.xyzx, r6.xyzx
rsq r2.x, r2.x
mul r6.xyz, r2.xxxx, r6.xyzx
mov_sat r2.z, r2.z
mul r2.xy, r3.xyxx, r3.xyxx
add r3.x, r2.w, l(-500.000000)
max r3.x, r3.x, l(0.000000)
add r2.w, r2.w, -r3.x
mul r3.x, r3.x, l(558.000000)
mad r2.w, r2.w, l(3.000000), r3.x
dp3 r3.x, r4.xyzx, cb1[14].xyzx
add r3.yzw, v2.xxyz, -cb1[15].xxyz
mul r4.xyz, r3.zzzz, cb6[1].xyzx
mad r4.xyz, r3.yyyy, cb6[0].xyzx, r4.xyzx
mad r4.xyz, r3.wwww, cb6[2].xyzx, r4.xyzx
mad r7.xyz, r4.xyzx, cb6[4].xyzx, cb6[8].xyzx
mov x0[0].xyz, r7.xyzx
mad r8.xyz, r4.xyzx, cb6[5].xyzx, cb6[9].xyzx
mov x0[1].xyz, r8.xyzx
mad r9.xyz, r4.xyzx, cb6[6].xyzx, cb6[10].xyzx
mov x0[2].xyz, r9.xyzx
mad r4.xyz, r4.xyzx, cb6[7].xyzx, cb6[11].xyzx
mov x0[3].xyz, r4.xyzx
mul r10.yw, cb6[14].zzzw, l(0.000000, -0.346097, 0.000000, 0.328490)
mad r4.z, -cb6[14].z, l(1.500000), l(1.000000)
mul r4.z, r4.z, l(0.500000)
max r4.w, |r9.y|, |r9.x|
lt r4.w, r4.w, r4.z
movc r4.w, r4.w, l(2), l(3)
max r5.w, |r8.y|, |r8.x|
lt r5.w, r5.w, r4.z
movc r4.w, r5.w, l(1), r4.w
max r5.w, |r7.y|, |r7.x|
lt r4.z, r5.w, r4.z
movc r4.z, r4.z, l(0), r4.w
mov r7.xyz, x0[r4.z + 0].xyzx
itof r4.z, r4.z
add r4.w, r4.z, l(0.500000)
mul r4.w, r4.w, l(0.250000)
eq r8.xyzw, l(0.000000, 1.000000, 2.000000, 3.000000), r4.zzzz
and r8.xyzw, r8.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
dp4 r4.z, r8.xyzw, cb6[12].xyzw
dp4 r5.w, r8.xyzw, cb6[13].xyzw
add r8.x, r7.x, l(0.500000)
mad r8.y, r7.y, l(0.250000), r4.w
ne r4.w, r4.z, l(0.000000)
add r4.z, -r4.z, r7.z
deriv_rtx r9.xyw, r8.xyxy
deriv_rtx r9.z, r4.z
deriv_rty r11.xyz, r8.yxyy
deriv_rty r11.w, r4.z
mul r7.xy, r9.ywyy, r11.ywyy
mad r12.xy, r9.xzxx, r11.xzxx, -r7.xyxx
div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r12.x
mul r7.x, r9.z, r11.y
mad r12.z, r9.x, r11.w, -r7.x
mul r7.xy, r6.wwww, r12.yzyy
max r7.xy, r7.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r7.xy, r7.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mad r4.z, -r5.w, r7.x, r4.z
mad r4.z, -r5.w, r7.y, r4.z
movc r10.z, r4.w, r4.z, r7.z
mov r8.z, l(0)
add r7.xyz, r8.xyzx, r10.ywzy
mul r10.xy, cb6[14].zwzz, l(-0.799291, 0.201741, 0.000000, 0.000000)
add r9.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(-0.031176, 0.179338, 0.000000, 0.000000)
add r11.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(0.514749, 0.253502, 0.000000, 0.000000)
add r12.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(-0.072870, 0.008097, 0.000000, 0.000000)
add r13.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(-0.969781, 0.034522, 0.000000, 0.000000)
add r14.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(0.545547, 0.024129, 0.000000, 0.000000)
add r15.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(-0.028906, -0.136785, 0.000000, 0.000000)
add r16.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(-0.479511, -0.244833, 0.000000, 0.000000)
add r17.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(0.758788, -0.112109, 0.000000, 0.000000)
add r18.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(0.339353, -0.249328, 0.000000, 0.000000)
add r19.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(1.070598, 0.208123, 0.000000, 0.000000)
add r20.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(1.294038, -0.018078, 0.000000, 0.000000)
add r21.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(-0.747563, -0.113974, 0.000000, 0.000000)
add r22.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(0.947722, -0.248764, 0.000000, 0.000000)
add r23.xyz, r8.xyzx, r10.xyzx
mul r10.xy, cb6[14].zwzz, l(-1.343153, -0.088584, 0.000000, 0.000000)
add r8.xyz, r8.xyzx, r10.xyzx
sample_c_lz r7.x, r7.xyxx, t15.xxxx, s15, r7.z
sample_c_lz r7.y, r9.xyxx, t15.xxxx, s15, r9.z
sample_c_lz r7.z, r11.xyxx, t15.xxxx, s15, r11.z
sample_c_lz r7.w, r12.xyxx, t15.xxxx, s15, r12.z
sample_c_lz r9.x, r13.xyxx, t15.xxxx, s15, r13.z
sample_c_lz r9.y, r14.xyxx, t15.xxxx, s15, r14.z
sample_c_lz r9.z, r15.xyxx, t15.xxxx, s15, r15.z
sample_c_lz r9.w, r16.xyxx, t15.xxxx, s15, r16.z
sample_c_lz r10.x, r17.xyxx, t15.xxxx, s15, r17.z
sample_c_lz r10.y, r18.xyxx, t15.xxxx, s15, r18.z
sample_c_lz r10.z, r19.xyxx, t15.xxxx, s15, r19.z
sample_c_lz r10.w, r20.xyxx, t15.xxxx, s15, r20.z
sample_c_lz r11.x, r21.xyxx, t15.xxxx, s15, r21.z
sample_c_lz r11.y, r22.xyxx, t15.xxxx, s15, r22.z
sample_c_lz r11.z, r23.xyxx, t15.xxxx, s15, r23.z
sample_c_lz r11.w, r8.xyxx, t15.xxxx, s15, r8.z
add r7.xyzw, r7.xyzw, r9.xyzw
add r7.xyzw, r10.xyzw, r7.xyzw
add r7.xyzw, r11.xyzw, r7.xyzw
dp4 r4.z, r7.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mad_sat r3.x, r3.x, cb6[0].w, cb6[1].w
max r4.x, |r4.y|, |r4.x|
mad_sat r4.x, r4.x, l(15.000000), l(-6.300000)
add r3.x, -r3.x, l(1.000000)
mul r3.x, r4.x, r3.x
mad r3.x, r4.z, l(0.062500), r3.x
mul r3.x, r3.x, r3.x
min r3.x, r3.x, l(1.000000)
mad_sat r4.x, v2.z, cb6[3].x, cb6[3].y
sqrt r4.x, r4.x
mul r4.x, r4.x, cb6[3].z
mad r3.x, r4.x, -r3.x, r3.x
dp3_sat r4.x, r1.xywx, -cb3[0].xyzx
dp3_sat r5.x, r5.xyzx, r1.xywx
dp3_sat r5.y, r6.xyzx, -cb3[0].xyzx
add r4.yz, -r5.xxyx, l(0.000000, 1.000000, 1.000000, 0.000000)
mul r5.xy, r4.yzyy, r4.yzyy
mul r5.xy, r5.xyxx, r5.xyxx
mul r4.yz, r4.yyzy, r5.xxyx
add r4.w, -cb10[0].y, l(1.000000)
mad r4.yz, cb10[0].yyyy, r4.yyzy, r4.wwww
add r5.xy, r2.wwww, l(2.000000, 0.000000, 0.000000, 0.000000)
mul r2.w, r5.x, l(0.125000)
mad r4.y, -r2.z, r4.y, l(1.000000)
dp3 r4.w, r1.xywx, r6.xyzx
add_sat r4.w, r4.w, l(0.000000)
log r4.w, r4.w
mul r4.w, r4.w, r5.y
exp r4.w, r4.w
mul r4.z, r4.z, r4.w
mul r2.w, r2.w, r4.z
mul r2.z, r2.z, r2.w
mul r2.z, r4.x, r2.z
mul r2.w, r4.y, r4.x
mad r4.xzw, r0.xxyz, r2.wwww, r2.zzzz
mul r4.xzw, r4.xxzw, cb3[1].xxyz
mad r0.w, r1.z, r0.w, cb3[43].w
mul r0.w, r0.w, cb3[44].w
max r0.w, r0.w, l(0.000000)
mad r5.xyz, cb3[47].xyzx, r0.wwww, cb3[48].xyzx
add r1.z, -cb2[12].z, l(1.000000)
mad r6.xyz, cb3[45].xyzx, r0.wwww, cb3[46].xyzx
mul r6.xyz, r6.xyzx, cb2[12].zzzz
mad r5.xyz, r5.xyzx, r1.zzzz, r6.xyzx
mul r2.yzw, r2.yyyy, r5.xxyz
mad r5.xyz, cb3[43].xyzx, r0.wwww, cb3[44].xyzx
mov r6.x, cb3[46].w
mov r6.y, cb3[47].w
mov r6.z, cb3[48].w
dp3_sat r0.w, r6.xyzx, r1.xywx
mad r1.xyz, cb3[49].xyzx, r0.wwww, r5.xyzx
mad r1.xyz, r1.xyzx, r2.xxxx, r2.yzwy
mul r1.xyz, r4.yyyy, r1.xyzx
mul r0.xyz, r0.xyzx, r1.xyzx
mad r0.xyz, r4.xzwx, r3.xxxx, r0.xyzx
dp3 r0.w, r3.yzwy, r3.yzwy
sqrt r1.x, r0.w
add r1.y, r1.x, -cb3[50].x
max r1.y, r1.y, l(0.000000)
div r1.x, r1.y, r1.x
mul r1.x, r1.x, r3.w
mul r1.z, r1.x, cb3[52].z
lt r1.x, l(0.010000), |r1.x|
mul r1.w, r1.z, l(-1.442695)
exp r1.w, r1.w
add r1.w, -r1.w, l(1.000000)
div r1.z, r1.w, r1.z
movc r1.x, r1.x, r1.z, l(1.000000)
mul r1.z, r1.y, cb3[51].w
mul r1.x, r1.x, r1.z
min r1.x, r1.x, l(1.000000)
mul r1.x, r1.x, l(1.442695)
exp r1.x, r1.x
min r1.x, r1.x, l(1.000000)
add r1.x, -r1.x, l(1.000000)
mul r1.z, r1.x, cb3[52].y
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, r3.yzwy
dp3_sat r0.w, r2.xyzx, cb3[54].xyzx
log r0.w, r0.w
mul r0.w, r0.w, cb3[54].w
exp r0.w, r0.w
dp3_sat r1.w, r2.xyzx, cb3[53].xyzx
log r1.w, r1.w
mul r1.w, r1.w, cb3[53].w
exp r1.w, r1.w
mad r1.x, -r1.x, cb3[52].y, l(1.000000)
mul r1.x, r1.x, cb3[51].y
add r2.x, r1.y, -cb3[52].x
max r2.x, r2.x, l(0.000000)
mul r2.x, r2.x, cb3[51].x
mul r2.x, r2.x, l(1.442695)
exp r2.x, r2.x
add r2.x, -r2.x, l(1.000000)
mad_sat r1.z, r1.x, r2.x, r1.z
mul r1.y, r1.y, -cb3[51].z
mul r1.y, r1.y, l(1.442695)
exp r1.y, r1.y
add r1.y, -r1.y, l(1.000000)
add r2.xyz, -cb3[56].xyzx, cb3[58].xyzx
mad r2.xyz, r0.wwww, r2.xyzx, cb3[56].xyzx
add r3.xyz, -r2.xyzx, cb3[55].xyzx
mad r2.xyz, r1.wwww, r3.xyzx, r2.xyzx
add r2.xyz, r2.xyzx, -cb3[57].xyzx
mad r2.xyz, r1.yyyy, r2.xyzx, cb3[57].xyzx
add r3.x, -r2.x, cb3[55].w
add r3.y, -r2.y, cb3[56].w
add r3.z, -r2.z, cb3[57].w
mad r1.xyw, r1.xxxx, r3.xyxz, r2.xyxz
add r1.xyw, -r0.xyxz, r1.xyxw
mad r0.xyz, r1.zzzz, r1.xywx, r0.xyzx
mul r0.xyz, r0.xyzx, cb13[4].xxxx
mul o0.xyz, r0.xyzx, cb2[13].zzzz
ret 
// Approximately 300 instruction slots used
