//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16 [unused]
//   float4 gDirectionalColour;         // Offset:   16 Size:    16 [unused]
//   int gNumForwardLights;             // Offset:   32 Size:     4 [unused]
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128 [unused]
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128 [unused]
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128 [unused]
//   float gLightConeScale[8];          // Offset:  432 Size:   116 [unused]
//   float gLightConeOffset[8];         // Offset:  560 Size:   116 [unused]
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16 [unused]
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16 [unused]
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16 [unused]
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16 [unused]
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16 [unused]
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80 [unused]
//   float4 globalFogColor;             // Offset:  880 Size:    16 [unused]
//   float4 globalFogColorE;            // Offset:  896 Size:    16 [unused]
//   float4 globalFogColorN;            // Offset:  912 Size:    16 [unused]
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16 [unused]
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer more_stuff
// {
//
//   float4 gEntitySelectColor[2];      // Offset:    0 Size:    32 [unused]
//   float4 gAmbientOcclusionEffect;    // Offset:   32 Size:    16 [unused]
//   float4 gDynamicBakesAndWetness;    // Offset:   48 Size:    16
//   float4 gAlphaRefVec0;              // Offset:   64 Size:    16 [unused]
//   float4 gAlphaRefVec1;              // Offset:   80 Size:    16 [unused]
//   float gAlphaTestRef;               // Offset:   96 Size:     4 [unused]
//   bool gTreesUseDiscard;             // Offset:  100 Size:     4 [unused]
//   float gReflectionMipCount;         // Offset:  104 Size:     4 [unused]
//   bool gUseTransparencyAA;           // Offset:  108 Size:     4 [unused]
//   bool gUseFogRay;                   // Offset:  112 Size:     4 [unused]
//
// }
//
// cbuffer ped_common_shared_locals
// {
//
//   float4 matWetClothesData;          // Offset:    0 Size:    16 [unused]
//   float4 umPedGlobalOverrideParams;  // Offset:   16 Size:    16 [unused]
//   float4 envEffFatSweatScale;        // Offset:   32 Size:    16 [unused]
//   float paletteSelector;             // Offset:   48 Size:     4
//   float2 StubbleGrowth;              // Offset:   52 Size:     8 [unused]
//   float4 _matMaterialColorScale[2];  // Offset:   64 Size:    32
//   float4 PedDamageColors[3];         // Offset:   96 Size:    48 [unused]
//   float4 envEffColorModCpvAdd;       // Offset:  144 Size:    16
//   float4 wrinkleMaskStrengths0;      // Offset:  160 Size:    16 [unused]
//   float4 wrinkleMaskStrengths1;      // Offset:  176 Size:    16 [unused]
//   float4 wrinkleMaskStrengths2;      // Offset:  192 Size:    16 [unused]
//   float4 wrinkleMaskStrengths3;      // Offset:  208 Size:    16 [unused]
//   float4 wrinkleMaskStrengths4;      // Offset:  224 Size:    16 [unused]
//   float4 wrinkleMaskStrengths5;      // Offset:  240 Size:    16 [unused]
//   float4 PedDamageData;              // Offset:  256 Size:    16 [unused]
//   float4 wetnessAdjust;              // Offset:  272 Size:    16
//   float alphaToCoverageScale;        // Offset:  288 Size:     4 [unused]
//
// }
//
// cbuffer ped_common_locals2
// {
//
//   float2 anisotropicSpecularIntensity;// Offset:    0 Size:     8
//   float2 anisotropicSpecularExponent;// Offset:    8 Size:     8
//   float4 anisotropicSpecularColour;  // Offset:   16 Size:    16
//   float4 specularNoiseMapUVScaleFactor;// Offset:   32 Size:    16
//   float bumpiness;                   // Offset:   48 Size:     4
//   float specularFresnel;             // Offset:   52 Size:     4
//   float specularFalloffMult;         // Offset:   56 Size:     4
//   float specularIntensityMult;       // Offset:   60 Size:     4
//   float orderNumber;                 // Offset:   64 Size:     4 [unused]
//
// }
//
// cbuffer pedmisclocals
// {
//
//   float AnisotropicAlphaBias;        // Offset:    0 Size:     4
//   float4 umGlobalParams;             // Offset:   16 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// AnisoNoiseSpecSampler             sampler      NA          NA             s3      1 
// BumpSampler                       sampler      NA          NA             s4      1 
// SpecSampler                       sampler      NA          NA             s5      1 
// SnowSampler                       sampler      NA          NA             s6      1 
// TextureSamplerDiffPal             sampler      NA          NA            s13      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// AnisoNoiseSpecSampler             texture  float4          2d             t3      1 
// BumpSampler                       texture  float4          2d             t4      1 
// SpecSampler                       texture  float4          2d             t5      1 
// SnowSampler                       texture  float4          2d             t6      1 
// TextureSamplerDiffPal             texture  float4          2d            t13      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// more_stuff                        cbuffer      NA          NA            cb5      1 
// pedmisclocals                     cbuffer      NA          NA            cb8      1 
// ped_common_locals2                cbuffer      NA          NA           cb10      1 
// ped_common_shared_locals          cbuffer      NA          NA           cb13      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 8      w        1     NONE   float      w
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 3   xyzw        3     NONE   float   x   
// TEXCOORD                 4   xyz         4     NONE   float   xyz 
// TEXCOORD                 5   xyz         5     NONE   float   xyz 
// TEXCOORD                 6   xyz         6     NONE   float   xyz 
// TEXCOORD                 2   xyz         7     NONE   float   x   
// SV_IsFrontFace           0   x           8    FFACE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB1[15], immediateIndexed
dcl_constantbuffer CB2[13], immediateIndexed
dcl_constantbuffer CB3[50], immediateIndexed
dcl_constantbuffer CB5[4], immediateIndexed
dcl_constantbuffer CB13[18], immediateIndexed
dcl_constantbuffer CB10[4], immediateIndexed
dcl_constantbuffer CB8[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s13, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t13
dcl_input_ps linear v1.xyz
dcl_input_ps linear v1.w
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.x
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyz
dcl_input_ps linear v7.x
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_temps 8
sample r0.xyzw, v1.xyxx, t0.xyzw, s0
sample r1.xyzw, v1.xyxx, t4.xyzw, s4
mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.z, r1.xyxx, r1.xyxx
add r0.z, -r0.z, l(1.000000)
sqrt r0.z, |r0.z|
max r1.z, cb10[3].x, l(0.001000)
mul r1.xy, r1.zzzz, r1.xyxx
mul r1.yzw, r1.yyyy, v6.xxyz
mad r1.xyz, r1.xxxx, v5.xyzx, r1.yzwy
mad r1.xyz, r0.zzzz, v2.xyzx, r1.xyzx
dp3 r0.z, r1.xyzx, r1.xyzx
rsq r0.z, r0.z
mul r1.xyw, r0.zzzz, r1.xyxz
sample r2.xyzw, v1.xyxx, t5.xyzw, s5
mul r2.xy, r2.yxyy, r2.yxyy
ge r2.w, r2.z, l(0.812500)
mad_sat o1.w, v2.z, l(128.000000), l(-127.000000)
ne r3.x, l(0.000000, 0.000000, 0.000000, 0.000000), v1.w
if_nz r3.x
  sample r3.xyzw, v1.xyxx, t6.xyzw, s6
  mad r3.x, r3.x, cb13[9].x, -r0.x
  mad r0.x, v1.w, r3.x, r0.x
endif 
mov r0.y, cb13[3].x
sample r3.xyzw, r0.xyxx, t13.xyzw, s13
mul r0.xy, v3.xxxx, cb2[11].zyzz
mad r3.w, r1.w, l(0.500000), l(0.500000)
mad r4.x, r3.w, cb5[3].y, cb5[3].x
add r3.w, r3.w, l(0.300000)
mul r0.y, r0.y, r3.w
add r4.yz, v1.zzzz, l(0.000000, 0.000000, -0.750000, 0.000000)
mul_sat r4.yz, r4.yyzy, l(0.000000, 4.000000, 4.000000, 0.000000)
ieq r3.w, r2.w, l(0)
mul r5.xyz, r3.xyzx, cb13[17].xxxx
mul r5.xyz, r4.yyyy, r5.xyzx
and r5.xyz, r3.wwww, r5.xyzx
add r3.xyz, r3.xyzx, -r5.xyzx
mul r4.yz, r4.zzzz, cb13[17].yyzy
mad r2.xy, r2.xyxx, cb10[3].zwzz, r4.yzyy
mul r3.xyz, r3.xyzx, cb13[4].xxxx
and r3.w, r2.w, l(0x3c23d70a)
movc r2.w, r2.w, l(-0.010000), l(-0.000000)
add r2.y, r2.w, r2.y
mad r2.y, cb13[4].z, r2.y, r3.w
dp3 r2.w, v4.xyzx, v4.xyzx
rsq r2.w, r2.w
mul r4.yzw, r2.wwww, v4.xxyz
dp3_sat r2.w, r4.yzwy, r1.xywx
add r2.w, -r2.w, l(1.000000)
mad r2.w, r2.w, l(0.400000), l(0.500000)
mad r0.z, r1.z, r0.z, l(1.000000)
mad_sat r0.z, r0.z, l(0.500000), l(-0.300000)
mul r0.z, r0.z, l(1.428571)
mov_sat r1.z, v7.x
mul r1.z, r1.z, r2.w
mul r0.z, r0.z, r1.z
mul r5.xyz, r3.xyzx, r0.zzzz
mad r3.xyz, r5.xyzx, cb13[4].yyyy, r3.xyzx
dp3 r0.z, v6.xyzx, v6.xyzx
rsq r0.z, r0.z
mul r5.xyz, r0.zzzz, v6.xyzx
mul r6.xyzw, v1.xyxy, cb10[2].xyzw
mul r6.xyzw, r6.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
sample r7.xyzw, r6.xyxx, t3.xyzw, s3
sample r6.xyzw, r6.zwzz, t3.xyzw, s3
mad r6.xy, r6.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r6.xy, r6.xyxx, l(0.100000, 0.100000, 0.000000, 0.000000)
mad r6.xzw, v2.xxyz, r6.xxxx, r5.xxyz
dp3 r0.z, r6.xzwx, r6.xzwx
rsq r0.z, r0.z
mul r6.xzw, r0.zzzz, r6.xxzw
dp3 r0.z, r4.yzwy, r6.xzwx
dp3 r1.z, cb1[14].xyzx, r6.xzwx
mad r5.xyz, v2.xyzx, r6.yyyy, r5.xyzx
dp3 r2.w, r5.xyzx, r5.xyzx
rsq r2.w, r2.w
mul r5.xyz, r2.wwww, r5.xyzx
dp3 r2.w, r4.yzwy, r5.xyzx
dp3 r3.w, cb1[14].xyzx, r5.xyzx
mad r4.y, -r0.z, r0.z, l(1.000000)
mad r4.z, -r1.z, r1.z, l(1.000000)
sqrt r4.yz, r4.yyzy
mul r0.z, r0.z, r1.z
mad r0.z, r4.y, r4.z, -r0.z
mad r1.z, -r2.w, r2.w, l(1.000000)
sqrt r1.z, r1.z
mad r4.y, -r3.w, r3.w, l(1.000000)
sqrt r4.y, r4.y
mul r2.w, r2.w, r3.w
mad r1.z, r1.z, r4.y, -r2.w
add r4.yz, cb10[0].zzwz, l(0.000000, 8.000000, 16.000000, 0.000000)
log r0.z, |r0.z|
mul r0.z, r0.z, r4.y
exp r0.z, r0.z
log r1.z, |r1.z|
mul r1.z, r1.z, r4.z
exp r1.z, r1.z
mul r2.w, r1.z, cb10[0].y
mad r0.z, r0.z, cb10[0].x, r2.w
lt r2.z, r2.z, l(0.031250)
and r2.w, r2.z, l(0x3f800000)
mul r0.z, r7.x, r0.z
movc r0.z, r2.z, r0.z, l(1.000000)
mul r0.z, r0.z, r2.y
mul r4.yzw, r1.zzzz, cb10[1].xxyz
mul r2.yzw, r2.wwww, r4.yyzw
mad o0.xyz, r2.yzwy, l(0.500000, 0.500000, 0.500000, 0.000000), r3.xyzx
mad_sat r1.z, r7.w, l(2.000000), cb8[0].x
mul r0.w, r0.w, r1.z
add_sat r1.z, cb2[12].z, cb3[49].w
mul r3.y, r0.y, r1.z
mul o0.w, r0.w, cb2[11].x
mad o1.xyz, r1.xywx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
mul r0.y, r2.x, l(0.001953)
mad r3.x, r4.x, r0.x, cb3[45].w
mul r0.xw, r3.xxxy, l(0.500000, 0.000000, 0.000000, 0.500000)
sqrt o3.xy, r0.xwxx
sqrt o2.xy, r0.zyzz
mov o2.z, cb10[3].y
mov o2.w, l(1.000000)
mov o3.zw, l(0,0,0,1.001884)
ret 
// Approximately 123 instruction slots used
