//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// HDRSampler                        sampler      NA          NA             s5      1 
// BlurSampler                       sampler      NA          NA             s7      1 
// HDRSampler                        texture  float4          2d             t5      1 
// BlurSampler                       texture  float4          2d             t7      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_sampler s5, mode_default
dcl_sampler s7, mode_default
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t7
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 2
sample r0.xyzw, v1.xyxx, t7.xyzw, s7
sample r1.xyzw, v1.xyxx, t5.xyzw, s5
max r0.x, r0.w, r1.w
mad o0.w, r0.x, l(2.000000), -r1.w
mov o0.xyz, r1.xyzx
ret 
// Approximately 6 instruction slots used
