//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer postfx_cbuffer
// {
//
//   float4 dofProj;                    // Offset:    0 Size:    16 [unused]
//   float4 dofShear;                   // Offset:   16 Size:    16 [unused]
//   float4 dofDist;                    // Offset:   32 Size:    16 [unused]
//   float4 hiDofParams;                // Offset:   48 Size:    16 [unused]
//   float4 hiDofMiscParams;            // Offset:   64 Size:    16 [unused]
//   float4 PostFXAdaptiveDofEnvBlurParams;// Offset:   80 Size:    16 [unused]
//   float4 PostFXAdaptiveDofCustomPlanesParams;// Offset:   96 Size:    16 [unused]
//   float4 BloomParams;                // Offset:  112 Size:    16 [unused]
//   float4 Filmic0;                    // Offset:  128 Size:    16 [unused]
//   float4 Filmic1;                    // Offset:  144 Size:    16 [unused]
//   float4 NoiseParams;                // Offset:  160 Size:    16 [unused]
//   float4 DirectionalMotionBlurParams;// Offset:  176 Size:    16 [unused]
//   float4 MBPrevViewProjMatrixX;      // Offset:  192 Size:    16 [unused]
//   float4 MBPrevViewProjMatrixY;      // Offset:  208 Size:    16 [unused]
//   float4 MBPrevViewProjMatrixW;      // Offset:  224 Size:    16 [unused]
//   float3 MBPerspectiveShearParams0;  // Offset:  240 Size:    12 [unused]
//   float3 MBPerspectiveShearParams1;  // Offset:  256 Size:    12 [unused]
//   float3 MBPerspectiveShearParams2;  // Offset:  272 Size:    12 [unused]
//   float lowLum;                      // Offset:  284 Size:     4 [unused]
//   float highLum;                     // Offset:  288 Size:     4 [unused]
//   float topLum;                      // Offset:  292 Size:     4 [unused]
//   float scalerLum;                   // Offset:  296 Size:     4 [unused]
//   float offsetLum;                   // Offset:  300 Size:     4 [unused]
//   float offsetLowLum;                // Offset:  304 Size:     4 [unused]
//   float offsetHighLum;               // Offset:  308 Size:     4 [unused]
//   float noiseLum;                    // Offset:  312 Size:     4 [unused]
//   float noiseLowLum;                 // Offset:  316 Size:     4 [unused]
//   float noiseHighLum;                // Offset:  320 Size:     4 [unused]
//   float bloomLum;                    // Offset:  324 Size:     4 [unused]
//   float4 colorLum;                   // Offset:  336 Size:    16 [unused]
//   float4 colorLowLum;                // Offset:  352 Size:    16 [unused]
//   float4 colorHighLum;               // Offset:  368 Size:    16 [unused]
//   float4 HeatHazeParams;             // Offset:  384 Size:    16 [unused]
//   float4 HeatHazeTex1Params;         // Offset:  400 Size:    16 [unused]
//   float4 HeatHazeTex2Params;         // Offset:  416 Size:    16 [unused]
//   float4 HeatHazeOffsetParams;       // Offset:  432 Size:    16 [unused]
//   float4 LensArtefactsParams0;       // Offset:  448 Size:    16 [unused]
//   float4 LensArtefactsParams1;       // Offset:  464 Size:    16
//   float4 LensArtefactsParams2;       // Offset:  480 Size:    16 [unused]
//   float4 LensArtefactsParams3;       // Offset:  496 Size:    16 [unused]
//   float4 LensArtefactsParams4;       // Offset:  512 Size:    16 [unused]
//   float4 LensArtefactsParams5;       // Offset:  528 Size:    16 [unused]
//   float4 LightStreaksColorShift0;    // Offset:  544 Size:    16
//   float4 LightStreaksBlurColWeights; // Offset:  560 Size:    16 [unused]
//   float4 LightStreaksBlurDir;        // Offset:  576 Size:    16
//   float4 globalFreeAimDir;           // Offset:  592 Size:    16 [unused]
//   float4 globalFogRayParam;          // Offset:  608 Size:    16 [unused]
//   float4 globalFogRayFadeParam;      // Offset:  624 Size:    16 [unused]
//   float4 lightrayParams;             // Offset:  640 Size:    16 [unused]
//   float4 lightrayParams2;            // Offset:  656 Size:    16 [unused]
//   float4 seeThroughParams;           // Offset:  672 Size:    16 [unused]
//   float4 seeThroughColorNear;        // Offset:  688 Size:    16 [unused]
//   float4 seeThroughColorFar;         // Offset:  704 Size:    16 [unused]
//   float4 seeThroughColorVisibleBase; // Offset:  720 Size:    16 [unused]
//   float4 seeThroughColorVisibleWarm; // Offset:  736 Size:    16 [unused]
//   float4 seeThroughColorVisibleHot;  // Offset:  752 Size:    16 [unused]
//   float4 debugParams0;               // Offset:  768 Size:    16 [unused]
//   float4 debugParams1;               // Offset:  784 Size:    16 [unused]
//   float PLAYER_MASK;                 // Offset:  800 Size:     4 [unused]
//   float4 VignettingParams;           // Offset:  816 Size:    16 [unused]
//   float4 VignettingColor;            // Offset:  832 Size:    16 [unused]
//   float4 GradientFilterColTop;       // Offset:  848 Size:    16 [unused]
//   float4 GradientFilterColBottom;    // Offset:  864 Size:    16 [unused]
//   float4 GradientFilterColMiddle;    // Offset:  880 Size:    16 [unused]
//   float4 DamageOverlayMisc;          // Offset:  896 Size:    16 [unused]
//   float4 ScanlineFilterParams;       // Offset:  912 Size:    16 [unused]
//   float ScreenBlurFade;              // Offset:  928 Size:     4 [unused]
//   float4 ColorCorrectHighLum;        // Offset:  944 Size:    16 [unused]
//   float4 ColorShiftLowLum;           // Offset:  960 Size:    16 [unused]
//   float Desaturate;                  // Offset:  976 Size:     4 [unused]
//   float Gamma;                       // Offset:  980 Size:     4 [unused]
//   float4 LensDistortionParams;       // Offset:  992 Size:    16 [unused]
//   float4 DistortionParams;           // Offset: 1008 Size:    16 [unused]
//   float4 BlurVignettingParams;       // Offset: 1024 Size:    16 [unused]
//   float4 BloomTexelSize;             // Offset: 1040 Size:    16 [unused]
//   float4 TexelSize;                  // Offset: 1056 Size:    16
//   float4 GBufferTexture0Param;       // Offset: 1072 Size:    16 [unused]
//   float2 rcpFrame;                   // Offset: 1088 Size:     8 [unused]
//   float4 sslrParams;                 // Offset: 1104 Size:    16 [unused]
//   float3 sslrCenter;                 // Offset: 1120 Size:    12 [unused]
//   float4 ExposureParams0;            // Offset: 1136 Size:    16 [unused]
//   float4 ExposureParams1;            // Offset: 1152 Size:    16 [unused]
//   float4 ExposureParams2;            // Offset: 1168 Size:    16 [unused]
//   float4 ExposureParams3;            // Offset: 1184 Size:    16 [unused]
//   float4 LuminanceDownsampleOOSrcDstSize;// Offset: 1200 Size:    16 [unused]
//   float4 QuadPosition;               // Offset: 1216 Size:    16 [unused]
//   float4 QuadTexCoords;              // Offset: 1232 Size:    16 [unused]
//   float4 QuadScale;                  // Offset: 1248 Size:    16 [unused]
//   float4 BokehBrightnessParams;      // Offset: 1264 Size:    16 [unused]
//   float4 BokehParams1;               // Offset: 1280 Size:    16 [unused]
//   float4 BokehParams2;               // Offset: 1296 Size:    16 [unused]
//   float2 DOFTargetSize;              // Offset: 1312 Size:     8 [unused]
//   float2 RenderTargetSize;           // Offset: 1320 Size:     8 [unused]
//   float BokehGlobalAlpha;            // Offset: 1328 Size:     4 [unused]
//   float BokehAlphaCutoff;            // Offset: 1332 Size:     4 [unused]
//   bool BokehEnableVar;               // Offset: 1336 Size:     4 [unused]
//   float BokehSortLevel;              // Offset: 1340 Size:     4 [unused]
//   float BokehSortLevelMask;          // Offset: 1344 Size:     4 [unused]
//   float BokehSortTransposeMatWidth;  // Offset: 1348 Size:     4 [unused]
//   float BokehSortTransposeMatHeight; // Offset: 1352 Size:     4 [unused]
//   float currentDOFTechnique;         // Offset: 1356 Size:     4 [unused]
//   float4 fpvMotionBlurWeights;       // Offset: 1360 Size:    16 [unused]
//   float3 fpvMotionBlurVelocity;      // Offset: 1376 Size:    12 [unused]
//   float fpvMotionBlurSize;           // Offset: 1388 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// HDRSampler                        sampler      NA          NA             s5      1 
// HDRSampler                        texture  float4          2d             t5      1 
// postfx_cbuffer                    cbuffer      NA          NA            cb5      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB5[67], immediateIndexed
dcl_sampler s5, mode_default
dcl_resource_texture2d (float,float,float,float) t5
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 3
mov r0.xyzw, l(0,0,0,0)
loop 
  ige r1.x, r0.w, l(4)
  breakc_nz r1.x
  itof r1.x, r0.w
  mad r1.y, -r1.x, l(0.250000), l(1.000000)
  mul r1.y, r1.y, r1.y
  mul r1.xz, r1.xxxx, cb5[36].xxyx
  mad r1.xz, cb5[66].xxyx, r1.xxzx, v1.xxyx
  sample r2.xyzw, r1.xzxx, t5.xyzw, s5
  mad r0.xyz, r2.xyzx, r1.yyyy, r0.xyzx
  iadd r0.w, r0.w, l(1)
endloop 
mul r0.xyz, r0.xyzx, cb5[34].xyzx
lt r0.w, l(0.000000), cb5[29].y
add r1.xy, v1.yxyy, l(-0.500000, -0.500000, 0.000000, 0.000000)
movc r0.w, r0.w, |r1.x|, |r1.y|
add r0.w, r0.w, r0.w
add r1.x, -cb5[29].z, cb5[29].w
mad r0.w, r1.x, r0.w, cb5[29].z
mul r0.w, r0.w, r0.w
mul o0.xyz, r0.wwww, r0.xyzx
mov o0.w, l(1.000000)
ret 
// Approximately 24 instruction slots used
