//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16 [unused]
//   float4 globalScalars2;             // Offset:  192 Size:    16 [unused]
//   float4 globalScalars3;             // Offset:  208 Size:    16
//   float4 globalScreenSize;           // Offset:  224 Size:    16
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer postfx_cbuffer
// {
//
//   float4 dofProj;                    // Offset:    0 Size:    16
//   float4 dofShear;                   // Offset:   16 Size:    16 [unused]
//   float4 dofDist;                    // Offset:   32 Size:    16 [unused]
//   float4 hiDofParams;                // Offset:   48 Size:    16
//   float4 hiDofMiscParams;            // Offset:   64 Size:    16
//   float4 PostFXAdaptiveDofEnvBlurParams;// Offset:   80 Size:    16 [unused]
//   float4 PostFXAdaptiveDofCustomPlanesParams;// Offset:   96 Size:    16 [unused]
//   float4 BloomParams;                // Offset:  112 Size:    16 [unused]
//   float4 Filmic0;                    // Offset:  128 Size:    16
//   float4 Filmic1;                    // Offset:  144 Size:    16
//   float4 NoiseParams;                // Offset:  160 Size:    16
//   float4 DirectionalMotionBlurParams;// Offset:  176 Size:    16 [unused]
//   float4 MBPrevViewProjMatrixX;      // Offset:  192 Size:    16 [unused]
//   float4 MBPrevViewProjMatrixY;      // Offset:  208 Size:    16 [unused]
//   float4 MBPrevViewProjMatrixW;      // Offset:  224 Size:    16 [unused]
//   float3 MBPerspectiveShearParams0;  // Offset:  240 Size:    12 [unused]
//   float3 MBPerspectiveShearParams1;  // Offset:  256 Size:    12 [unused]
//   float3 MBPerspectiveShearParams2;  // Offset:  272 Size:    12 [unused]
//   float lowLum;                      // Offset:  284 Size:     4
//   float highLum;                     // Offset:  288 Size:     4
//   float topLum;                      // Offset:  292 Size:     4
//   float scalerLum;                   // Offset:  296 Size:     4
//   float offsetLum;                   // Offset:  300 Size:     4
//   float offsetLowLum;                // Offset:  304 Size:     4
//   float offsetHighLum;               // Offset:  308 Size:     4
//   float noiseLum;                    // Offset:  312 Size:     4
//   float noiseLowLum;                 // Offset:  316 Size:     4
//   float noiseHighLum;                // Offset:  320 Size:     4
//   float bloomLum;                    // Offset:  324 Size:     4
//   float4 colorLum;                   // Offset:  336 Size:    16
//   float4 colorLowLum;                // Offset:  352 Size:    16
//   float4 colorHighLum;               // Offset:  368 Size:    16
//   float4 HeatHazeParams;             // Offset:  384 Size:    16 [unused]
//   float4 HeatHazeTex1Params;         // Offset:  400 Size:    16 [unused]
//   float4 HeatHazeTex2Params;         // Offset:  416 Size:    16 [unused]
//   float4 HeatHazeOffsetParams;       // Offset:  432 Size:    16 [unused]
//   float4 LensArtefactsParams0;       // Offset:  448 Size:    16 [unused]
//   float4 LensArtefactsParams1;       // Offset:  464 Size:    16 [unused]
//   float4 LensArtefactsParams2;       // Offset:  480 Size:    16 [unused]
//   float4 LensArtefactsParams3;       // Offset:  496 Size:    16 [unused]
//   float4 LensArtefactsParams4;       // Offset:  512 Size:    16 [unused]
//   float4 LensArtefactsParams5;       // Offset:  528 Size:    16 [unused]
//   float4 LightStreaksColorShift0;    // Offset:  544 Size:    16 [unused]
//   float4 LightStreaksBlurColWeights; // Offset:  560 Size:    16 [unused]
//   float4 LightStreaksBlurDir;        // Offset:  576 Size:    16 [unused]
//   float4 globalFreeAimDir;           // Offset:  592 Size:    16 [unused]
//   float4 globalFogRayParam;          // Offset:  608 Size:    16 [unused]
//   float4 globalFogRayFadeParam;      // Offset:  624 Size:    16 [unused]
//   float4 lightrayParams;             // Offset:  640 Size:    16
//   float4 lightrayParams2;            // Offset:  656 Size:    16 [unused]
//   float4 seeThroughParams;           // Offset:  672 Size:    16 [unused]
//   float4 seeThroughColorNear;        // Offset:  688 Size:    16 [unused]
//   float4 seeThroughColorFar;         // Offset:  704 Size:    16 [unused]
//   float4 seeThroughColorVisibleBase; // Offset:  720 Size:    16 [unused]
//   float4 seeThroughColorVisibleWarm; // Offset:  736 Size:    16 [unused]
//   float4 seeThroughColorVisibleHot;  // Offset:  752 Size:    16 [unused]
//   float4 debugParams0;               // Offset:  768 Size:    16 [unused]
//   float4 debugParams1;               // Offset:  784 Size:    16 [unused]
//   float PLAYER_MASK;                 // Offset:  800 Size:     4 [unused]
//   float4 VignettingParams;           // Offset:  816 Size:    16 [unused]
//   float4 VignettingColor;            // Offset:  832 Size:    16 [unused]
//   float4 GradientFilterColTop;       // Offset:  848 Size:    16 [unused]
//   float4 GradientFilterColBottom;    // Offset:  864 Size:    16 [unused]
//   float4 GradientFilterColMiddle;    // Offset:  880 Size:    16 [unused]
//   float4 DamageOverlayMisc;          // Offset:  896 Size:    16 [unused]
//   float4 ScanlineFilterParams;       // Offset:  912 Size:    16 [unused]
//   float ScreenBlurFade;              // Offset:  928 Size:     4 [unused]
//   float4 ColorCorrectHighLum;        // Offset:  944 Size:    16
//   float4 ColorShiftLowLum;           // Offset:  960 Size:    16
//   float Desaturate;                  // Offset:  976 Size:     4
//   float Gamma;                       // Offset:  980 Size:     4 [unused]
//   float4 LensDistortionParams;       // Offset:  992 Size:    16 [unused]
//   float4 DistortionParams;           // Offset: 1008 Size:    16 [unused]
//   float4 BlurVignettingParams;       // Offset: 1024 Size:    16 [unused]
//   float4 BloomTexelSize;             // Offset: 1040 Size:    16 [unused]
//   float4 TexelSize;                  // Offset: 1056 Size:    16
//   float4 GBufferTexture0Param;       // Offset: 1072 Size:    16 [unused]
//   float2 rcpFrame;                   // Offset: 1088 Size:     8 [unused]
//   float4 sslrParams;                 // Offset: 1104 Size:    16
//   float3 sslrCenter;                 // Offset: 1120 Size:    12 [unused]
//   float4 ExposureParams0;            // Offset: 1136 Size:    16 [unused]
//   float4 ExposureParams1;            // Offset: 1152 Size:    16 [unused]
//   float4 ExposureParams2;            // Offset: 1168 Size:    16 [unused]
//   float4 ExposureParams3;            // Offset: 1184 Size:    16 [unused]
//   float4 LuminanceDownsampleOOSrcDstSize;// Offset: 1200 Size:    16 [unused]
//   float4 QuadPosition;               // Offset: 1216 Size:    16 [unused]
//   float4 QuadTexCoords;              // Offset: 1232 Size:    16 [unused]
//   float4 QuadScale;                  // Offset: 1248 Size:    16 [unused]
//   float4 BokehBrightnessParams;      // Offset: 1264 Size:    16 [unused]
//   float4 BokehParams1;               // Offset: 1280 Size:    16 [unused]
//   float4 BokehParams2;               // Offset: 1296 Size:    16 [unused]
//   float2 DOFTargetSize;              // Offset: 1312 Size:     8 [unused]
//   float2 RenderTargetSize;           // Offset: 1320 Size:     8 [unused]
//   float BokehGlobalAlpha;            // Offset: 1328 Size:     4 [unused]
//   float BokehAlphaCutoff;            // Offset: 1332 Size:     4 [unused]
//   bool BokehEnableVar;               // Offset: 1336 Size:     4
//   float BokehSortLevel;              // Offset: 1340 Size:     4 [unused]
//   float BokehSortLevelMask;          // Offset: 1344 Size:     4 [unused]
//   float BokehSortTransposeMatWidth;  // Offset: 1348 Size:     4 [unused]
//   float BokehSortTransposeMatHeight; // Offset: 1352 Size:     4 [unused]
//   float currentDOFTechnique;         // Offset: 1356 Size:     4
//   float4 fpvMotionBlurWeights;       // Offset: 1360 Size:    16 [unused]
//   float3 fpvMotionBlurVelocity;      // Offset: 1376 Size:    12 [unused]
//   float fpvMotionBlurSize;           // Offset: 1388 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// BlurSampler                       sampler      NA          NA             s7      1 
// MotionBlurSampler                 sampler      NA          NA             s9      1 
// BloomSampler                      sampler      NA          NA            s10      1 
// BloomSamplerG                     sampler      NA          NA            s11      1 
// SSLRSampler                       sampler      NA          NA            s15      1 
// gbufferTextureDepth               texture   float        2dMS             t3      1 
// HDRTextureAA                      texture  float4        2dMS             t5      1 
// BlurSampler                       texture  float4          2d             t7      1 
// MotionBlurSampler                 texture  float4          2d             t9      1 
// BloomSampler                      texture  float4          2d            t10      1 
// BloomSamplerG                     texture  float4          2d            t11      1 
// SSLRSampler                       texture  float4          2d            t15      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// postfx_cbuffer                    cbuffer      NA          NA            cb5      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// SV_SampleIndex           0   x           2   SAMPLE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
// Pixel Shader runs at sample frequency
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[15], immediateIndexed
dcl_constantbuffer CB5[85], immediateIndexed
dcl_sampler s7, mode_default
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_sampler s15, mode_default
dcl_resource_texture2dms(0) (float,float,float,float) t3
dcl_resource_texture2dms(0) (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v1.xyzw
dcl_input_ps_sgv constant v2.x, sampleIndex
dcl_output o0.xyzw
dcl_temps 6
mul r0.xy, v1.xyxx, cb2[14].xyxx
ftoi r0.xy, r0.xyxx
mov r0.zw, l(0,0,0,0)
ldms r1.xyz, r0.xyww, t5.xyzw, v2.x
mul r1.xyz, r1.xyzx, cb2[13].wwww
lt r1.w, l(0.000000), cb5[84].w
if_z r1.w
  ldms r0.x, r0.xyzw, t3.xyzw, v2.x
  add r0.x, -r0.x, cb5[0].w
  add r0.x, r0.x, l(1.000000)
  div r0.x, cb5[0].z, r0.x
  mad r2.xyzw, cb5[66].xyxy, l(-1.000000, -0.500000, 0.500000, -1.000000), v1.xyxy
  sample r0.yzw, r2.xyxx, t9.wxyz, s9
  sample r2.xyz, r2.zwzz, t9.xyzw, s9
  mad r3.xyzw, cb5[66].xyxy, l(-0.500000, 1.000000, 1.000000, 0.500000), v1.xyxy
  sample r4.xyz, r3.xyxx, t9.xyzw, s9
  sample r3.xyz, r3.zwzz, t9.xyzw, s9
  sample r5.xyz, v1.xyxx, t9.xyzw, s9
  add r0.yzw, r0.yyzw, r2.xxyz
  add r0.yzw, r4.xxyz, r0.yyzw
  add r0.yzw, r3.xxyz, r0.yyzw
  mad r0.yzw, r5.xxyz, l(0.000000, 0.500000, 0.500000, 0.500000), r0.yyzw
  mul r0.yzw, r0.yyzw, l(0.000000, 0.222222, 0.222222, 0.222222)
  ne r1.w, cb5[4].x, l(0.000000)
  movc r0.yzw, r1.wwww, r5.xxyz, r0.yyzw
  add r2.xy, r0.xxxx, -cb5[3].xzxx
  mul r0.x, r2.y, cb5[3].w
  mad_sat r1.w, -r2.x, cb5[3].y, l(1.000000)
  mov_sat r0.x, r0.x
  max r0.x, r0.x, r1.w
  mad_sat r2.xyzw, r0.xxxx, l(-2.004008, -2.004008, -1000.000000, 1000.000000), l(1.000000, 2.002004, 1000.000000, -999.000000)
  add r3.xy, -r2.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
  min r2.yz, r2.yyzy, r3.xxyx
  mul r3.xyz, r2.yyyy, r5.xyzx
  mad r3.xyz, r1.xyzx, r2.xxxx, r3.xyzx
  mad r2.xyz, r0.yzwy, r2.zzzz, r3.xyzx
  mad r1.xyz, r0.yzwy, r2.wwww, r2.xyzx
endif 
if_nz cb5[83].z
  sample r0.xyzw, v1.xyxx, t11.xyzw, s11
  add r0.xyz, -r1.xyzx, r0.xyzx
  mad r1.xyz, r0.wwww, r0.xyzx, r1.xyzx
endif 
sample r0.xyz, v1.xyxx, t10.xyzw, s10
mul r0.xyz, r0.xyzx, v1.wwww
lt r0.w, l(0.000000), cb5[69].z
if_nz r0.w
  sample r0.w, v1.xyxx, t15.yzwx, s15
  mul r0.w, r0.w, r0.w
  mul r0.w, r0.w, r0.w
  mul r0.w, r0.w, r0.w
  mad r1.xyz, cb5[40].xyzx, r0.wwww, r1.xyzx
endif 
min r1.xyz, r1.xyzx, l(65504.000000, 65504.000000, 65504.000000, 0.000000)
mul r1.xyz, r1.xyzx, v1.zzzz
max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r2.xyz, cb5[8].xxxx, r1.xyzx, cb5[9].xxxx
mad r2.xyz, r1.xyzx, r2.xyzx, cb5[9].yyyy
mad r3.xyz, cb5[8].xxxx, r1.xyzx, cb5[8].yyyy
mad r1.xyz, r1.xyzx, r3.xyzx, cb5[9].zzzz
div r1.xyz, r2.xyzx, r1.xyzx
add r1.xyz, r1.xyzx, -cb5[9].wwww
mul_sat r1.xyz, r1.xyzx, cb5[8].zzzz
dp3 r0.w, r1.xyzx, l(0.212500, 0.715400, 0.072100, 0.000000)
add r1.xyz, -r0.wwww, r1.xyzx
mad r1.xyz, cb5[61].xxxx, r1.xyzx, r0.wwww
div_sat r1.w, r0.w, cb5[60].w
add r2.xyz, cb5[59].xyzx, -cb5[60].xyzx
mad r2.xyz, r1.wwww, r2.xyzx, cb5[60].xyzx
mul r3.xyz, r1.xyzx, r2.xyzx
add r1.w, -cb5[59].w, l(1.000000)
add r0.w, r0.w, -r1.w
add r1.w, -r1.w, l(1.000000)
max r1.w, r1.w, l(0.010000)
div_sat r0.w, r0.w, r1.w
mad r1.xyz, -r1.xyzx, r2.xyzx, r1.xyzx
mad_sat r1.xyz, r0.wwww, r1.xyzx, r3.xyzx
dp3 r0.w, r1.xyzx, l(0.212500, 0.715400, 0.072100, 0.000000)
mul r1.x, r0.w, cb5[18].z
div_sat r1.x, r1.x, cb5[17].w
add r1.x, -r1.x, l(1.000000)
mad r1.y, r0.w, cb5[18].z, -cb5[18].x
add r1.z, -cb5[18].x, cb5[18].y
div_sat r1.y, r1.y, r1.z
add r1.z, r1.y, r1.x
add r1.z, -r1.z, l(1.000000)
mul r2.xy, r1.xxxx, cb5[19].xwxx
mad r1.w, r1.y, cb5[19].y, r2.x
mad r1.w, r1.z, cb5[18].w, r1.w
mad r0.w, r0.w, cb5[18].z, r1.w
mad r2.xz, v1.xxyx, l(2.400000, 0.000000, 1.350000, 0.000000), cb5[10].xxyx
frc r2.xz, r2.xxzx
sample r2.x, r2.xzxx, t7.yxzw, s7
mad r2.y, r1.z, cb5[19].z, r2.y
add r2.x, r2.x, l(-0.500000)
mad r0.w, r2.x, r2.y, r0.w
mul r2.y, r1.y, cb5[20].x
mul r2.x, r2.y, r2.x
max r2.x, r2.x, l(0.000000)
add r0.w, r0.w, r2.x
mul r0.xyz, r0.xyzx, v1.zzzz
max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mad r2.xyz, cb5[8].xxxx, r0.xyzx, cb5[9].xxxx
mad r2.xyz, r0.xyzx, r2.xyzx, cb5[9].yyyy
mad r3.xyz, cb5[8].xxxx, r0.xyzx, cb5[8].yyyy
mad r0.xyz, r0.xyzx, r3.xyzx, cb5[9].zzzz
div r0.xyz, r2.xyzx, r0.xyzx
add r0.xyz, r0.xyzx, -cb5[9].wwww
mul_sat r0.xyz, r0.xyzx, cb5[8].zzzz
dp3 r0.x, r0.xyzx, l(0.212500, 0.715400, 0.072100, 0.000000)
mad r0.x, r0.x, cb5[18].z, r1.w
add r0.x, -r1.y, r0.x
max r0.x, r0.x, l(0.000000)
mad r0.x, r0.x, cb5[20].y, r0.w
mul r0.yzw, r1.yyyy, cb5[23].xxyz
mad r0.yzw, r1.xxxx, cb5[22].xxyz, r0.yyzw
mad r0.yzw, r1.zzzz, cb5[21].xxyz, r0.yyzw
mul_sat r0.xyz, r0.xxxx, r0.yzwy
dp3 o0.w, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
mov o0.xyz, r0.xyzx
ret 
// Approximately 121 instruction slots used
