//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16 [unused]
//   float4 globalScalars2;             // Offset:  192 Size:    16 [unused]
//   float4 globalScalars3;             // Offset:  208 Size:    16
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer rage_SoftParticleBuffer
// {
//
//   float4 NearFarPlane;               // Offset:    0 Size:    16
//   float4 gInvScreenSize;             // Offset:   16 Size:    16
//
// }
//
// cbuffer ptfx_common_locals
// {
//
//   float4 deferredLightScreenSize;    // Offset:    0 Size:    16 [unused]
//   float4 deferredProjectionParams;   // Offset:   16 Size:    16 [unused]
//   float3 deferredPerspectiveShearParams0;// Offset:   32 Size:    12 [unused]
//   float3 deferredPerspectiveShearParams1;// Offset:   48 Size:    12 [unused]
//   float3 deferredPerspectiveShearParams2;// Offset:   64 Size:    12 [unused]
//   float4 postProcess_FlipDepth_NearPlaneFade_Params;// Offset:   80 Size:    16
//   float4 waterfogPtfxParams;         // Offset:   96 Size:    16 [unused]
//   float4 activeShadowCascades;       // Offset:  112 Size:    16 [unused]
//   float4 numActiveShadowCascades;    // Offset:  128 Size:    16 [unused]
//
// }
//
// cbuffer ptxgpu_render_locals
// {
//
//   float gLightIntensityMult;         // Offset:    0 Size:     4 [unused]
//   float4 gTextureRowsColsStartEnd;   // Offset:   16 Size:    16 [unused]
//   float4 gTextureAnimRateScaleOverLifeStart2End2;// Offset:   32 Size:    16 [unused]
//   float4 gSizeMinRange;              // Offset:   48 Size:    16 [unused]
//   float4 gColour;                    // Offset:   64 Size:    16 [unused]
//   float2 gFadeInOut;                 // Offset:   80 Size:     8 [unused]
//   float2 gRotSpeedMinRange;          // Offset:   88 Size:     8 [unused]
//   float3 gDirectionalZOffsetMinRange;// Offset:   96 Size:    12 [unused]
//   float2 gFadeNearFar;               // Offset:  112 Size:     8 [unused]
//   float3 gFadeZBaseLoHi;             // Offset:  128 Size:    12 [unused]
//   float3 gDirectionalVelocityAdd;    // Offset:  144 Size:    12 [unused]
//   float gEdgeSoftness;               // Offset:  156 Size:     4
//   float gMaxLife;                    // Offset:  160 Size:     4 [unused]
//   float3 gRefParticlePos;            // Offset:  164 Size:    12 [unused]
//   float gParticleColorPercentage;    // Offset:  176 Size:     4 [unused]
//   float gBackgroundDistortionVisibilityPercentage;// Offset:  180 Size:     4
//   float gBackgroundDistortionAlphaBooster;// Offset:  184 Size:     4 [unused]
//   float gBackgroundDistortionAmount; // Offset:  188 Size:     4
//   float gDirectionalLightShadowAmount;// Offset:  192 Size:     4 [unused]
//   float gLocalLightsMultiplier;      // Offset:  196 Size:     4 [unused]
//   float4 gCamAngleLimits;            // Offset:  208 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s7      1 
// BackBufferSampler                 sampler      NA          NA             s8      1 
// DistortionSampler                 sampler      NA          NA             s9      1 
// DepthMapTexSampler                sampler      NA          NA            s12      1 
// DiffuseSampler                    texture  float4          2d             t7      1 
// BackBufferSampler                 texture  float4          2d             t8      1 
// DistortionSampler                 texture  float4          2d             t9      1 
// DepthMapTexSampler                texture  float4          2d            t12      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// rage_SoftParticleBuffer           cbuffer      NA          NA            cb7      1 
// ptxgpu_render_locals              cbuffer      NA          NA            cb8      1 
// ptfx_common_locals                cbuffer      NA          NA           cb10      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyz         0     NONE   float       
// TEXCOORD                 1   xy          1     NONE   float   xy  
// TEXCOORD                 3     zw        1     NONE   float       
// TEXCOORD                 2   xyz         2     NONE   float       
// TEXCOORD                 4   xyzw        3     NONE   float   xyzw
// TEXCOORD                 5   xyzw        4     NONE   float   xyzw
// TEXCOORD                 6   xy          5     NONE   float       
// SV_Position              0   xyzw        6      POS   float   xyz 
// SV_ClipDistance          0   xyzw        7  CLIPDST   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB2[14], immediateIndexed
dcl_constantbuffer CB7[2], immediateIndexed
dcl_constantbuffer CB10[6], immediateIndexed
dcl_constantbuffer CB8[12], immediateIndexed
dcl_sampler s7, mode_default
dcl_sampler s8, mode_default
dcl_sampler s9, mode_default
dcl_sampler s12, mode_default
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t12
dcl_input_ps linear v1.xy
dcl_input_ps constant v3.xyzw
dcl_input_ps linear v4.xyzw
dcl_input_ps_siv linear noperspective v6.xyz, position
dcl_output o0.xyzw
dcl_temps 3
sample r0.xyzw, v1.xyxx, t7.xyzw, s7
mul r0.x, r0.w, v3.w
mul r0.yz, v6.xxyx, cb7[1].xxyx
lt r0.w, l(0.000000), cb8[11].w
if_nz r0.w
  mad r0.w, -v6.z, v6.z, l(1.000000)
  sample r1.xyzw, v1.xyxx, t9.xyzw, s9
  mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  mul r1.xy, r1.xyxx, r1.zzzz
  mul r1.xy, r1.xyxx, cb7[1].xyxx
  mul r0.w, r0.w, cb8[11].w
  mul r1.xy, r0.wwww, r1.xyxx
else 
  mov r1.xy, l(0,0,0,0)
endif 
mad r1.xy, v6.xyxx, cb7[1].xyxx, r1.xyxx
sample r1.xyzw, r1.xyxx, t8.xyzw, s8
mul r1.xyz, r1.xyzx, cb8[11].yyyy
mad r1.xyz, v3.xyzx, v4.xyzx, r1.xyzx
sample r2.xyzw, r0.yzyy, t12.xyzw, s12
add r0.y, -r2.x, l(1.000000)
ne r0.z, l(0.000000, 0.000000, 0.000000, 0.000000), cb10[5].z
add r0.w, -r0.y, l(1.000000)
movc r0.y, r0.z, r0.w, r0.y
add r0.y, -r0.y, l(1.000000)
mad r0.y, r0.y, cb7[0].z, cb7[0].w
div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
add r0.y, r0.y, -v4.w
mul r0.y, r0.y, r0.y
mul_sat r0.y, r0.y, cb8[9].w
mul o0.w, r0.y, r0.x
mul o0.xyz, r1.xyzx, cb2[13].zzzz
ret 
// Approximately 33 instruction slots used
