//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer radar_locals
// {
//
//   float4 diffuseCol;                 // Offset:    0 Size:    16
//   float4 clippingPlane;              // Offset:   16 Size:    16
//   float4 targetSize;                 // Offset:   32 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// radar_locals                      cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
// TEXCOORD                 1   xyzw        3     NONE   float   xyz 
// TEXCOORD                 2   x           4     NONE    uint       
// TEXCOORD                 6   xyz         5     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB12[2], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xy
dcl_input_ps linear v3.xyz
dcl_input_ps linear noperspective v5.xyz
dcl_output o0.xyzw
dcl_temps 2
mov r0.xyz, v3.xyzx
mov r0.w, l(1.000000)
dp4 r0.x, r0.xyzw, cb12[1].xyzw
ge r0.x, r0.x, l(0.000000)
and r0.x, r0.x, l(0x3f800000)
sample r1.xyzw, v2.xyxx, t0.xyzw, s0
mul r1.xyzw, r1.xyzw, v1.xyzw
mul r1.xyzw, r1.xyzw, cb12[0].xyzw
mul r0.x, r0.x, r1.w
mov o0.xyz, r1.xyzx
min r0.y, v5.y, v5.x
min_sat r0.y, r0.y, v5.z
mul o0.w, r0.y, r0.x
ret 
// Approximately 14 instruction slots used
