//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rmptfx_common_locals
// {
//
//   float HybridAdd;                   // Offset:    0 Size:     4
//   float gBiasToCamera;               // Offset:    4 Size:     4 [unused]
//   float gHybridAddRatio;             // Offset:    8 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseTexSampler                 sampler      NA          NA             s0      1 
// DiffuseTexSampler                 texture  float4          2d             t0      1 
// rmptfx_common_locals              cbuffer      NA          NA           cb13      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xy  
// TEXCOORD                 1   xyzw        3     NONE   float       
// TEXCOORD                 2   xyzw        4     NONE   float       
// TEXCOORD                 3   xyzw        5     NONE   float   x   
// TEXCOORD                 4   xyzw        6     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB13[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xy
dcl_input_ps linear v5.x
dcl_output o0.xyzw
dcl_temps 3
ne r0.x, l(0.000000, 0.000000, 0.000000, 0.000000), cb13[0].x
add r0.y, -v5.x, l(1.000000)
sample r1.xyzw, v2.xyxx, t0.xyzw, s0
mul r1.xyzw, r1.xyzw, v1.xyzw
mul r2.w, r0.y, r1.w
mul r2.xyz, r1.wwww, r1.xyzx
movc o0.xyzw, r0.xxxx, r2.xyzw, r1.xyzw
ret 
// Approximately 8 instruction slots used
