//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer sky_system_locals
// {
//
//   float3 azimuthEastColor;           // Offset:    0 Size:    12 [unused]
//   float3 azimuthWestColor;           // Offset:   16 Size:    12 [unused]
//   float3 azimuthTransitionColor;     // Offset:   32 Size:    12 [unused]
//   float azimuthTransitionPosition;   // Offset:   44 Size:     4 [unused]
//   float3 zenithColor;                // Offset:   48 Size:    12 [unused]
//   float3 zenithTransitionColor;      // Offset:   64 Size:    12 [unused]
//   float4 zenithConstants;            // Offset:   80 Size:    16 [unused]
//   float4 skyPlaneColor;              // Offset:   96 Size:    16 [unused]
//   float4 skyPlaneParams;             // Offset:  112 Size:    16 [unused]
//   float hdrIntensity;                // Offset:  128 Size:     4 [unused]
//   float3 sunColor;                   // Offset:  132 Size:    12 [unused]
//   float3 sunColorHdr;                // Offset:  144 Size:    12
//   float3 sunDiscColorHdr;            // Offset:  160 Size:    12 [unused]
//   float4 sunConstants;               // Offset:  176 Size:    16
//   float3 sunDirection;               // Offset:  192 Size:    12
//   float3 sunPosition;                // Offset:  208 Size:    12 [unused]
//   float3 cloudBaseMinusMidColour;    // Offset:  224 Size:    12
//   float3 cloudMidColour;             // Offset:  240 Size:    12
//   float3 cloudShadowMinusBaseColourTimesShadowStrength;// Offset:  256 Size:    12
//   float4 cloudDetailConstants;       // Offset:  272 Size:    16
//   float4 cloudConstants1;            // Offset:  288 Size:    16
//   float4 cloudConstants2;            // Offset:  304 Size:    16
//   float4 smallCloudConstants;        // Offset:  320 Size:    16
//   float3 smallCloudColorHdr;         // Offset:  336 Size:    12
//   float4 effectsConstants;           // Offset:  352 Size:    16 [unused]
//   float horizonLevel;                // Offset:  368 Size:     4 [unused]
//   float3 speedConstants;             // Offset:  372 Size:    12 [unused]
//   float starfieldIntensity;          // Offset:  384 Size:     4 [unused]
//   float3 moonDirection;              // Offset:  388 Size:    12 [unused]
//   float3 moonPosition;               // Offset:  400 Size:    12 [unused]
//   float moonIntensity;               // Offset:  412 Size:     4 [unused]
//   float3 lunarCycle;                 // Offset:  416 Size:    12 [unused]
//   float3 moonColor;                  // Offset:  432 Size:    12 [unused]
//   float noiseFrequency;              // Offset:  444 Size:     4 [unused]
//   float noiseScale;                  // Offset:  448 Size:     4 [unused]
//   float noiseThreshold;              // Offset:  452 Size:     4 [unused]
//   float noiseSoftness;               // Offset:  456 Size:     4 [unused]
//   float noiseDensityOffset;          // Offset:  460 Size:     4 [unused]
//   float2 noisePhase;                 // Offset:  464 Size:     8 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// perlinSampler                     sampler      NA          NA             s3      1 
// highDetailSampler                 sampler      NA          NA             s4      1 
// ditherSampler                     sampler      NA          NA             s6      1 
// perlinSampler                     texture  float4          2d             t3      1 
// highDetailSampler                 texture  float4          2d             t4      1 
// ditherSampler                     texture  float4          2d             t6      1 
// sky_system_locals                 cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 2   xyzw        3     NONE   float   xyz 
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// TEXCOORD                 5   xy          6     NONE   float       
// TEXCOORD                 6   xyzw        7     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB12[22], immediateIndexed
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s6, mode_default
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t6
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v7.xyzw
dcl_output o0.xyzw
dcl_temps 5
sample r0.xyzw, v4.xyxx, t4.xyzw, s4
add r0.x, r0.x, l(-0.500000)
mul r0.x, r0.x, cb12[17].x
sample r1.xyzw, v5.zwzz, t4.xyzw, s4
add r0.z, r1.x, l(-0.500000)
mul r0.y, r0.z, cb12[20].y
sample r1.xyzw, v4.zwzz, t4.xyzw, s4
add r1.x, r1.x, l(-0.500000)
mul r0.z, r1.x, cb12[19].z
sample r2.xyzw, v1.zwzz, t3.xyzw, s3
mad r0.z, r0.z, cb12[17].z, r2.x
mul r0.z, r0.z, cb12[18].x
sample r3.xyzw, v1.xyxx, t3.xyzw, s3
mul r0.z, r0.z, r3.x
mad_sat r0.w, -r0.z, l(2.000000), l(1.000000)
mul r0.xy, r0.wwww, r0.xyxx
mul r0.xy, r3.zzzz, r0.xyxx
mov r4.x, cb12[17].z
mov r4.y, cb12[20].y
add r1.y, -r3.z, l(1.000000)
mad r0.xy, r1.xyxx, r4.xyxx, r0.xyxx
add r0.w, r0.x, r2.y
mad r1.xyz, r0.wwww, cb12[16].xyzx, cb12[14].xyzx
mad r1.xyz, r0.zzzz, r1.xyzx, cb12[15].xyzx
mov r3.y, l(0)
add r0.xy, r0.xyxx, r3.xyxx
mul r2.x, r0.x, cb12[18].y
mul r2.y, r0.y, cb12[20].z
mov r0.y, -cb12[20].w
mov r0.xz, -cb12[18].zzwz
add_sat r0.xy, r0.xyxx, r2.xyxx
mul r0.xy, r0.xyxx, r0.xyxx
dp4 r0.w, v2.xyzw, v2.xyzw
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, v2.xyzx
mad_sat r0.z, r2.z, l(5.000000), r0.z
dp3 r0.w, r2.xyzx, -cb12[12].xyzx
mul r0.xy, r0.zzzz, r0.xyxx
mad r0.z, -cb12[11].x, r0.w, cb12[11].y
mad r0.w, r0.w, r0.w, l(1.000000)
log r0.z, |r0.z|
mul r0.z, r0.z, l(1.500000)
exp r0.z, r0.z
div r0.z, r0.w, r0.z
mul r0.w, r0.z, cb12[11].z
mad_sat r0.z, -r0.z, cb12[11].z, l(1.000000)
mov_sat r0.w, r0.w
mul r2.xyz, r0.wwww, cb12[9].xyzx
mul r2.xyz, r2.xyzx, cb12[11].wwww
mad r2.xyz, v3.xyzx, r0.zzzz, r2.xyzx
add r3.xyz, -r2.xyzx, cb12[21].xyzx
mad r2.xyz, r0.yyyy, r3.xyzx, r2.xyzx
mad r1.xyz, r1.xyzx, cb12[19].wwww, -r2.xyzx
mad r1.xyz, r0.xxxx, r1.xyzx, r2.xyzx
add r0.x, r0.y, r0.x
add_sat o0.w, -r0.x, v2.w
add r0.xyz, -r1.xyzx, v7.xyzx
mad r0.xyz, v7.wwww, r0.xyzx, r1.xyzx
sample r1.xyzw, v5.xyxx, t6.xyzw, s6
add r0.w, r1.x, l(-0.500000)
mad o0.xyz, r0.wwww, l(0.000100, 0.000100, 0.000100, 0.000000), r0.xyzx
ret 
// Approximately 62 instruction slots used
