//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16
//   float4 gDirectionalColour;         // Offset:   16 Size:    16
//   int gNumForwardLights;             // Offset:   32 Size:     4 [unused]
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128 [unused]
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128 [unused]
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128 [unused]
//   float gLightConeScale[8];          // Offset:  432 Size:   116 [unused]
//   float gLightConeOffset[8];         // Offset:  560 Size:   116 [unused]
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80
//   float4 globalFogColor;             // Offset:  880 Size:    16
//   float4 globalFogColorE;            // Offset:  896 Size:    16
//   float4 globalFogColorN;            // Offset:  912 Size:    16
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer terrain_cb_common_locals
// {
//
//   float specularFalloffMult;         // Offset:    0 Size:     4 [unused]
//   float specularIntensityMult;       // Offset:    4 Size:     4
//   float bumpiness;                   // Offset:    8 Size:     4 [unused]
//   float parallaxSelfShadowAmount;    // Offset:   12 Size:     4 [unused]
//   float heightScale0;                // Offset:   16 Size:     4 [unused]
//   float heightBias0;                 // Offset:   20 Size:     4 [unused]
//   float heightScale1;                // Offset:   24 Size:     4 [unused]
//   float heightBias1;                 // Offset:   28 Size:     4 [unused]
//   float heightScale2;                // Offset:   32 Size:     4 [unused]
//   float heightBias2;                 // Offset:   36 Size:     4 [unused]
//   float heightScale3;                // Offset:   40 Size:     4 [unused]
//   float heightBias3;                 // Offset:   44 Size:     4 [unused]
//   float bumpSelfShadowAmount;        // Offset:   48 Size:     4 [unused]
//   float4 materialWetnessMultiplier;  // Offset:   64 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureSampler_layer0             sampler      NA          NA             s2      1 
// TextureSampler_layer1             sampler      NA          NA             s5      1 
// TextureSampler_layer2             sampler      NA          NA             s8      1 
// TextureSampler_layer3             sampler      NA          NA            s11      1 
// TextureSampler_layer0             texture  float4          2d             t2      1 
// TextureSampler_layer1             texture  float4          2d             t5      1 
// TextureSampler_layer2             texture  float4          2d             t8      1 
// TextureSampler_layer3             texture  float4          2d            t11      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// terrain_cb_common_locals          cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// COLOR                    0   xyzw        2     NONE   float   xyz 
// TEXCOORD                 1   xyz         3     NONE   float   xyz 
// TEXCOORD                 2   xyz         4     NONE   float   xyz 
// TEXCOORD                 3   xyzw        5     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB1[16], immediateIndexed
dcl_constantbuffer CB2[13], immediateIndexed
dcl_constantbuffer CB3[59], immediateIndexed
dcl_constantbuffer CB12[1], immediateIndexed
dcl_sampler s2, mode_default
dcl_sampler s5, mode_default
dcl_sampler s8, mode_default
dcl_sampler s11, mode_default
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t11
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xy
dcl_output o0.xyzw
dcl_temps 4
sample r0.xyzw, v1.xyxx, t2.xyzw, s2
sample r1.xyzw, v1.zwzz, t5.xyzw, s5
mov_sat r2.xyz, v2.xyzx
add r3.xyz, -r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r0.w, r3.y, r3.x
mul r1.w, r2.z, r0.w
mul r0.w, r3.z, r0.w
mul r1.xyz, r1.wwww, r1.xyzx
mad r0.xyz, r0.xyzx, r0.wwww, r1.xyzx
sample r1.xyzw, v1.zwzz, t8.xyzw, s8
mul r0.w, r2.y, r3.x
mul r1.w, r2.z, r0.w
mul r0.w, r3.z, r0.w
mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
sample r2.xyzw, v1.zwzz, t11.xyzw, s11
mad r0.xyz, r2.xyzx, r1.wwww, r0.xyzx
mul r0.xyz, r0.xyzx, r0.xyzx
mov r1.x, cb3[46].w
mov r1.y, cb3[47].w
mov r1.z, cb3[48].w
dp3_sat r0.w, r1.xyzx, v4.xyzx
add r1.x, v4.z, cb3[43].w
mul r1.x, r1.x, cb3[44].w
max r1.x, r1.x, l(0.000000)
mad r1.yzw, cb3[43].xxyz, r1.xxxx, cb3[44].xxyz
mad r1.yzw, cb3[49].xxyz, r0.wwww, r1.yyzw
mad r2.xyz, cb3[45].xyzx, r1.xxxx, cb3[46].xyzx
mad r3.xyz, cb3[47].xyzx, r1.xxxx, cb3[48].xyzx
mul r2.xyz, r2.xyzx, cb2[12].zzzz
add r0.w, -cb2[12].z, l(1.000000)
mad r2.xyz, r3.xyzx, r0.wwww, r2.xyzx
mov_sat r3.xy, v5.xyxx
mul r3.xy, r3.xyxx, cb2[11].zyzz
mul r3.xy, r3.xyxx, r3.xyxx
mul r2.xyz, r2.xyzx, r3.yyyy
mad r1.xyz, r1.yzwy, r3.xxxx, r2.xyzx
mov_sat r0.w, cb12[0].y
add r0.w, -r0.w, l(1.000000)
mul r1.xyz, r0.wwww, r1.xyzx
mul r1.xyz, r0.xyzx, r1.xyzx
dp3_sat r1.w, v4.xyzx, -cb3[0].xyzx
mul r0.w, r0.w, r1.w
mul r0.xyz, r0.wwww, r0.xyzx
mul r0.w, r3.x, r3.x
mul r0.w, r0.w, cb3[0].w
mul r2.xyz, r0.wwww, cb3[1].xyzx
mul r0.xyz, r0.xyzx, r2.xyzx
mad r0.xyz, r0.xyzx, r3.xxxx, r1.xyzx
add r1.xyz, v3.xyzx, -cb1[15].xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
sqrt r1.w, r0.w
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, r1.xyzx
add r0.w, r1.w, -cb3[50].x
max r0.w, r0.w, l(0.000000)
div r1.x, r0.w, r1.w
mul r1.x, r1.x, r1.z
mul r1.y, r1.x, cb3[52].z
lt r1.x, l(0.010000), |r1.x|
mul r1.z, r1.y, l(-1.442695)
exp r1.z, r1.z
add r1.z, -r1.z, l(1.000000)
div r1.y, r1.z, r1.y
movc r1.x, r1.x, r1.y, l(1.000000)
mul r1.y, r0.w, cb3[51].w
mul r1.x, r1.x, r1.y
min r1.x, r1.x, l(1.000000)
mul r1.x, r1.x, l(1.442695)
exp r1.x, r1.x
min r1.x, r1.x, l(1.000000)
add r1.x, -r1.x, l(1.000000)
mad r1.y, -r1.x, cb3[52].y, l(1.000000)
mul r1.x, r1.x, cb3[52].y
mul r1.y, r1.y, cb3[51].y
dp3_sat r1.z, r2.xyzx, cb3[53].xyzx
dp3_sat r1.w, r2.xyzx, cb3[54].xyzx
log r1.w, r1.w
mul r1.w, r1.w, cb3[54].w
exp r1.w, r1.w
log r1.z, r1.z
mul r1.z, r1.z, cb3[53].w
exp r1.z, r1.z
add r2.xyz, -cb3[56].xyzx, cb3[58].xyzx
mad r2.xyz, r1.wwww, r2.xyzx, cb3[56].xyzx
add r3.xyz, -r2.xyzx, cb3[55].xyzx
mad r2.xyz, r1.zzzz, r3.xyzx, r2.xyzx
add r2.xyz, r2.xyzx, -cb3[57].xyzx
mul r1.z, r0.w, -cb3[51].z
add r0.w, r0.w, -cb3[52].x
max r0.w, r0.w, l(0.000000)
mul r0.w, r0.w, cb3[51].x
mul r0.w, r0.w, l(1.442695)
exp r0.w, r0.w
add r0.w, -r0.w, l(1.000000)
mad_sat r0.w, r1.y, r0.w, r1.x
mul r1.x, r1.z, l(1.442695)
exp r1.x, r1.x
add r1.x, -r1.x, l(1.000000)
mad r1.xzw, r1.xxxx, r2.xxyz, cb3[57].xxyz
add r2.x, -r1.x, cb3[55].w
add r2.y, -r1.z, cb3[56].w
add r2.z, -r1.w, cb3[57].w
mad r1.xyz, r1.yyyy, r2.xyzx, r1.xzwx
add r1.xyz, -r0.xyzx, r1.xyzx
mad o0.xyz, r0.wwww, r1.xyzx, r0.xyzx
mov o0.w, l(1.000000)
ret 
// Approximately 107 instruction slots used
