//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16 [unused]
//   float4 gDirectionalColour;         // Offset:   16 Size:    16 [unused]
//   int gNumForwardLights;             // Offset:   32 Size:     4 [unused]
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128 [unused]
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128 [unused]
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128 [unused]
//   float gLightConeScale[8];          // Offset:  432 Size:   116 [unused]
//   float gLightConeOffset[8];         // Offset:  560 Size:   116 [unused]
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16 [unused]
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16 [unused]
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16 [unused]
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16 [unused]
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16 [unused]
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16 [unused]
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80
//   float4 globalFogColor;             // Offset:  880 Size:    16 [unused]
//   float4 globalFogColorE;            // Offset:  896 Size:    16 [unused]
//   float4 globalFogColorN;            // Offset:  912 Size:    16 [unused]
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16 [unused]
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer more_stuff
// {
//
//   float4 gEntitySelectColor[2];      // Offset:    0 Size:    32 [unused]
//   float4 gAmbientOcclusionEffect;    // Offset:   32 Size:    16 [unused]
//   float4 gDynamicBakesAndWetness;    // Offset:   48 Size:    16 [unused]
//   float4 gAlphaRefVec0;              // Offset:   64 Size:    16 [unused]
//   float4 gAlphaRefVec1;              // Offset:   80 Size:    16 [unused]
//   float gAlphaTestRef;               // Offset:   96 Size:     4 [unused]
//   bool gTreesUseDiscard;             // Offset:  100 Size:     4 [unused]
//   float gReflectionMipCount;         // Offset:  104 Size:     4 [unused]
//   bool gUseTransparencyAA;           // Offset:  108 Size:     4
//   bool gUseFogRay;                   // Offset:  112 Size:     4 [unused]
//
// }
//
// cbuffer trees_common_locals
// {
//
//   float specularFresnel;             // Offset:    0 Size:     4
//   float specularFalloffMult;         // Offset:    4 Size:     4
//   float specularIntensityMult;       // Offset:    8 Size:     4
//   float3 specMapIntMask;             // Offset:   16 Size:    12
//   float bumpiness;                   // Offset:   28 Size:     4
//   float4 umGlobalParams;             // Offset:   32 Size:    16 [unused]
//   float4 WindGlobalParams;           // Offset:   48 Size:    16 [unused]
//   float UseTreeNormals;              // Offset:   64 Size:     4
//   float SelfShadowing;               // Offset:   68 Size:     4 [unused]
//   float AlphaScale;                  // Offset:   72 Size:     4
//   float AlphaTest;                   // Offset:   76 Size:     4
//   float ShadowFalloff;               // Offset:   80 Size:     4
//   float AlphaScaleNormal;            // Offset:   84 Size:     4 [unused]
//   float AlphaClampNormal;            // Offset:   88 Size:     4 [unused]
//   float ShadowFacingOffset;          // Offset:   92 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// SpecSampler                       sampler      NA          NA             s3      1 
// BumpSampler                       sampler      NA          NA             s4      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// SpecSampler                       texture  float4          2d             t3      1 
// BumpSampler                       texture  float4          2d             t4      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// more_stuff                        cbuffer      NA          NA            cb5      1 
// trees_common_locals               cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyz         4     NONE   float   xyz 
// SV_IsFrontFace           0   x           5    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
//
ps_4_0
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000},
                              { 2, 0.250000, 0.250000, 0},
                              { 6, -0.250000, -0.250000, 0},
                              { 0, -0.125000, -0.375000, 0},
                              { 0, 0.375000, -0.125000, 0},
                              { 0, -0.375000, 0.125000, 0},
                              { 0, 0.125000, 0.375000, 0},
                              { 0, 0.062500, -0.187500, 0},
                              { 0, -0.062500, 0.187500, 0},
                              { 0, 0.312500, 0.062500, 0},
                              { 0, -0.187500, -0.312500, 0},
                              { 0, -0.312500, 0.312500, 0},
                              { 0, -0.437500, -0.062500, 0},
                              { 0, 0.187500, 0.437500, 0},
                              { 0, 0.437500, -0.437500, 0} }
dcl_constantbuffer CB2[16], immediateIndexed
dcl_constantbuffer CB3[51], immediateIndexed
dcl_constantbuffer CB5[7], immediateIndexed
dcl_constantbuffer CB12[6], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps_sgv constant v5.x, is_front_face
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_temps 5
ftou r0.xy, v0.xyxx
and r0.xy, r0.xyxx, l(1, 1, 0, 0)
ishl r0.y, r0.y, l(1)
iadd r0.x, r0.x, r0.y
dp4 r0.x, cb2[0].xyzw, icb[r0.x + 0].xyzw
lt r0.x, r0.x, l(1.000000)
discard_nz r0.x
sample r0.xyzw, v1.xyxx, t0.wxyz, s0
lt r1.x, r0.x, l(0.750000)
dp2 r1.y, v0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
frc r1.y, r1.y
lt r1.y, r1.y, l(0.500000)
and r1.x, r1.y, r1.x
ge r1.y, l(0.100000), r0.x
or r1.x, r1.y, r1.x
discard_nz r1.x
ine r1.x, cb5[6].w, l(0)
ult r1.y, l(1), cb2[15].x
and r1.x, r1.y, r1.x
if_nz r1.x
  deriv_rtx r1.xz, v1.xxyx
  deriv_rty r2.xy, v1.xyxx
  ishl r1.w, cb2[15].x, l(16)
  movc r2.z, r1.w, r1.w, cb2[15].x
  ishl r2.w, r2.z, l(8)
  movc r2.z, r2.w, r2.w, r2.z
  movc r3.xy, r1.wwww, l(15,7,0,0), l(31,23,0,0)
  movc r1.w, r2.w, r3.y, r3.x
  ishl r2.w, r2.z, l(4)
  movc r2.z, r2.w, r2.w, r2.z
  iadd r3.x, r1.w, l(-4)
  movc r1.w, r2.w, r3.x, r1.w
  ishl r2.w, r2.z, l(2)
  movc r2.z, r2.w, r2.w, r2.z
  iadd r3.x, r1.w, l(-2)
  movc r1.w, r2.w, r3.x, r1.w
  ishl r2.z, r2.z, l(1)
  iadd r2.w, r1.w, l(-1)
  movc r1.w, r2.z, r2.w, r1.w
  iadd r1.w, r1.w, l(-1)
  movc r1.w, cb2[15].x, r1.w, l(-2)
  ult r3.xyz, l(2, 3, 4, 0), cb2[15].xxxx
  if_nz cb2[15].x
    mov r2.z, icb[r1.w + 3].x
    mul r4.xy, r2.xyxx, icb[r2.z + 4].zzzz
    mad r2.zw, icb[r2.z + 4].yyyy, r1.xxxz, r4.xxxy
    add r2.zw, r2.zzzw, v1.xxxy
    sample r4.xyzw, r2.zwzz, t0.xyzw, s0
    mul r2.z, r4.w, cb12[4].z
    dp2 r2.z, r2.zzzz, cb2[11].xxxx
    lt r2.z, cb12[4].w, r2.z
    and r2.z, r2.z, l(1)
  else 
    mov r2.z, l(0)
  endif 
  if_nz r1.y
    iadd r1.y, icb[r1.w + 3].x, l(1)
    mul r4.xy, r2.xyxx, icb[r1.y + 4].zzzz
    mad r4.xy, icb[r1.y + 4].yyyy, r1.xzxx, r4.xyxx
    add r4.xy, r4.xyxx, v1.xyxx
    sample r4.xyzw, r4.xyxx, t0.xyzw, s0
    mul r1.y, r4.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(2)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  if_nz r3.x
    mov r1.y, icb[r1.w + 3].x
    mul r3.xw, r2.xxxy, icb[r1.y + 6].zzzz
    mad r3.xw, icb[r1.y + 6].yyyy, r1.xxxz, r3.xxxw
    add r3.xw, r3.xxxw, v1.xxxy
    sample r4.xyzw, r3.xwxx, t0.xyzw, s0
    mul r1.y, r4.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(4)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  if_nz r3.y
    mov r1.y, icb[r1.w + 3].x
    mul r3.xy, r2.xyxx, icb[r1.y + 7].zzzz
    mad r3.xy, icb[r1.y + 7].yyyy, r1.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v1.xyxx
    sample r4.xyzw, r3.xyxx, t0.xyzw, s0
    mul r1.y, r4.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(8)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  if_nz r3.z
    mov r1.y, icb[r1.w + 3].x
    mul r3.xy, r2.xyxx, icb[r1.y + 8].zzzz
    mad r3.xy, icb[r1.y + 8].yyyy, r1.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v1.xyxx
    sample r3.xyzw, r3.xyxx, t0.xyzw, s0
    mul r1.y, r3.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(16)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  ult r3.xyzw, l(5, 6, 7, 8), cb2[15].xxxx
  if_nz r3.x
    mov r1.y, icb[r1.w + 3].x
    mul r4.xy, r2.xyxx, icb[r1.y + 9].zzzz
    mad r4.xy, icb[r1.y + 9].yyyy, r1.xzxx, r4.xyxx
    add r4.xy, r4.xyxx, v1.xyxx
    sample r4.xyzw, r4.xyxx, t0.xyzw, s0
    mul r1.y, r4.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(32)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  if_nz r3.y
    mov r1.y, icb[r1.w + 3].x
    mul r3.xy, r2.xyxx, icb[r1.y + 10].zzzz
    mad r3.xy, icb[r1.y + 10].yyyy, r1.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v1.xyxx
    sample r4.xyzw, r3.xyxx, t0.xyzw, s0
    mul r1.y, r4.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(64)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  if_nz r3.z
    mov r1.y, icb[r1.w + 3].x
    mul r3.xy, r2.xyxx, icb[r1.y + 11].zzzz
    mad r3.xy, icb[r1.y + 11].yyyy, r1.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v1.xyxx
    sample r4.xyzw, r3.xyxx, t0.xyzw, s0
    mul r1.y, r4.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(128)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  if_nz r3.w
    iadd r1.y, icb[r1.w + 3].x, l(8)
    mul r3.xy, r2.xyxx, icb[r1.y + 4].zzzz
    mad r3.xy, icb[r1.y + 4].yyyy, r1.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v1.xyxx
    sample r3.xyzw, r3.xyxx, t0.xyzw, s0
    mul r1.y, r3.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(256)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  ult r3.xyzw, l(9, 10, 11, 12), cb2[15].xxxx
  if_nz r3.x
    iadd r1.y, icb[r1.w + 3].x, l(9)
    mul r4.xy, r2.xyxx, icb[r1.y + 4].zzzz
    mad r4.xy, icb[r1.y + 4].yyyy, r1.xzxx, r4.xyxx
    add r4.xy, r4.xyxx, v1.xyxx
    sample r4.xyzw, r4.xyxx, t0.xyzw, s0
    mul r1.y, r4.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(512)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  if_nz r3.y
    mov r1.y, icb[r1.w + 3].x
    mul r3.xy, r2.xyxx, icb[r1.y + 14].zzzz
    mad r3.xy, icb[r1.y + 14].yyyy, r1.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v1.xyxx
    sample r4.xyzw, r3.xyxx, t0.xyzw, s0
    mul r1.y, r4.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(1024)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  if_nz r3.z
    mov r1.y, icb[r1.w + 3].x
    mul r3.xy, r2.xyxx, icb[r1.y + 15].zzzz
    mad r3.xy, icb[r1.y + 15].yyyy, r1.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v1.xyxx
    sample r4.xyzw, r3.xyxx, t0.xyzw, s0
    mul r1.y, r4.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r2.w, r2.z, l(2048)
    movc r2.z, r1.y, r2.w, r2.z
  endif 
  if_nz r3.w
    mov r1.y, icb[r1.w + 3].x
    mul r3.xy, r2.xyxx, icb[r1.y + 16].zzzz
    mad r1.yw, icb[r1.y + 16].yyyy, r1.xxxz, r3.xxxy
    add r1.yw, r1.yyyw, v1.xxxy
    sample r3.xyzw, r1.ywyy, t0.xyzw, s0
    mul r1.y, r3.w, cb12[4].z
    dp2 r1.y, r1.yyyy, cb2[11].xxxx
    lt r1.y, cb12[4].w, r1.y
    iadd r1.w, r2.z, l(4096)
    movc r2.z, r1.y, r1.w, r2.z
  endif 
  ult r1.y, l(13), cb2[15].x
  if_nz r1.y
    mul r1.yw, r2.xxxy, l(0.000000, -0.437500, 0.000000, -0.437500)
    mad r1.xy, r1.xzxx, l(0.437500, 0.437500, 0.000000, 0.000000), r1.ywyy
    add r1.xy, r1.xyxx, v1.xyxx
    sample r1.xyzw, r1.xyxx, t0.xyzw, s0
    mul r1.x, r1.w, cb12[4].z
    dp2 r1.x, r1.xxxx, cb2[11].xxxx
    lt r1.x, cb12[4].w, r1.x
    iadd r1.y, r2.z, l(8192)
    movc r2.z, r1.x, r1.y, r2.z
  endif 
  ieq r1.x, r2.z, l(0)
  discard_nz r1.x
  mov r0.x, l(1.000000)
else 
  add r1.x, r0.x, l(-0.100000)
  mad_sat r1.x, r1.x, l(1.538462), l(0.003922)
  mul r1.y, cb2[11].x, cb12[4].z
  dp2 r0.x, r1.yyyy, r1.xxxx
  ge r1.x, cb12[4].w, r0.x
  discard_nz r1.x
endif 
ne r1.x, l(0.000000, 0.000000, 0.000000, 0.000000), cb3[50].w
movc r1.y, v5.x, l(0), l(1)
iadd r1.y, v5.x, r1.y
itof r1.y, r1.y
movc r1.x, r1.x, r1.y, l(1.000000)
mul r1.xyz, r1.xxxx, v2.xyzx
sample r2.xyzw, v1.xyxx, t4.xyzw, s4
mad r2.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r1.w, r2.xyxx, r2.xyxx
add r1.w, -r1.w, l(1.000000)
sqrt r1.w, |r1.w|
max r2.z, cb12[1].w, l(0.001000)
mul r2.xy, r2.zzzz, r2.xyxx
mul r2.yzw, r2.yyyy, v4.xxyz
mad r2.xyz, r2.xxxx, v3.xyzx, r2.yzwy
mad r1.xyz, r1.wwww, r1.xyzx, r2.xyzx
dp3 r1.w, r1.xyzx, r1.xyzx
rsq r1.w, r1.w
mad r1.xyz, r1.xyzx, r1.wwww, l(-0.000000, -0.000000, -1.000000, 0.000000)
mad r1.xyz, cb12[4].xxxx, r1.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
sample r2.xyzw, v1.xyxx, t3.xyzw, s3
mul r1.w, r2.w, cb12[0].y
dp3 r2.x, r2.xyzx, cb12[1].xyzx
mul r2.x, r2.x, cb12[0].z
mul o2.x, r2.x, l(4.000000)
mul r1.w, r1.w, l(0.001953)
sqrt o2.y, r1.w
mad o1.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
mul r1.xy, v1.zzzz, cb2[11].zyzz
add_sat r1.w, cb2[12].z, cb3[49].w
mul r1.z, r1.w, r1.y
mul r1.xy, r1.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
sqrt o3.xy, r1.xyxx
mov o0.xyzw, r0.yzwx
mov o1.w, l(0)
mov o2.z, cb12[0].x
mov o2.w, v1.w
mov o3.z, l(0)
mul o3.w, cb12[5].x, l(0.496078)
ret 
// Approximately 264 instruction slots used
