//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16
//   float4 gDirectionalColour;         // Offset:   16 Size:    16
//   int gNumForwardLights;             // Offset:   32 Size:     4 [unused]
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128 [unused]
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128 [unused]
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128 [unused]
//   float gLightConeScale[8];          // Offset:  432 Size:   116 [unused]
//   float gLightConeOffset[8];         // Offset:  560 Size:   116 [unused]
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80 [unused]
//   float4 globalFogColor;             // Offset:  880 Size:    16 [unused]
//   float4 globalFogColorE;            // Offset:  896 Size:    16 [unused]
//   float4 globalFogColorN;            // Offset:  912 Size:    16 [unused]
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16 [unused]
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer trees_common_locals
// {
//
//   float specularFresnel;             // Offset:    0 Size:     4 [unused]
//   float specularFalloffMult;         // Offset:    4 Size:     4 [unused]
//   float specularIntensityMult;       // Offset:    8 Size:     4 [unused]
//   float3 specMapIntMask;             // Offset:   16 Size:    12 [unused]
//   float bumpiness;                   // Offset:   28 Size:     4 [unused]
//   float4 umGlobalParams;             // Offset:   32 Size:    16 [unused]
//   float4 WindGlobalParams;           // Offset:   48 Size:    16 [unused]
//   float UseTreeNormals;              // Offset:   64 Size:     4 [unused]
//   float SelfShadowing;               // Offset:   68 Size:     4 [unused]
//   float AlphaScale;                  // Offset:   72 Size:     4 [unused]
//   float AlphaTest;                   // Offset:   76 Size:     4
//   float ShadowFalloff;               // Offset:   80 Size:     4 [unused]
//   float AlphaScaleNormal;            // Offset:   84 Size:     4 [unused]
//   float AlphaClampNormal;            // Offset:   88 Size:     4 [unused]
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16
//   float4 gCSMResolution;             // Offset:  224 Size:    16
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// trees_common_locals               cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 1   xyz         1     NONE   float   xyz 
// TEXCOORD                 2   xyz         2     NONE   float   xyz 
// TEXCOORD                 3   xyzw        3     NONE   float   xyzw
// SV_Position              0   xyzw        4      POS   float       
// SV_ClipDistance          0   xyzw        5  CLIPDST   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB1[16], immediateIndexed
dcl_constantbuffer CB2[13], immediateIndexed
dcl_constantbuffer CB3[50], immediateIndexed
dcl_constantbuffer CB12[5], immediateIndexed
dcl_constantbuffer CB6[15], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyzw
dcl_output o0.xyzw
dcl_temps 7
dcl_indexableTemp x0[4], 4
sample r0.xyzw, v0.xyxx, t0.xyzw, s0
ge r1.x, cb12[4].w, r0.w
discard_nz r1.x
mul r0.xyz, r0.xyzx, r0.xyzx
mul r1.xy, cb2[11].zyzz, cb2[11].zyzz
add r1.z, -v0.w, l(1.000000)
add r2.xyz, -v1.xyzx, cb1[15].xyzx
dp3 r1.w, r2.xyzx, cb1[14].xyzx
add r2.xyz, v1.xyzx, -cb1[15].xyzx
mul r3.xyz, r2.yyyy, cb6[1].xyzx
mad r2.xyw, r2.xxxx, cb6[0].xyxz, r3.xyxz
mad r2.xyz, r2.zzzz, cb6[2].xyzx, r2.xywx
mad r3.xyz, r2.xyzx, cb6[4].xyzx, cb6[8].xyzx
mov x0[0].xyz, r3.xyzx
mad r4.xyz, r2.xyzx, cb6[5].xyzx, cb6[9].xyzx
mov x0[1].xyz, r4.xyzx
mad r5.xyz, r2.xyzx, cb6[6].xyzx, cb6[10].xyzx
mov x0[2].xyz, r5.xyzx
mad r2.xyz, r2.xyzx, cb6[7].xyzx, cb6[11].xyzx
mov x0[3].xyz, r2.xyzx
mad r2.z, -cb6[14].z, l(1.500000), l(1.000000)
mul r2.z, r2.z, l(0.500000)
max r2.w, |r5.y|, |r5.x|
lt r2.w, r2.w, r2.z
movc r2.w, r2.w, l(2), l(3)
max r3.z, |r4.y|, |r4.x|
lt r3.z, r3.z, r2.z
movc r2.w, r3.z, l(1), r2.w
max r3.x, |r3.y|, |r3.x|
lt r2.z, r3.x, r2.z
movc r2.z, r2.z, l(0), r2.w
mov r3.xyz, x0[r2.z + 0].xyzx
itof r2.z, r2.z
add r2.w, r2.z, l(0.500000)
mul r2.w, r2.w, l(0.250000)
eq r4.xyzw, l(0.000000, 1.000000, 2.000000, 3.000000), r2.zzzz
and r4.xyzw, r4.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
dp4 r2.z, r4.xyzw, cb6[12].xyzw
dp4 r3.w, r4.xyzw, cb6[13].xyzw
add r3.x, r3.x, l(0.500000)
mad r2.w, r3.y, l(0.250000), r2.w
ne r3.y, r2.z, l(0.000000)
add r2.z, -r2.z, r3.z
deriv_rtx r4.x, r3.x
deriv_rtx r4.yzw, r2.wwzw
deriv_rty r5.y, r3.x
deriv_rty r5.xzw, r2.wwwz
mul r4.yw, r4.yyyw, r5.yyyw
mad r6.xy, r4.xzxx, r5.xzxx, -r4.ywyy
div r4.y, l(1.000000, 1.000000, 1.000000, 1.000000), r6.x
mul r4.z, r4.z, r5.y
mad r6.z, r4.x, r5.w, -r4.z
mul r4.xy, r4.yyyy, r6.yzyy
max r4.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r4.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mad r2.z, -r3.w, r4.x, r2.z
mad r2.z, -r3.w, r4.y, r2.z
movc r2.z, r3.y, r2.z, r3.z
add r3.x, r3.x, cb6[14].z
mad r3.y, cb6[14].w, l(0.250000), r2.w
sample_c_lz r2.z, r3.xyxx, t15.xxxx, s15, r2.z
mad_sat r1.w, r1.w, cb6[0].w, cb6[1].w
max r2.x, |r2.y|, |r2.x|
mad_sat r2.x, r2.x, l(15.000000), l(-6.300000)
add r1.w, -r1.w, l(1.000000)
mad r1.w, r1.w, r2.x, r2.z
mul r1.w, r1.w, r1.w
min r1.w, r1.w, l(1.000000)
mad_sat r2.x, v1.z, cb6[3].x, cb6[3].y
sqrt r2.x, r2.x
mul r2.x, r2.x, cb6[3].z
mad r1.w, r2.x, -r1.w, r1.w
dp3_sat r2.x, v2.xyzx, -cb3[0].xyzx
mul r2.xyz, r0.xyzx, r2.xxxx
mul r2.xyz, r2.xyzx, cb3[1].xyzx
mul r2.xyz, r1.wwww, r2.xyzx
add r1.w, v2.z, cb3[43].w
mul r1.w, r1.w, cb3[44].w
max r1.w, r1.w, l(0.000000)
mad r3.xyz, cb3[47].xyzx, r1.wwww, cb3[48].xyzx
add r2.w, -cb2[12].z, l(1.000000)
mad r4.xyz, cb3[45].xyzx, r1.wwww, cb3[46].xyzx
mul r4.xyz, r4.xyzx, cb2[12].zzzz
mad r3.xyz, r3.xyzx, r2.wwww, r4.xyzx
mul r3.xyz, r1.yyyy, r3.xyzx
mad r4.xyz, cb3[43].xyzx, r1.wwww, cb3[44].xyzx
mov r5.x, cb3[46].w
mov r5.y, cb3[47].w
mov r5.z, cb3[48].w
dp3_sat r1.y, r5.xyzx, v2.xyzx
mad r4.xyz, cb3[49].xyzx, r1.yyyy, r4.xyzx
mad r1.xyw, r4.xyxz, r1.xxxx, r3.xyxz
mul r0.xyz, r0.xyzx, r1.xywx
mul r0.xyz, r0.xyzx, v0.zzzz
mad r0.xyz, r1.zzzz, r2.xyzx, r0.xyzx
add r1.xyz, -r0.xyzx, v3.xyzx
mad o0.xyz, v3.wwww, r1.xyzx, r0.xyzx
add r0.x, -v3.w, l(1.000000)
mul o0.w, r0.w, r0.x
ret 
// Approximately 100 instruction slots used
