//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16 [unused]
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16 [unused]
//   float4 gDirectionalColour;         // Offset:   16 Size:    16 [unused]
//   int gNumForwardLights;             // Offset:   32 Size:     4 [unused]
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128 [unused]
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128 [unused]
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128 [unused]
//   float gLightConeScale[8];          // Offset:  432 Size:   116 [unused]
//   float gLightConeOffset[8];         // Offset:  560 Size:   116 [unused]
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16 [unused]
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16 [unused]
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16 [unused]
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16 [unused]
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16 [unused]
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16 [unused]
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80 [unused]
//   float4 globalFogColor;             // Offset:  880 Size:    16 [unused]
//   float4 globalFogColorE;            // Offset:  896 Size:    16 [unused]
//   float4 globalFogColorN;            // Offset:  912 Size:    16 [unused]
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16 [unused]
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer more_stuff
// {
//
//   float4 gEntitySelectColor[2];      // Offset:    0 Size:    32 [unused]
//   float4 gAmbientOcclusionEffect;    // Offset:   32 Size:    16 [unused]
//   float4 gDynamicBakesAndWetness;    // Offset:   48 Size:    16 [unused]
//   float4 gAlphaRefVec0;              // Offset:   64 Size:    16 [unused]
//   float4 gAlphaRefVec1;              // Offset:   80 Size:    16 [unused]
//   float gAlphaTestRef;               // Offset:   96 Size:     4 [unused]
//   bool gTreesUseDiscard;             // Offset:  100 Size:     4
//   float gReflectionMipCount;         // Offset:  104 Size:     4 [unused]
//   bool gUseTransparencyAA;           // Offset:  108 Size:     4
//   bool gUseFogRay;                   // Offset:  112 Size:     4 [unused]
//
// }
//
// cbuffer trees_common_locals
// {
//
//   float4 umGlobalParams;             // Offset:    0 Size:    16 [unused]
//   float4 WindGlobalParams;           // Offset:   16 Size:    16 [unused]
//   float UseTreeNormals;              // Offset:   32 Size:     4 [unused]
//   float SelfShadowing;               // Offset:   36 Size:     4 [unused]
//   float AlphaScale;                  // Offset:   40 Size:     4
//   float AlphaTest;                   // Offset:   44 Size:     4
//   float ShadowFalloff;               // Offset:   48 Size:     4
//   float AlphaScaleNormal;            // Offset:   52 Size:     4 [unused]
//   float AlphaClampNormal;            // Offset:   56 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// more_stuff                        cbuffer      NA          NA            cb5      1 
// trees_common_locals               cbuffer      NA          NA           cb12      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyz         3     NONE   float   xyz 
// SV_IsFrontFace           0   x           4    FFACE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Coverage              0    N/A    oMask COVERAGE    uint    YES
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000},
                              { 2, 0.250000, 0.250000, 0},
                              { 6, -0.250000, -0.250000, 0},
                              { 0, -0.125000, -0.375000, 0},
                              { 0, 0.375000, -0.125000, 0},
                              { 0, -0.375000, 0.125000, 0},
                              { 0, 0.125000, 0.375000, 0},
                              { 0, 0.062500, -0.187500, 0},
                              { 0, -0.062500, 0.187500, 0},
                              { 0, 0.312500, 0.062500, 0},
                              { 0, -0.187500, -0.312500, 0},
                              { 0, -0.312500, 0.312500, 0},
                              { 0, -0.437500, -0.062500, 0},
                              { 0, 0.187500, 0.437500, 0},
                              { 0, 0.437500, -0.437500, 0} }
dcl_constantbuffer CB2[16], immediateIndexed
dcl_constantbuffer CB3[50], immediateIndexed
dcl_constantbuffer CB5[7], immediateIndexed
dcl_constantbuffer CB12[4], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.xyz
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output oMask
dcl_temps 5
ine r0.x, cb5[6].y, l(0)
ftou r0.yz, v0.xxyx
bfi r0.z, l(1), l(1), r0.z, l(0)
bfi r0.y, l(1), l(0), r0.y, r0.z
dp4 r0.y, cb2[0].xyzw, icb[r0.y + 0].xyzw
lt r0.y, r0.y, l(1.000000)
and r0.x, r0.y, r0.x
discard_nz r0.x
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v2.xyxx, t0.xyzw, s0
mov r1.xyz, r0.xyzx
mov r1.w, v1.w
mul r1.xyzw, r1.wxyz, v1.wxyz
ine r0.x, cb5[6].w, l(0)
ult r0.y, l(1), cb2[15].x
and r0.x, r0.y, r0.x
if_nz r0.x
  deriv_rtx_coarse r0.xz, v2.xxyx
  deriv_rty_coarse r2.xy, v2.xyxx
  firstbit_lo r2.z, cb2[15].x
  iadd r2.z, r2.z, l(-1)
  ult r3.xyz, l(2, 3, 4, 0), cb2[15].xxxx
  if_nz cb2[15].x
    mov r2.w, icb[r2.z + 3].x
    mul r4.xy, r2.xyxx, icb[r2.w + 4].zzzz
    mad r4.xy, icb[r2.w + 4].yyyy, r0.xzxx, r4.xyxx
    add r4.xy, r4.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r2.w, r4.xyxx, t0.xyzw, s0
    mul r2.w, r2.w, v1.w
    mul r2.w, r2.w, cb12[2].z
    dp2 r2.w, r2.wwww, cb2[11].xxxx
    lt r2.w, cb12[2].w, r2.w
    and r2.w, r2.w, l(1)
  else 
    mov r2.w, l(0)
  endif 
  if_nz r0.y
    iadd r0.y, l(1), icb[r2.z + 3].x
    mul r4.xy, r2.xyxx, icb[r0.y + 4].zzzz
    mad r4.xy, icb[r0.y + 4].yyyy, r0.xzxx, r4.xyxx
    add r4.xy, r4.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r4.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.w, r2.w, l(2)
    movc r2.w, r0.y, r3.w, r2.w
  endif 
  if_nz r3.x
    mov r0.y, icb[r2.z + 3].x
    mul r3.xw, r2.xxxy, icb[r0.y + 6].zzzz
    mad r3.xw, icb[r0.y + 6].yyyy, r0.xxxz, r3.xxxw
    add r3.xw, r3.xxxw, v2.xxxy
    sample_indexable(texture2d)(float,float,float,float) r0.y, r3.xwxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.x, r2.w, l(4)
    movc r2.w, r0.y, r3.x, r2.w
  endif 
  if_nz r3.y
    mov r0.y, icb[r2.z + 3].x
    mul r3.xy, r2.xyxx, icb[r0.y + 7].zzzz
    mad r3.xy, icb[r0.y + 7].yyyy, r0.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r3.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.x, r2.w, l(8)
    movc r2.w, r0.y, r3.x, r2.w
  endif 
  if_nz r3.z
    mov r0.y, icb[r2.z + 3].x
    mul r3.xy, r2.xyxx, icb[r0.y + 8].zzzz
    mad r3.xy, icb[r0.y + 8].yyyy, r0.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r3.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.x, r2.w, l(16)
    movc r2.w, r0.y, r3.x, r2.w
  endif 
  ult r3.xyzw, l(5, 6, 7, 8), cb2[15].xxxx
  if_nz r3.x
    mov r0.y, icb[r2.z + 3].x
    mul r4.xy, r2.xyxx, icb[r0.y + 9].zzzz
    mad r4.xy, icb[r0.y + 9].yyyy, r0.xzxx, r4.xyxx
    add r4.xy, r4.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r4.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.x, r2.w, l(32)
    movc r2.w, r0.y, r3.x, r2.w
  endif 
  if_nz r3.y
    mov r0.y, icb[r2.z + 3].x
    mul r3.xy, r2.xyxx, icb[r0.y + 10].zzzz
    mad r3.xy, icb[r0.y + 10].yyyy, r0.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r3.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.x, r2.w, l(64)
    movc r2.w, r0.y, r3.x, r2.w
  endif 
  if_nz r3.z
    mov r0.y, icb[r2.z + 3].x
    mul r3.xy, r2.xyxx, icb[r0.y + 11].zzzz
    mad r3.xy, icb[r0.y + 11].yyyy, r0.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r3.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.x, r2.w, l(128)
    movc r2.w, r0.y, r3.x, r2.w
  endif 
  if_nz r3.w
    iadd r0.y, icb[r2.z + 3].x, l(8)
    mul r3.xy, r2.xyxx, icb[r0.y + 4].zzzz
    mad r3.xy, icb[r0.y + 4].yyyy, r0.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r3.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.x, r2.w, l(256)
    movc r2.w, r0.y, r3.x, r2.w
  endif 
  ult r3.xyzw, l(9, 10, 11, 12), cb2[15].xxxx
  if_nz r3.x
    iadd r0.y, icb[r2.z + 3].x, l(9)
    mul r4.xy, r2.xyxx, icb[r0.y + 4].zzzz
    mad r4.xy, icb[r0.y + 4].yyyy, r0.xzxx, r4.xyxx
    add r4.xy, r4.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r4.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.x, r2.w, l(512)
    movc r2.w, r0.y, r3.x, r2.w
  endif 
  if_nz r3.y
    mov r0.y, icb[r2.z + 3].x
    mul r3.xy, r2.xyxx, icb[r0.y + 14].zzzz
    mad r3.xy, icb[r0.y + 14].yyyy, r0.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r3.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.x, r2.w, l(1024)
    movc r2.w, r0.y, r3.x, r2.w
  endif 
  if_nz r3.z
    mov r0.y, icb[r2.z + 3].x
    mul r3.xy, r2.xyxx, icb[r0.y + 15].zzzz
    mad r3.xy, icb[r0.y + 15].yyyy, r0.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r3.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r3.x, r2.w, l(2048)
    movc r2.w, r0.y, r3.x, r2.w
  endif 
  if_nz r3.w
    mov r0.y, icb[r2.z + 3].x
    mul r3.xy, r2.xyxx, icb[r0.y + 16].zzzz
    mad r3.xy, icb[r0.y + 16].yyyy, r0.xzxx, r3.xyxx
    add r3.xy, r3.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.y, r3.xyxx, t0.xwyz, s0
    mul r0.y, r0.y, v1.w
    mul r0.y, r0.y, cb12[2].z
    dp2 r0.y, r0.yyyy, cb2[11].xxxx
    lt r0.y, cb12[2].w, r0.y
    iadd r2.z, r2.w, l(4096)
    movc r2.w, r0.y, r2.z, r2.w
  endif 
  ult r0.y, l(13), cb2[15].x
  if_nz r0.y
    mul r2.xy, r2.xyxx, l(-0.437500, -0.437500, 0.000000, 0.000000)
    mad r0.xy, r0.xzxx, l(0.437500, 0.437500, 0.000000, 0.000000), r2.xyxx
    add r0.xy, r0.xyxx, v2.xyxx
    sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t0.wxyz, s0
    mul r0.x, r0.x, v1.w
    mul r0.x, r0.x, cb12[2].z
    dp2 r0.x, r0.xxxx, cb2[11].xxxx
    lt r0.x, cb12[2].w, r0.x
    iadd r0.y, r2.w, l(8192)
    movc r2.w, r0.x, r0.y, r2.w
  endif 
  ieq r0.x, r2.w, l(0)
  discard_nz r0.x
  mov r1.x, l(1.000000)
  mov oMask, r2.w
else 
  mul r0.x, r0.w, r1.x
  mul r0.y, cb2[11].x, cb12[2].z
  dp2 r1.x, r0.yyyy, r0.xxxx
  ge r0.x, cb12[2].w, r1.x
  discard_nz r0.x
  mov oMask, l(-1)
endif 
mul r0.xy, v2.zzzz, cb2[11].zyzz
add_sat r0.w, cb2[12].z, cb3[49].w
mul r0.z, r0.w, r0.y
mul r0.xy, r0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
sqrt o3.xy, r0.xyxx
mov o0.xyzw, r1.yzwx
mov o1.xyz, v3.xyzx
mov o1.w, l(0)
mov o2.xyz, l(0,0,0,0)
mov o2.w, v2.w
mov o3.z, l(0)
mul o3.w, cb12[3].x, l(0.496078)
ret 
// Approximately 231 instruction slots used
