//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer rage_matrices
// {
//
//   row_major float4x4 gWorld;         // Offset:    0 Size:    64 [unused]
//   row_major float4x4 gWorldView;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 gWorldViewProj; // Offset:  128 Size:    64 [unused]
//   row_major float4x4 gViewInverse;   // Offset:  192 Size:    64
//
// }
//
// cbuffer misc_globals
// {
//
//   float4 globalFade;                 // Offset:    0 Size:    16 [unused]
//   float globalHeightScale;           // Offset:   16 Size:     4 [unused]
//   float4 g_Rage_Tessellation_CameraPosition;// Offset:   32 Size:    16 [unused]
//   float4 g_Rage_Tessellation_CameraZAxis;// Offset:   48 Size:    16 [unused]
//   float4 g_Rage_Tessellation_ScreenSpaceErrorParams;// Offset:   64 Size:    16 [unused]
//   float4 g_Rage_Tessellation_LinearScale;// Offset:   80 Size:    16 [unused]
//   float4 g_Rage_Tessellation_Frustum[4];// Offset:   96 Size:    64 [unused]
//   float4 g_Rage_Tessellation_Epsilons;// Offset:  160 Size:    16 [unused]
//   float4 globalScalars;              // Offset:  176 Size:    16
//   float4 globalScalars2;             // Offset:  192 Size:    16
//   float4 globalScalars3;             // Offset:  208 Size:    16
//   float4 globalScreenSize;           // Offset:  224 Size:    16 [unused]
//   uint4 gTargetAAParams;             // Offset:  240 Size:    16 [unused]
//   float4 colorize;                   // Offset:  256 Size:    16 [unused]
//   float4 gGlobalParticleShadowBias;  // Offset:  272 Size:    16 [unused]
//   float gGlobalParticleDofAlphaScale;// Offset:  288 Size:     4 [unused]
//   float gGlobalFogIntensity;         // Offset:  292 Size:     4 [unused]
//   float4 gPlayerLFootPos;            // Offset:  304 Size:    16 [unused]
//   float4 gPlayerRFootPos;            // Offset:  320 Size:    16 [unused]
//
// }
//
// cbuffer lighting_globals
// {
//
//   float4 gDirectionalLight;          // Offset:    0 Size:    16
//   float4 gDirectionalColour;         // Offset:   16 Size:    16
//   int gNumForwardLights;             // Offset:   32 Size:     4
//   float4 gLightPositionAndInvDistSqr[8];// Offset:   48 Size:   128
//   float4 gLightDirectionAndFalloffExponent[8];// Offset:  176 Size:   128
//   float4 gLightColourAndCapsuleExtent[8];// Offset:  304 Size:   128
//   float gLightConeScale[8];          // Offset:  432 Size:   116
//   float gLightConeOffset[8];         // Offset:  560 Size:   116
//   float4 gLightNaturalAmbient0;      // Offset:  688 Size:    16
//   float4 gLightNaturalAmbient1;      // Offset:  704 Size:    16
//   float4 gLightArtificialIntAmbient0;// Offset:  720 Size:    16
//   float4 gLightArtificialIntAmbient1;// Offset:  736 Size:    16
//   float4 gLightArtificialExtAmbient0;// Offset:  752 Size:    16
//   float4 gLightArtificialExtAmbient1;// Offset:  768 Size:    16
//   float4 gDirectionalAmbientColour;  // Offset:  784 Size:    16
//   float4 globalFogParams[5];         // Offset:  800 Size:    80
//   float4 globalFogColor;             // Offset:  880 Size:    16
//   float4 globalFogColorE;            // Offset:  896 Size:    16
//   float4 globalFogColorN;            // Offset:  912 Size:    16
//   float4 globalFogColorMoon;         // Offset:  928 Size:    16
//   float4 gReflectionTweaks;          // Offset:  944 Size:    16 [unused]
//
// }
//
// cbuffer vehiclecommonlocals
// {
//
//   float3 matDiffuseColor;            // Offset:    0 Size:    12
//   float4 matDiffuseColor2;           // Offset:   16 Size:    16 [unused]
//   float4 dirtLevelMod;               // Offset:   32 Size:    16 [unused]
//   float3 specMapIntMask;             // Offset:   48 Size:    12 [unused]
//   float reflectivePower;             // Offset:   60 Size:     4 [unused]
//   float envEffThickness;             // Offset:   64 Size:     4 [unused]
//   float2 envEffScale;                // Offset:   68 Size:     8 [unused]
//   float envEffTexTileUV;             // Offset:   76 Size:     4 [unused]
//
// }
//
// cbuffer csmshader
// {
//
//   float4 gCSMShaderVars_shared[12];  // Offset:    0 Size:   192
//   float4 gCSMDepthBias;              // Offset:  192 Size:    16
//   float4 gCSMDepthSlopeBias;         // Offset:  208 Size:    16
//   float4 gCSMResolution;             // Offset:  224 Size:    16
//   row_major float4x4 gLocalLightShadowData[8];// Offset:  240 Size:   512 [unused]
//   float4 gShadowTexParam;            // Offset:  752 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DiffuseSampler                    sampler      NA          NA             s0      1 
// gCSMShadowTextureSamp           sampler_c      NA          NA            s15      1 
// DiffuseSampler                    texture  float4          2d             t0      1 
// gCSMShadowTexture                 texture  float4          2d            t15      1 
// rage_matrices                     cbuffer      NA          NA            cb1      1 
// misc_globals                      cbuffer      NA          NA            cb2      1 
// lighting_globals                  cbuffer      NA          NA            cb3      1 
// csmshader                         cbuffer      NA          NA            cb6      1 
// vehiclecommonlocals               cbuffer      NA          NA           cb11      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// TEXCOORD                10     z         0     NONE   float     z 
// TEXCOORD                 1   xyz         1     NONE   float   xyz 
// TEXCOORD                 2   xyzw        2     NONE   float   xyz 
// TEXCOORD                 3   xyz         3     NONE   float       
// TEXCOORD                 6   xyzw        4     NONE   float   x  w
// SV_Position              0   xyzw        5      POS   float       
// SV_ClipDistance          0   xyzw        6  CLIPDST   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   x           1   TARGET   float   x   
// SV_Target                2   x           2   TARGET   float   x   
//
ps_4_0
dcl_constantbuffer CB1[16], immediateIndexed
dcl_constantbuffer CB2[14], immediateIndexed
dcl_constantbuffer CB3[59], immediateIndexed
dcl_constantbuffer CB11[1], immediateIndexed
dcl_constantbuffer CB6[15], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s15, mode_comparison
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v0.xy
dcl_input_ps linear v0.z
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v4.xw
dcl_output o0.xyzw
dcl_output o1.x
dcl_output o2.x
dcl_temps 22
dcl_indexableTemp x0[4], 4
sample r0.xyzw, v0.xyxx, t0.xyzw, s0
mul r0.xyz, r0.xyzx, cb11[0].xyzx
mul r0.w, r0.w, v4.w
add_sat r1.x, cb2[12].z, cb3[49].w
mul r1.x, r1.x, cb2[11].y
mul r1.y, v4.x, l(0.250000)
mul r0.xyz, r0.xyzx, r0.xyzx
add r2.xyz, -v2.xyzx, cb1[15].xyzx
dp3 r1.z, r2.xyzx, r2.xyzx
rsq r1.z, r1.z
mul r3.xyz, r1.zzzz, r2.xyzx
mul r1.z, cb2[11].z, cb2[11].z
dp3 r1.w, r2.xyzx, cb1[14].xyzx
add r2.xyz, v2.xyzx, -cb1[15].xyzx
mul r4.xyz, r2.yyyy, cb6[1].xyzx
mad r4.xyz, r2.xxxx, cb6[0].xyzx, r4.xyzx
mad r4.xyz, r2.zzzz, cb6[2].xyzx, r4.xyzx
mad r5.xyz, r4.xyzx, cb6[4].xyzx, cb6[8].xyzx
mov x0[0].xyz, r5.xyzx
mad r6.xyz, r4.xyzx, cb6[5].xyzx, cb6[9].xyzx
mov x0[1].xyz, r6.xyzx
mad r7.xyz, r4.xyzx, cb6[6].xyzx, cb6[10].xyzx
mov x0[2].xyz, r7.xyzx
mad r4.xyz, r4.xyzx, cb6[7].xyzx, cb6[11].xyzx
mov x0[3].xyz, r4.xyzx
mul r8.yw, cb6[14].zzzw, l(0.000000, -0.346097, 0.000000, 0.328490)
mad r2.w, -cb6[14].z, l(1.500000), l(1.000000)
mul r2.w, r2.w, l(0.500000)
max r3.w, |r7.y|, |r7.x|
lt r3.w, r3.w, r2.w
movc r3.w, r3.w, l(2), l(3)
max r4.z, |r6.y|, |r6.x|
lt r4.z, r4.z, r2.w
movc r3.w, r4.z, l(1), r3.w
max r4.z, |r5.y|, |r5.x|
lt r2.w, r4.z, r2.w
movc r2.w, r2.w, l(0), r3.w
mov r5.xyz, x0[r2.w + 0].xyzx
itof r2.w, r2.w
add r3.w, r2.w, l(0.500000)
mul r3.w, r3.w, l(0.250000)
eq r6.xyzw, l(0.000000, 1.000000, 2.000000, 3.000000), r2.wwww
and r6.xyzw, r6.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
dp4 r2.w, r6.xyzw, cb6[12].xyzw
dp4 r4.z, r6.xyzw, cb6[13].xyzw
add r6.x, r5.x, l(0.500000)
mad r6.y, r5.y, l(0.250000), r3.w
ne r3.w, r2.w, l(0.000000)
add r2.w, -r2.w, r5.z
deriv_rtx r7.xyw, r6.xyxy
deriv_rtx r7.z, r2.w
deriv_rty r9.xyz, r6.yxyy
deriv_rty r9.w, r2.w
mul r5.xy, r7.ywyy, r9.ywyy
mad r10.xy, r7.xzxx, r9.xzxx, -r5.xyxx
div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r10.x
mul r5.x, r7.z, r9.y
mad r10.z, r7.x, r9.w, -r5.x
mul r5.xy, r4.wwww, r10.yzyy
max r5.xy, r5.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r5.xy, r5.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
mad r2.w, -r4.z, r5.x, r2.w
mad r2.w, -r4.z, r5.y, r2.w
movc r8.z, r3.w, r2.w, r5.z
mov r6.z, l(0)
add r5.xyz, r6.xyzx, r8.ywzy
mul r8.xy, cb6[14].zwzz, l(-0.799291, 0.201741, 0.000000, 0.000000)
add r7.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(-0.031176, 0.179338, 0.000000, 0.000000)
add r9.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(0.514749, 0.253502, 0.000000, 0.000000)
add r10.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(-0.072870, 0.008097, 0.000000, 0.000000)
add r11.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(-0.969781, 0.034522, 0.000000, 0.000000)
add r12.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(0.545547, 0.024129, 0.000000, 0.000000)
add r13.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(-0.028906, -0.136785, 0.000000, 0.000000)
add r14.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(-0.479511, -0.244833, 0.000000, 0.000000)
add r15.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(0.758788, -0.112109, 0.000000, 0.000000)
add r16.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(0.339353, -0.249328, 0.000000, 0.000000)
add r17.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(1.070598, 0.208123, 0.000000, 0.000000)
add r18.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(1.294038, -0.018078, 0.000000, 0.000000)
add r19.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(-0.747563, -0.113974, 0.000000, 0.000000)
add r20.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(0.947722, -0.248764, 0.000000, 0.000000)
add r21.xyz, r6.xyzx, r8.xyzx
mul r8.xy, cb6[14].zwzz, l(-1.343153, -0.088584, 0.000000, 0.000000)
add r6.xyz, r6.xyzx, r8.xyzx
sample_c_lz r5.x, r5.xyxx, t15.xxxx, s15, r5.z
sample_c_lz r5.y, r7.xyxx, t15.xxxx, s15, r7.z
sample_c_lz r5.z, r9.xyxx, t15.xxxx, s15, r9.z
sample_c_lz r5.w, r10.xyxx, t15.xxxx, s15, r10.z
sample_c_lz r7.x, r11.xyxx, t15.xxxx, s15, r11.z
sample_c_lz r7.y, r12.xyxx, t15.xxxx, s15, r12.z
sample_c_lz r7.z, r13.xyxx, t15.xxxx, s15, r13.z
sample_c_lz r7.w, r14.xyxx, t15.xxxx, s15, r14.z
sample_c_lz r8.x, r15.xyxx, t15.xxxx, s15, r15.z
sample_c_lz r8.y, r16.xyxx, t15.xxxx, s15, r16.z
sample_c_lz r8.z, r17.xyxx, t15.xxxx, s15, r17.z
sample_c_lz r8.w, r18.xyxx, t15.xxxx, s15, r18.z
sample_c_lz r9.x, r19.xyxx, t15.xxxx, s15, r19.z
sample_c_lz r9.y, r20.xyxx, t15.xxxx, s15, r20.z
sample_c_lz r9.z, r21.xyxx, t15.xxxx, s15, r21.z
sample_c_lz r9.w, r6.xyxx, t15.xxxx, s15, r6.z
add r5.xyzw, r5.xyzw, r7.xyzw
add r5.xyzw, r8.xyzw, r5.xyzw
add r5.xyzw, r9.xyzw, r5.xyzw
dp4 r2.w, r5.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mad_sat r1.w, r1.w, cb6[0].w, cb6[1].w
max r3.w, |r4.y|, |r4.x|
mad_sat r3.w, r3.w, l(15.000000), l(-6.300000)
add r1.w, -r1.w, l(1.000000)
mul r1.w, r3.w, r1.w
mad r1.w, r2.w, l(0.062500), r1.w
mul r1.xw, r1.xxxw, r1.xxxw
min r1.w, r1.w, l(1.000000)
mad_sat r2.w, v2.z, cb6[3].x, cb6[3].y
sqrt r2.w, r2.w
mul r2.w, r2.w, cb6[3].z
mad r1.w, r2.w, -r1.w, r1.w
dp3_sat r2.w, v1.xyzx, -cb3[0].xyzx
dp3_sat r3.x, r3.xyzx, v1.xyzx
mul r3.yzw, r0.xxyz, r2.wwww
mul r3.yzw, r3.yyzw, cb3[1].xxyz
ige r2.w, l(0), cb3[2].x
if_z r2.w
  eq r4.x, cb3[19].w, l(0.000000)
  add r4.yzw, -v2.xxyz, cb3[3].xxyz
  add r5.xyz, v2.xyzx, -cb3[3].xyzx
  dp3 r5.x, r5.xyzx, cb3[11].xyzx
  div_sat r5.x, r5.x, cb3[19].w
  mul r5.x, r5.x, cb3[19].w
  mad r5.xyz, cb3[11].xyzx, r5.xxxx, cb3[3].xyzx
  add r5.xyz, r5.xyzx, -v2.xyzx
  movc r4.xyz, r4.xxxx, r4.yzwy, r5.xyzx
  dp3 r4.w, r4.xyzx, r4.xyzx
  add r4.xyz, r4.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
  dp3 r5.x, r4.xyzx, r4.xyzx
  rsq r5.x, r5.x
  mul r4.xyz, r4.xyzx, r5.xxxx
  mad_sat r4.w, -r4.w, cb3[3].w, l(1.000000)
  add r5.x, -cb3[11].w, l(1.000000)
  mad r5.x, r5.x, r4.w, cb3[11].w
  div r4.w, r4.w, r5.x
  dp3 r5.x, r4.xyzx, -cb3[11].xyzx
  mad_sat r5.x, r5.x, cb3[27].x, cb3[35].x
  dp3_sat r4.x, r4.xyzx, v1.xyzx
  mul r4.x, r5.x, r4.x
  mul r4.x, r4.w, r4.x
  mul r4.xyz, r4.xxxx, cb3[19].xyzx
  mul r4.xyz, r0.xyzx, r4.xyzx
else 
  mov r4.xyz, l(0,0,0,0)
endif 
ilt r4.w, l(0), cb3[2].x
if_nz r4.w
  ige r5.x, l(1), cb3[2].x
  or r4.w, r2.w, r4.w
  movc r2.w, r5.x, r4.w, r2.w
  if_z r2.w
    eq r4.w, cb3[20].w, l(0.000000)
    add r5.xyz, -v2.xyzx, cb3[4].xyzx
    add r6.xyz, v2.xyzx, -cb3[4].xyzx
    dp3 r5.w, r6.xyzx, cb3[12].xyzx
    div_sat r5.w, r5.w, cb3[20].w
    mul r5.w, r5.w, cb3[20].w
    mad r6.xyz, cb3[12].xyzx, r5.wwww, cb3[4].xyzx
    add r6.xyz, r6.xyzx, -v2.xyzx
    movc r5.xyz, r4.wwww, r5.xyzx, r6.xyzx
    dp3 r4.w, r5.xyzx, r5.xyzx
    add r5.xyz, r5.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r5.w, r5.xyzx, r5.xyzx
    rsq r5.w, r5.w
    mul r5.xyz, r5.wwww, r5.xyzx
    mad_sat r4.w, -r4.w, cb3[4].w, l(1.000000)
    add r5.w, -cb3[12].w, l(1.000000)
    mad r5.w, r5.w, r4.w, cb3[12].w
    div r4.w, r4.w, r5.w
    dp3 r5.w, r5.xyzx, -cb3[12].xyzx
    mad_sat r5.w, r5.w, cb3[28].x, cb3[36].x
    dp3_sat r5.x, r5.xyzx, v1.xyzx
    mul r5.x, r5.w, r5.x
    mul r4.w, r4.w, r5.x
    mul r5.xyz, r4.wwww, cb3[20].xyzx
    mad r4.xyz, r5.xyzx, r0.xyzx, r4.xyzx
  endif 
else 
  mov r2.w, l(-1)
endif 
if_z r2.w
  ige r4.w, l(2), cb3[2].x
  or r2.w, r2.w, r4.w
  if_z r2.w
    eq r4.w, cb3[21].w, l(0.000000)
    add r5.xyz, -v2.xyzx, cb3[5].xyzx
    add r6.xyz, v2.xyzx, -cb3[5].xyzx
    dp3 r5.w, r6.xyzx, cb3[13].xyzx
    div_sat r5.w, r5.w, cb3[21].w
    mul r5.w, r5.w, cb3[21].w
    mad r6.xyz, cb3[13].xyzx, r5.wwww, cb3[5].xyzx
    add r6.xyz, r6.xyzx, -v2.xyzx
    movc r5.xyz, r4.wwww, r5.xyzx, r6.xyzx
    dp3 r4.w, r5.xyzx, r5.xyzx
    add r5.xyz, r5.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r5.w, r5.xyzx, r5.xyzx
    rsq r5.w, r5.w
    mul r5.xyz, r5.wwww, r5.xyzx
    mad_sat r4.w, -r4.w, cb3[5].w, l(1.000000)
    add r5.w, -cb3[13].w, l(1.000000)
    mad r5.w, r5.w, r4.w, cb3[13].w
    div r4.w, r4.w, r5.w
    dp3 r5.w, r5.xyzx, -cb3[13].xyzx
    mad_sat r5.w, r5.w, cb3[29].x, cb3[37].x
    dp3_sat r5.x, r5.xyzx, v1.xyzx
    mul r5.x, r5.w, r5.x
    mul r4.w, r4.w, r5.x
    mul r5.xyz, r4.wwww, cb3[21].xyzx
    mad r4.xyz, r5.xyzx, r0.xyzx, r4.xyzx
  endif 
else 
  mov r2.w, l(-1)
endif 
if_z r2.w
  ige r4.w, l(3), cb3[2].x
  or r2.w, r2.w, r4.w
  if_z r2.w
    eq r2.w, cb3[22].w, l(0.000000)
    add r5.xyz, -v2.xyzx, cb3[6].xyzx
    add r6.xyz, v2.xyzx, -cb3[6].xyzx
    dp3 r4.w, r6.xyzx, cb3[14].xyzx
    div_sat r4.w, r4.w, cb3[22].w
    mul r4.w, r4.w, cb3[22].w
    mad r6.xyz, cb3[14].xyzx, r4.wwww, cb3[6].xyzx
    add r6.xyz, r6.xyzx, -v2.xyzx
    movc r5.xyz, r2.wwww, r5.xyzx, r6.xyzx
    dp3 r2.w, r5.xyzx, r5.xyzx
    add r5.xyz, r5.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    dp3 r4.w, r5.xyzx, r5.xyzx
    rsq r4.w, r4.w
    mul r5.xyz, r4.wwww, r5.xyzx
    mad_sat r2.w, -r2.w, cb3[6].w, l(1.000000)
    add r4.w, -cb3[14].w, l(1.000000)
    mad r4.w, r4.w, r2.w, cb3[14].w
    div r2.w, r2.w, r4.w
    dp3 r4.w, r5.xyzx, -cb3[14].xyzx
    mad_sat r4.w, r4.w, cb3[30].x, cb3[38].x
    dp3_sat r5.x, r5.xyzx, v1.xyzx
    mul r4.w, r4.w, r5.x
    mul r2.w, r2.w, r4.w
    mul r5.xyz, r2.wwww, cb3[22].xyzx
    mad r4.xyz, r5.xyzx, r0.xyzx, r4.xyzx
  endif 
endif 
mad r3.yzw, r3.yyzw, r1.wwww, r4.xxyz
add r1.w, v1.z, cb3[43].w
mul r1.w, r1.w, cb3[44].w
max r1.w, r1.w, l(0.000000)
mad r4.xyz, cb3[47].xyzx, r1.wwww, cb3[48].xyzx
add r2.w, -cb2[12].z, l(1.000000)
mad r5.xyz, cb3[45].xyzx, r1.wwww, cb3[46].xyzx
mul r5.xyz, r5.xyzx, cb2[12].zzzz
mad r4.xyz, r4.xyzx, r2.wwww, r5.xyzx
mul r4.xyz, r1.xxxx, r4.xyzx
mad r5.xyz, cb3[43].xyzx, r1.wwww, cb3[44].xyzx
mov r6.x, cb3[46].w
mov r6.y, cb3[47].w
mov r6.z, cb3[48].w
dp3_sat r1.x, r6.xyzx, v1.xyzx
mad r5.xyz, cb3[49].xyzx, r1.xxxx, r5.xyzx
mad r1.xzw, r5.xxyz, r1.zzzz, r4.xxyz
mad r1.xzw, r1.xxzw, r0.xxyz, r3.yyzw
mul r1.y, r1.y, r3.x
mad r0.xyz, r0.xyzx, r1.yyyy, r1.xzwx
mul r0.w, r0.w, cb2[11].x
dp3 r1.x, r2.xyzx, r2.xyzx
sqrt r1.y, r1.x
add r1.z, r1.y, -cb3[50].x
max r1.z, r1.z, l(0.000000)
div r1.y, r1.z, r1.y
mul r1.y, r1.y, r2.z
mul r1.w, r1.y, cb3[52].z
lt r1.y, l(0.010000), |r1.y|
mul r2.w, r1.w, l(-1.442695)
exp r2.w, r2.w
add r2.w, -r2.w, l(1.000000)
div r1.w, r2.w, r1.w
movc r1.y, r1.y, r1.w, l(1.000000)
mul r1.w, r1.z, cb3[51].w
mul r1.y, r1.y, r1.w
min r1.y, r1.y, l(1.000000)
mul r1.y, r1.y, l(1.442695)
exp r1.y, r1.y
min r1.y, r1.y, l(1.000000)
add r1.y, -r1.y, l(1.000000)
mul r1.w, r1.y, cb3[52].y
rsq r1.x, r1.x
mul r2.xyz, r1.xxxx, r2.xyzx
dp3_sat r1.x, r2.xyzx, cb3[54].xyzx
log r1.x, r1.x
mul r1.x, r1.x, cb3[54].w
exp r1.x, r1.x
dp3_sat r2.x, r2.xyzx, cb3[53].xyzx
log r2.x, r2.x
mul r2.x, r2.x, cb3[53].w
exp r2.x, r2.x
mad r1.y, -r1.y, cb3[52].y, l(1.000000)
mul r1.y, r1.y, cb3[51].y
add r2.y, r1.z, -cb3[52].x
max r2.y, r2.y, l(0.000000)
mul r2.y, r2.y, cb3[51].x
mul r2.y, r2.y, l(1.442695)
exp r2.y, r2.y
add r2.y, -r2.y, l(1.000000)
mad_sat r1.w, r1.y, r2.y, r1.w
mul r1.z, r1.z, -cb3[51].z
mul r1.z, r1.z, l(1.442695)
exp r1.z, r1.z
add r1.z, -r1.z, l(1.000000)
add r2.yzw, -cb3[56].xxyz, cb3[58].xxyz
mad r2.yzw, r1.xxxx, r2.yyzw, cb3[56].xxyz
add r3.xyz, -r2.yzwy, cb3[55].xyzx
mad r2.xyz, r2.xxxx, r3.xyzx, r2.yzwy
add r2.xyz, r2.xyzx, -cb3[57].xyzx
mad r2.xyz, r1.zzzz, r2.xyzx, cb3[57].xyzx
add r3.x, -r2.x, cb3[55].w
add r3.y, -r2.y, cb3[56].w
add r3.z, -r2.z, cb3[57].w
mad r1.xyz, r1.yyyy, r3.xyzx, r2.xyzx
add r1.xyz, -r0.xyzx, r1.xyzx
mad r0.xyz, r1.wwww, r1.xyzx, r0.xyzx
mul o0.xyz, r0.xyzx, cb2[13].zzzz
lt r0.x, l(0.300000), r0.w
and r0.x, r0.x, l(0x3f800000)
mul o1.x, r0.x, v0.z
mov o0.w, r0.w
mov o2.x, r0.x
ret 
// Approximately 345 instruction slots used
